### PR TITLE
chore: update node to 16

### PR DESCRIPTION
**Pull request by birkskyum**
The current Node LTS is 16, bundling the npm v8 which use package-lock.json v2 format.

<changelog>Update node to 16</changelog>

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for taking the time to look into this. Currently, we recommend using `nvm use 14`, which keeps the problems with package lockfiles out of the way. Does `nvm use 16` work with this codebase?

**Comment by wipfli** [comment]
If you update node and npm, please also edit https://github.com/maplibre/maplibre-gl-js/blob/main/CONTRIBUTING.md

**Comment by birkskyum** [comment]
I can run the codebase locally, even with node 17, but I have added a commit here that effectively bumps node to 16 in the github workflows - so we can see how well the codebase can support it.

**Comment by birkskyum** [comment]
I bumped node-canvas and gl because their newer versions does have node 16 support. Can we rerun the tests?

**Comment by birkskyum** [comment]
Awesome! Let me know if anything is holding this back.

**Comment by HarelM** [comment]
I think the only thing holding this back is my hesitation to upgrade my dev env to node 16... :-(
Other than that, I think we should move forward. :-)

**Review by HarelM — APPROVED** [review]

**Comment by birkskyum** [comment]
> I think the only thing holding this back is my hesitation to upgrade my dev env to node 16... :-( Other than that, I think we should move forward. :-)

Great :) nvm to the rescus. I'll rebase the affected pr's to this branch then.

**Comment by birkskyum** [comment]
@wipfli , @astridx , @HarelM - I love what you have done to this repo since the fork - setting up a pipeline, typescript, jest etc. It's a big project, so if you can use an extra set of hands, I'd be happy to chip in.

**Comment by HarelM** [comment]
We'd appreciate any extra hands :-)
Let us know if you would like to be added as a maintainer.

**Comment by birkskyum** [comment]
> We'd appreciate any extra hands :-) Let us know if you would like to be added as a maintainer.

Alright, that would be great actually :)

**Comment by HarelM** [comment]
Added as a maintainer. Godspeed!
Feel free to ping me in maplibre slack if you need to say something in private.
I'm pushing the button... :-)

**Comment by wipfli** [comment]
Welcome to MapLibre, Birk!

**Pull request merged**
