### PR TITLE
Update to node 14 and upgrade libraries

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Upgrade development environment to be up-to-date.

This is a rework of PR #190.
@astridx feel free to send PR into this branch (node-14). I'll try to do my best to redo the work...

 - [x] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by HarelM** [comment]
OK, Updated the ci files.
I think circle ci is not in use any more, I think I'll remove it.

The problem is that tap and flow do not work well together with node 14, in terms of importing files without file extension.
Although this works when adding the parameter `--experimental-specifier-resolution=node` it break the flow removal code, I think, not sure...

Worth noting that tap is far down the bottom of this chart.
https://www.npmtrends.com/ava-vs-jest-vs-karma-vs-mocha-vs-tap

I'm familiar with karma from my angular work, but maybe we can use jest somehow to resolve this mess...
I'll use this branch for my experiments.

**Comment by astridx** [comment]
> The problem is that tap and flow do not work well together with node 14, in terms of importing files without file extension.
> Although this works when adding the parameter `--experimental-specifier-resolution=node` it break the flow removal code, I think, not sure...

Because these tests worked in my last attempt, I just uploaded my play branch. Maybe you would like to have a look.
https://github.com/maplibre/maplibre-gl-js/compare/main...astridx:play?expand=1

I think that tap works with flow. Here you can see that there is a parameter for this: https://node-tap.org/docs/using-with/. 

But, in this repo there are special cases. We don't use the general library https://github.com/facebook/flow, but.
https://github.com/mapbox/flow-remove-types.

I tried the `--flow` parameter with tape, but it didn't work. And I tried to use https://github.com/facebook/flow. It didn't work either. 

Translated with www.DeepL.com/Translator (free version)

**Comment by HarelM** [comment]
I'm not saying it's not possible, but it's sure as hell not out-of-the-box. I've looked at the solution you found and it felt "too hackish" to me.
After a long thought about this subject I decided the best approach would be to use typescript and jest. See #209.
So if you really want to push this forward it's OK by me, but I think investing our time in #209 would be better.
You can also read about it in the slack channel.
Let me know what you decide.

**Comment by wipfli** [comment]
I will close this pull request and delete the `node-14` branch in favor of #209 which actually has cherry-picked the changes from this pull request.

**Pull request closed without merging**
