### PR TITLE
Chalk

### PR DESCRIPTION
**Pull request by astridx**
## Launch Checklist

See https://github.com/maplibre/maplibre-gl-js/issues/715

Output of `npm run test-expressions`

Before 

After

I wonder why this change does not show up in `package.lock`. I have called npm ci. Is that OK for a removal?

 - [ x ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

### CODE REVIEW

**Comment by wipfli** [comment]
Use `npm uninstall chalk`.

**Comment by birkskyum** [comment]
Given that it's already removed from package.json, you will have to rebase to main and run `npm install` with node 16.

**Comment by astridx** [comment]
Thank you @wipfli and @birkskyum .
Now this should be fine.

**Comment by HarelM** [comment]
What's the motivation on removing this package? It seems useful, isn't it?

**Comment by astridx** [comment]
> What's the motivation on removing this package? It seems useful, isn't it?

Less redundances. See https://github.com/maplibre/maplibre-gl-js/pull/699#discussion_r763175120

**Comment by HarelM** [comment]
Can you try using console.warn and console.error instead if yellow and red?

**Review by HarelM — APPROVED** [review]

**Comment by astridx** [comment]
> npm run test-expressions

I tried it, but it does not change the color in my console. See https://stackoverflow.com/questions/51449019/what-is-the-difference-between-console-log-and-console-error-in-js/51449060#51449060

**Pull request merged**
