### PR TITLE
fix link in COMMUNITY.md

### LINKED ISSUE #1617: 404 link to Community.md file
Hey,

https://github.com/maplibre/maplibre-gl-js/blob/main/COMMUNITY.md

currently has a link to

https://github.com/maplibre/maplibre/blob/main/COMMUNITY.md

which is 404.

I'm unsure whether it'd be better to link to https://github.com/maplibre/maplibre/ simply, or some file in that repo e.g., CHARTER.md..? I'd be happy to open a PR with an updated link.

Cheers

### PR DESCRIPTION
**Pull request by gregsadetsky**
documentation-only fix

fixes #1617

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
PR is still failing on coverage 😕 I'll take care of that...

**Comment by HarelM** [comment]
I've created this PR to fix this issue: #1621. Once merged I'll let you know so you could update your fork and I'll merge this.
I know this doesn't break any test, but it's a good practice to see that the fix is working on a fork and not just branches of this repo...

**Comment by HarelM** [comment]
@gregsadetsky Can you sync your fork please? I hope now the issue will be solved.
Thanks for you patiences.

**Comment by gregsadetsky** [comment]
@HarelM done! fingers crossed

**Comment by HarelM** [comment]
Didn't work :-(

**Comment by HarelM** [comment]
No, no, it's because I'm not very good at what I do... :-)
You are doing the right thing.
Can you try and update your firk again?

**Comment by HarelM** [comment]
Last time you'll need to update, I swear :-)
Thanks for you patience...

**Pull request merged**
