### PR TITLE
simplify script invocation

### PR DESCRIPTION
**Pull request by rotu**
1. Specify loader/module options in tsconfig instead of command line
2. Don't override memory limits for test-render (unneeded?)

### CODE REVIEW

**Review by birkskyum — APPROVED** [review]
Much better, thanks!

**Comment by wipfli** [comment]
Since this touches the build system, it would be good to make a prerelease

**Comment by birkskyum** [comment]
> Since this touches the build system, it would be good to make a prerelease

https://github.com/maplibre/maplibre-gl-js/pull/1968

**Comment by HarelM** [comment]
@rotu I've seen the following when running the jest tests:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
Can you take a look at it? I think it might be related to this PR...

**Pull request merged**
