### PR TITLE
fix fitBounds crossing AM with 3d - add wrap for lng in transform getElevation 

### PR DESCRIPTION
**Pull request by llambanna**
wrap `lnglat` point so `fitBounds` across anti-meridian no longer throws error

## Launch Checklist

 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues. https://github.com/maplibre/maplibre-gl-js/issues/2095
 - [x] Write tests for all new functionality.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for taking the time to fix this!
Can you add a small unit tests around this bug?

**Comment by llambanna** [comment]
@HarelM i tried but i have a mac M1 and i can't get the tests to run, i get this error:
>  dlopen(/Users/admin/code/maplibre-gl-js/node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace '_cairo_fill'

despite following the arm64 approach here: https://github.com/koordinates/maplibre-gl-js/blob/main/CONTRIBUTING.md#osx

**Comment by HarelM** [comment]
You can use the CI to run the tests in theory, which is less than optimal I guess.
But since this is a bug fix, it has to have a test to make sure this bug won't "return".

**Comment by llambanna** [comment]
@HarelM yep, that would be a painful way to write a test, but it would work, eventually
i'll see what i can do

**Comment by HarelM** [comment]
Thanks! Also if there's a way to make it work on M1 as well it would be super, but you'll need to investigate and test it as I don't have one unfortunately (and I'm also not very keen on buying one due to all this incompatibility mess).

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Forgot to ask, can you please add an entry to the changelog file?

**Comment by llambanna** [comment]
@HarelM yep, i'll add something to changelog

if i get it working on an M1 i'll update the docs with what i did

**Comment by HarelM** [comment]
Thanks!! It might not be just the docs, but you already know that 😀

**Comment by llambanna** [comment]
> Thanks!! It might not be just the docs, but you already know that 😀

@HarelM turns out it was just the docs 😌 

have a PR for steps: https://github.com/maplibre/maplibre-gl-js/pull/2196

**Pull request merged**
