### PR TITLE
Release 2.0.5

### PR DESCRIPTION
**Pull request by birkskyum**
Updated changelog, package.json and package-lock.

### CODE REVIEW

**Comment by HarelM** [comment]
Is it worth releasing this version? Doesn't seem like it adds something...?

**Comment by birkskyum** [comment]
Apparently, the current situation gives this warning:

`error maplibre-gl@2.0.4: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.2"`

**Comment by HarelM** [comment]
ahh, I see.
In that case release it :-)

**Comment by HarelM** [comment]
Can you release or you need me to release?

**Comment by birkskyum** [comment]
I believe I have access to triggering the Release action. Is that all it takes?

**Comment by HarelM** [comment]
Yup.

**Pull request merged**
