### PR TITLE
Correct mouse/touch position for maps scaled with CSS transform

### PR DESCRIPTION
**Pull request by kurt-stolle**
When you scale the GL container using a CSS transform, i.e. `transform: scale(N)`, interacting with the map becomes difficult because the `DOM.touchPos` and `DOM.mousePos` functions do not correct for this scaling factor `N`. 

This issue has been raised before (Nov. 2019) in the Mapbox GL repository, but the PRs [[1](https://github.com/mapbox/mapbox-gl-js/pull/9014), [2](https://github.com/mapbox/mapbox-gl-js/pull/9057)] were never accepted due to the development team at the time waiting for a more robust solution to be made. Sadly, this solution never came to be. For this reason, this piece of code has been something that I had to manually paste into my own version of GL every time I required the functionality. I would like to re-evaluate whether this could be added to the Maplibre GL project at this time for practical reasons.

Full disclosure: this code is based on a _rejected_ PR in the Mapbox GL repository [[2](https://github.com/mapbox/mapbox-gl-js/pull/9057)] of which I am not the author. This PR was submitted on Dec 3, 2019 for version 1.x.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for opening a PR!
Is there a way for you to write a small unit-test to make sure this behavior is preserved?
Also reading the code it seems that you are talking about scaling when the code is using offset.
Can you explain the reasoning for that?

**Comment by HarelM** [comment]
I would like to merge this if possible but for that I need a few more things:
1. Open an issue describing the problem
2. Add a unit test to make sure this is working as expected
3. Resolve conflicts (probably related to the fact that we migrated to typescript)
4. Add a changelog entry

Thanks!!

**Comment by kurt-stolle** [comment]
Hello @HarelM, I've been away for a while hence why there has been no progress. I will update the PR and make an issue in the next two weeks.

**Comment by HarelM** [comment]
Cool, thanks!

**Pull request closed without merging**
