### PR TITLE
Rename css

### LINKED ISSUE #83: Rename CSS classes from `mapboxgl-*` to `maplibre-*`
Question to @maplibre/core -- should all CSS classes be renamed to `maplibregl-*`, or do we want to keep the original `mapboxgl-*` to be compatible with other code?  Would this be a stylistic or a legal requirement?  My understanding is that this would be part of the API, and thus could stay as is.  Also I suspect this change would be a relatively painful for the endusers.

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Resolved #83 

 - [x] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by wipfli** [comment]
Are the tests failing for good or do we have problems again?

**Comment by HarelM** [comment]
I think they are blinking unfortunately... 
But some did fail due to bugs I introduced.
In any case, I think I managed to fix everything...
I couldn't find a way to rerun tests without pushing another commit...?

**Comment by wipfli** [comment]
Go to https://github.com/maplibre/maplibre-gl-js/pull/185/checks then click here:

image

**Comment by HarelM** [comment]
I probably don't have this right permissions as I didn't see this button when I tried to find out how to rerun...

**Comment by HarelM** [comment]
My mistake, I do have this button.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/issues/83

**Comment by wipfli** [comment]
Thanks for working on this Harel. If the updated css means that users have to do some find-and-replace, can you maybe add a note about this in the README?

**Comment by HarelM** [comment]
Sure, no problem.
Should this be version 2.0 then due to this breaking change or 1.15 is enough?

**Comment by wipfli** [comment]
That's a good question. You know when we went from the release candidates of version 1.13 to the actual release v1.14 we also broke stuff by using maplibre rather than mapbox.

**Comment by HarelM** [comment]
Yea, I know, that's why I suggested 1.15.
I'm good with 1.15.

**Comment by HarelM** [comment]
@wipfli can you please review so this will be ready for merge? Currently merge is blocked due to required code review.

**Review by wipfli — APPROVED** [review]
Thanks Harel

**Comment by bendman** [comment]
Will the policy of this repo be to use minor version bumps in the future to denote breaking changes, or will it eventually change to use semver major bumps?

**Comment by HarelM** [comment]
I think the place for such a question is the discussions area as this was merged and released. I honestly not sure what you are asking or what are you suggesting... :-)

**Pull request merged**
