### PR TITLE
Demo test

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

Test pull request demo introduced in #1169.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by wipfli** [comment]
Whoops https://github.com/maplibre/maplibre-gl-js/runs/5886140502?check_suite_focus=true failed

**Comment by wipfli** [comment]
image

means it has not enough privileges. Reading https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

**Comment by wipfli** [comment]
Example to adjust the permissions per workflow: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input

**Comment by wipfli** [comment]
Stuff we can elevate is:

```
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```

**Comment by wipfli** [comment]
And these are the settings that the pull request with the branch in the repo had #1171 :+1: 
``` 
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

**Comment by wipfli** [comment]
Still read only... If I can't fix it, I will revert the pr demo workflow.

**Comment by HarelM** [comment]
@wipfli can this PR be closed?

**Pull request closed without merging**
