### PR TITLE
Evaluate symbol-spacing at collision time

### PR DESCRIPTION
**Pull request by drwestco**
Draft PR for discussion

This is some experimental code to address #1127. Instead of laying out line labels with optimal spacing in the worker tile, a denser set of anchors is created, providing alternate positions for the labels to use when collisions occur. The images linked to that issue were generated using the code and debug page in this PR, and illustrate the new approach.

Open questions:
1) Does this new approach to symbol-spacing become "the" way, or do we need to keep a switch in place to allow maplibre consumers the ability to switch between current and new behavior?
1) What are the negatives of this new approach in terms of user experience? The render tests show some differences in placement (as you'd expect), but it's difficult to say whether any of those changes are "bad" and not just "different".
1) What's the optimum number of extra anchors to create? The code in get_anchors.ts marked HACK has some hard-coded spacing based on label size. This obviously needs to be refined and/or turned into a new style property.
1) The old `anchorIsTooClose` uses the label text as the key to space out duplicates. The raw text isn't available to the placement code (it's been converted to glyphs by that point), so a combination of `bucketInstanceId` and `featureIndex` are used. This is fine for a single feature, but neighboring features with the same name (e.g. multi-lane highway, with each lane as its own feature) may have labels spaced too closely. `symbolInstance.key` is the hash of the text, so that may be used here. Drawback of this for multi-lane scenarios is that all labels will wind up on the first lane encountered during the placement pass - all labels in the neighboring lane would be rejected as being too close. Ideal behavior for these labels (highway shields) would be to alternate placement between lanes.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for sharing. To fix some of the linting errors, you can run `npm run lint -- --fix`.

**Comment by drwestco** [comment]
Used anchors are unstable at higher zoom levels (LOD 17+), as the line geometry becomes significantly larger than the viewport. Placed labels shift around as the map pans, as the upper-leftmost anchor in view changes. I thought the control is supposed to re-use placed anchors from one frame to the next, so don't yet understand why they're shifting like they do.

**Comment by wipfli** [comment]
Just out of curiosity, can you run the benchmarks on this pull request and share the results here?

**Comment by wipfli** [comment]
image

`Placement` seems about 20 percent slower if I set `const collisionSymbolSpacing = true;`. I guess that is not too bad...

**Comment by drwestco** [comment]
Yeah, I expect the perf to suffer a bit as coded. The full pass + sort by key I just added in the placement step needs a better solution.

**Comment by wipfli** [comment]
Uff, hello stalebot... @drwestco what is your plan?

**Comment by HarelM** [comment]
@drwestco where are we with this PR? Can this exist draft state or should it be closed?

**Pull request closed without merging**
