### PR TITLE
Fix bug with performance.now in NextJS

### PR DESCRIPTION
**Pull request by crubier**
## Launch Checklist

Fix https://github.com/maplibre/maplibre-gl-js/issues/768

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [x] Suggest a changelog category: bug
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog>Fix bug with performance.now in NextJS</changelog>`.

### CODE REVIEW

**Comment by wipfli** [comment]
Please lint with `npm run lint -- --fix`

**Comment by HarelM** [comment]
Why checking if window is defined? Why not checking if performance is defined?
I don't see a reason to add windiw there as this may run in a worker.

**Review by HarelM — CHANGES_REQUESTED** [review]
See my comment above

**Comment by HarelM** [comment]
Closed in favor of #986

**Pull request closed without merging**
