### PR TITLE
Bump version to 2.2.0-pre.3

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

@wipfli @birkskyum @xabbu42 @astridx please approve so I can publish a new version to npm

Thanks!

### CODE REVIEW

**Review by birkskyum — APPROVED** [review]
Great :)

**Comment by wipfli** [comment]
Hm I still don't know why in the changlelog text does not get attached to prerelease info...

**Comment by HarelM** [comment]
Probably because it's a prerelease...?

**Comment by wipfli** [comment]
I am so bad with regex... Do you thinks this stuff is actually correct?

https://github.com/maplibre/maplibre-gl-js/blob/8373c9d972efd4376d6bc229fbe4df6840f456d8/build/release-notes.js#L19-L29

**Comment by HarelM** [comment]
Everyone is :-) I use regexp online tester to see what are the results.

**Pull request merged**
