### PR TITLE
Remove tap after jest migration

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

Confilct resolution and continuation of #829.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by wipfli** [comment]
Are the browser tests actually run by jest? `jest.config.cjs` does not seem to include them.

**Comment by wipfli** [comment]
@birkskyum can you help me fixing the build tests?

**Comment by birkskyum** [comment]
is we add the test folder as a root in jest config, maybe add back the different tests with something  like this

test-unit: jest -- src/
test-builds: jest -- test/build
test-browser -- test/browser

**Comment by birkskyum** [comment]
browser and build tests are indeed using jest

**Comment by birkskyum** [comment]
Tests script in package.json and CI/CD was updated here (#866), to get the tests activated again.

**Pull request closed without merging**
