### PR TITLE
[Jest] Migrate `ajax.test.js`

### PR DESCRIPTION
**Pull request by wipfli**
- Move and rename
- Run jscodeshift
- Run custom codemods and lint
- Manual edits

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by astridx** [comment]
Please see https://github.com/wipfli/maplibre-gl-js/pull/22

**Comment by birkskyum** [comment]
This seems to work great :)

**Comment by wipfli** [comment]
@HarelM @birkskyum this is ready for review. Thanks @astridx for your help.

**Comment by HarelM** [comment]
I don't think we should export and mock arrayBuffer method just to make the tests pass.
We should be able to mock imghtmlelement I think.

**Comment by HarelM** [comment]
If you want me to try and mock the img part of the code let me know.
I have done it in stub_loader for the tap tests, so I'm pretty sure it's possible...

**Comment by astridx** [comment]
@HarelM I would be interested to know how that works. So I want you to do that.

**Comment by HarelM** [comment]
Sorry for not submitting a PR to this PR, but here's is the failing test fixed:
```js
    test('getImage uses HTMLImageElement when ImageBitmap is not supported', (done) => {
        resetImageRequestQueue();

        server.respondWith(request => request.respond(200, {'Content-Type': 'image/png'}, ''));

        // mock createImageBitmap not supported
        global.createImageBitmap = undefined;
        global.URL.revokeObjectURL = () => {};
        Object.defineProperty(global.Image.prototype, 'src', {
            set(src) {
                this.onload();
            }
        });

        getImage({url: ''}, (err, img) => {
            if (err) done('get image failed with error ' + err.message);
            expect(img).toBeInstanceOf(HTMLImageElement);
            done();
        });

        server.respond();
    });
```

**Review by HarelM — DISMISSED** [review]
See my comment on how to fix the test.

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
