### PR TITLE
userlocationfocus and userlocationlostfocus events added to geolocate_control

### LINKED ISSUE #3846: geolocate_control.ts  Some events are missing
## User Story
I was creating a custom button for geolocation, utilizing the events thrown by the Geolocate class. I noticed that the Geolocate class has six states in _watchState, but it doesn't emit events for each of these states.

The states and their corresponding events are as follows:

WAITING_ACTIVE: trackuserlocationstart
ACTIVE_LOCK: geolocate
OFF: trackuserlocationend
BACKGROUND: trackuserlocationend
BACKGROUND_ERROR: error
ACTIVE_ERROR: error

However, I'm unable to distinguish when the Geolocator turns off or when the user drags the map, among other actions, due to the lack of specific events for each state.

## Rationale
This limitation prevents me from fully customizing the button and handling related events accurately.

## Impact
I can submit a pull request to address this issue if desired.

### PR DESCRIPTION
**Pull request by MeysamRT76**
## Launch Checklist
Resolves #3846
Geolocate Control's OFF and BACKGROUND states both triggering the same trackuserlocationend event, and the WAITING_ACTIVE and ACTIVE_LOCK states both triggering the trackuserlocationstart event, two new events were introduced to separate theme:

1. userlocationfocus
2. userlocationlostfocus

This differentiation allows for a more precise control mechanism, enabling developers to accurately respond to specific geolocator state changes and implement more sophisticated and responsive geolocation functionalities.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Document any changes to public APIs.

### CODE REVIEW

**Comment by HarelM** [comment]
Geolocate control is missing a lot of coverage in terms of tests and state management.
It would be great if you could add the relevant tests to cover all the flows related to state management.
When I tried to cover it with tests I had problems understanding all the state management logic.
Since you are deep into it, it works be great if you could spend some time adding the relevant tests.
Thanks!

**Comment by MeysamRT76** [comment]
I will try to write the related tests.

**Comment by HarelM** [comment]
This is a breaking change in terms of API, isn't it?
I think you could add the new events without removing the old event, document the old event is now deprecated and add a comment in v5 breaking change issue about it so we'll remove it in the future.

**Comment by MeysamRT76** [comment]
Do you want the old events to remain in their previous places and should I add new events beside them?

**Comment by HarelM** [comment]
Yes, I don't think there's another way to keep the old API and new at the same time, isn't it?

**Comment by MeysamRT76** [comment]
I made the code changes. How should I mark old events and functions as deprecated?

**Comment by HarelM** [comment]
The best thing I can think of is this one: 
https://tsdoc.org/pages/tags/deprecated/

**Comment by MeysamRT76** [comment]
Please let me know if there are any changes needed.

**Comment by HarelM** [comment]
I'm not sure the added comments will be visible to users reading the geolocation API documentation here:
https://maplibre.org/maplibre-gl-js/docs/API/classes/GeolocateControl/
You can build the docs locally by running `npm run generate-docs`

Can you try and make sure the deprecation gets to this page somehow?

**Comment by andrewharvey** [comment]
> When I tried to cover it with tests I had problems understanding all the state management logic.

I included a state diagram in my original implementation PR at https://github.com/mapbox/mapbox-gl-js/pull/4479.

I recently had to implement the Geolocate Control button external to the map with it's own design and ended up needing to access the private `_watchState` so :+1: to exposing more detailed events to allow custom buttons etc.

**Comment by HarelM** [comment]
@andrewharvey thanks, this is a great diagram!! I'll need to find a good way to incorporate this in the docs somehow so people can find this better, maybe using an image link to github user content or something, IDK...

In any case, this PR is missing the docs update to be merged.

**Review by HarelM — APPROVED** [review]

**Review by HarelM — CHANGES_REQUESTED** [review]
Looking deeply into this code, I don't understand why the old events are considered deprecated when there's no alternative to the two places that are being fired now.
This PR still needs work and proper design, preferably a diagram with which events are fired when "before" and "after" this change.

**Comment by mrajaei76** [comment]
State Transitions and Events Description Based On Diagram.

OFF -> ACTIVE WAITING
Event: trackUserLocationStart

ACTIVE WAITING -> OFF
ACTIVE ERROR -> OFF
BACKGROUND ERROR -> OFF
ACTIVE LOCK -> OFF
Event: trackUserLocationEnd

Explanation:
The above states and events are correct, indicating the start and end of user location tracking.

Proposed Changes:

BACKGROUND -> ACTIVE LOCK
Current Event: trackUserLocationStart

My Change: userLocationFocus (in addition to the existing event trackUserLocationStart)

ACTIVE LOCK -> BACKGROUND
Current Event: trackUserLocationEnd

My Change: userLocationLostFocus (in addition to the existing event trackUserLocationEnd)

Rationale:
When transitioning between ACTIVE LOCK and BACKGROUND, location tracking is not ending or starting; it is merely losing focus and refocusing on the user location.

Therefore, the old events trackUserLocationEnd and trackUserLocationStart are not deprecated. They are replaced in the two places mentioned above (Proposed Changes).

**Comment by MeysamRT76** [comment]
State Transitions and Events Description Based On Diagram.

OFF -> ACTIVE WAITING
Event: trackUserLocationStart

ACTIVE WAITING -> OFF
ACTIVE ERROR -> OFF
BACKGROUND ERROR -> OFF
ACTIVE LOCK -> OFF
Event: trackUserLocationEnd

Explanation:
The above states and events are correct, indicating the start and end of user location tracking.

Proposed Changes:

BACKGROUND -> ACTIVE LOCK
Current Event: trackUserLocationStart

My Change: userLocationFocus (in addition to the existing event trackUserLocationStart)

ACTIVE LOCK -> BACKGROUND
Current Event: trackUserLocationEnd

My Change: userLocationLostFocus (in addition to the existing event trackUserLocationEnd)

Rationale:
When transitioning between ACTIVE LOCK and BACKGROUND, location tracking is not ending or starting; it is merely losing focus and refocusing on the user location.

Therefore, the old events trackUserLocationEnd and trackUserLocationStart are not deprecated. They are replaced in the two places mentioned above (Proposed Changes).

**Comment by HarelM** [comment]
So the events are not deprecated, but rather there are places where in the future, these event will not be fired.
In that case, I would recommend adding a comment to the following issue:
- #3834 

That will remind us to remove the code that fire the events when they are not needed, when releasing version 5.

Please also fix the docs I changed as there's no real deprecation at this point.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
I've done the relevant change.
I'll merge this soon.

**Comment by MeysamRT76** [comment]
I was struggling with documentation changes due to personal issues, so I didn't have time to work on it. Thank you for completing this PR.

**Comment by andrewharvey** [comment]
> When transitioning between ACTIVE LOCK and BACKGROUND, location tracking is not ending or starting; it is merely losing focus and refocusing on the user location.

Location tracking can mean different things, in this context it was likely talking about the map camera updating as the GPS location updates, not the "blue dot" tracking the live GPS location updates.

**Comment by HarelM** [comment]
I've added the diagram to the docs, hoping future reader will find it useful:
https://maplibre.org/maplibre-gl-js/docs/API/classes/GeolocateControl/#state-diagram

Thanks @andrewharvey!

**Pull request merged**
