### PR TITLE
Migrate `util/task_queue.test.js`

### PR DESCRIPTION
**Pull request by wipfli**

### CODE REVIEW

**Comment by HarelM** [comment]
Do we know if the fact that we have a add and delete for each file is due to whitespace or something?
Most of the files are not that different and it seems weird that git is not seeing them as the same file in most cases...

**Comment by wipfli** [comment]
image

It is not the whitespaces.

**Comment by wipfli** [comment]
Just to be on the same page, the first three commits are done with without using an editor. Then for the remaining manual edits you can look at the individual commits. For example here you could review

https://github.com/maplibre/maplibre-gl-js/compare/d0561e1..fd25d3f

**Comment by HarelM** [comment]
Yes, this is what I'm doing now :-)
@chippieTV, @astridx @wipfli Please make sure not to do any edit in the first three commits that are not manual as I won't review them.
I'll focus on reviewing the manual edit and forth, it's much simpler this way...

**Comment by wipfli** [comment]
Thanks for all the reviews @HarelM!

**Pull request merged**
