### PR TITLE
Bump documentation to 13.0.2

### PR DESCRIPTION
**Pull request by birkskyum**
We can get to v13 with this PR, which is what our documentation repository use - but we can't update to the latest version (13.2.5), because of this: https://github.com/documentationjs/documentation/issues/1471

### CODE REVIEW

**Comment by astridx** [comment]
When I run with `"documentation": "^13.0.2",`

```
$ npm run lint-docs

> maplibre-gl@2.1.0 lint-docs
> documentation lint src/index.ts

Error: Cannot find module './ui/map' from '/maplibre/maplibre-gl-js/src'
    at /maplibre/maplibre-gl-js/node_modules/module-deps-sortable/node_modules/resolve/lib/async.js:55:21
    at load /maplibre/maplibre-gl-js/node_modules/module-deps-sortable/node_modules/resolve/lib/async.js:69:43)
    at onex (/maplibre/maplibre-gl-js/node_modules/module-deps-sortable/node_modules/resolve/lib/async.js:92:31)
    at /maplibre/maplibre-gl-js/node_modules/module-deps-sortable/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (node:fs:198:21)

```

With `"documentation": "^12.3.0"` this is fine.

Is this only wrong on my computer?

**Comment by birkskyum** [comment]
it has to be 13.0.2, and not ^13.0.2, because v13.1.0 breaks it - so not following semver. I made an issue, but let's not merge this now

**Comment by birkskyum** [comment]
@astridx , now the version number is exactly 13.0.2

**Review by astridx — APPROVED** [review]

**Comment by astridx** [comment]
Changed to the use of done

**Pull request merged**
