### PR TITLE
Terrain 3d model example

### PR DESCRIPTION
**Pull request by birkskyum**
Add debug-page (terrain-3d-model.html) with a 3D model on top of 3D terrain. Intended for debugging [#1654](https://github.com/maplibre/maplibre-gl-js/issues/1654)

When moving the map around, the 3D map will change it's elevation, presumably depending on the elevation of the map center.

Screen Shot 2022-09-18 at 16 06 51

### CODE REVIEW

**Comment by HarelM** [comment]
Does this page works as expected or only shows the bug? If it only shows the bug I would recommend fixing the bug before adding this.
Also I'm not confident the problem use with maplibre code and not with the integration code in the relevant issue...

**Comment by birkskyum** [comment]
This is the 3d model example from the website with the terrain-osm style added.

My understanding is that the whole point of the debug pages is to expose bugs to then debug them, and the finished examples to the website. If it ain't helpful as a repro then feel free to close the pr.

**Comment by HarelM** [comment]
I'm not sure, but I see the debug pages as pages you can debug with, but when added to this repo should show a working map with the expected behavior.
It's OK to commit them along side the fix, or to a debug branch to allow collaborating, but from my point of view they should work correctly when in main branch.

**Comment by birkskyum** [comment]
I'm curious, how'd you check if it worked in the latest commit, if not through a debug page? make a prerelease and use it in stackblitz?

**Comment by HarelM** [comment]
Though a debug page is the right way, but I wouldn't commit it to main without a fix, either in the page itself or in the library code. that's all :-)
Example pages are more complicated to build, with images and other "limitations", debug pages are less "strict", but should still showcase a working example.

**Comment by wipfli** [comment]
Is there a way to automate branch removal?

**Comment by wipfli** [comment]
Or is this one not deleted on purpose, @birkskyum?

**Comment by birkskyum** [comment]
The branch still serves the purpose of being a repro of #1654

**Pull request closed without merging**
