### PR TITLE
Add windows latest to test-build workflow

### PR DESCRIPTION
**Pull request by zhangyiatmicrosoft**
## Launch Checklist

Config build-test to also run on windows-latest 

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by zhangyiatmicrosoft** [comment]
Very surprised that "build" step did not even execute for this PR. Did I miss something?

**Comment by HarelM** [comment]
Build is failing :-/ but at least we know ci is working now :-)

**Comment by zhangyiatmicrosoft** [comment]
Finally passed. Maybe just me, yml seems way too restrictive in that it does not like extra indentations, and "name" must exists while using if" condition. The worst part is that GH does not tell you exactly what went wrong except line X.

**Comment by HarelM** [comment]
Would be much more valuable to fix those step to work on Windows, wouldn't it?

**Comment by wipfli** [comment]
@zhangyiatmicrosoft try once the online web editor of GitHub for workflows. For that:

1. go to a workflow file on github, e.g. https://github.com/maplibre/maplibre-gl-js/blob/main/.github/workflows/test-query.yml

2. press edit
image

3. get the syntax highlighting
image


Probably there is also a VS Code extension which tells you formatting errors in your workflow files...

**Comment by zhangyiatmicrosoft** [comment]
> Would be much more valuable to fix those step to work on Windows, wouldn't it?



> Would be much more valuable to fix those step to work on Windows, wouldn't it?

Fixed with powershell

**Review by HarelM — APPROVED** [review]

**Pull request merged**
