### PR TITLE
Update CI from node v10 to v14 and replace yarn with npm

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

This pull request cherry-picks the single commit of @HarelM in the `node-14` branch with brings CI from node version 10 to version 14. If merged, please delete branch `node-14`.

 - [🐳 ] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [ ] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/commit/8b9dd747432f2bbdfcca669d6f1a99d6b5a14e05

**Review by HarelM — APPROVED** [review]
Can we delete circle ci file?

**Comment by HarelM** [comment]
Cool, thanks!

**Comment by wipfli** [comment]
Since we already got rid of `yarn.lock` I switched most CI commands from `yarn` to `npm`. Todo are:

* in `analyze.yml`:  `yarn source-map-explorer before/maplibre-gl.js --gzip --json before.json`
* in `release.yml`:  `yarn version --non-interactive --no-git-tag ...`

**Pull request merged**
