### PR TITLE
Change 'kb' to 'kB' for kilobytes

### PR DESCRIPTION
**Pull request by jleedev**
#833

skip changelog

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for taking the time to send this PR!

**Comment by jleedev** [comment]
Render diff is larger than I might expect so I'll refrain from attempting to update it.

image

**Comment by HarelM** [comment]
I guess you can change the ci to upload the results.html file in case of failure and change the images according to the ci results...?

**Comment by jleedev** [comment]
Never mind, I was just confused. It looked as though the entire green background had changed, but I'm chalking that up to macOS.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
