### PR TITLE
Don't reload raster sources when RTL text plugin loads to avoid flicker.

### LINKED ISSUE #2380: Deferred loading of RTL text plugin causes flicker for raster layers
When a deferred load of the RTL text plugin completes, there's logic that causes the source caches to reload:

https://github.com/maplibre/maplibre-gl-js/blob/9f713cd2299a567e4f2a8000d984cd3f4ca14a19/src/style/style.ts#L226-L238

The purpose of this logic is to cause them to regenerate their symbol buckets with the new RTL shaping applied. If the plugin loads before the initial tile load, this will be a no-op, but if some tiles have already loaded it will reparse them. This is some extra work and the tile cache is cleared out, but the old tiles can still display until the new tiles are ready.

This logic is unnecessary for raster sources, since they don't have any symbols to regenerate. Also, raster tiles tend to load faster (because no parsing/bucket-generation is necessary), and are thus more likely to load before the RTL plugin loads. This generates extra work, but might not be that noticeable except for the fact that reloading a raster tile also resets the tile fade animation to the beginning.

The upshot of all this is an unsightly flicker during map load (in this example I'm just loading a single satellite layer and setting the rtl text plugin).

load_flicker

Stepping through in the debugger, you can see loaded tiles getting dropped one at a time as reloaded images arrive:

reloading_raster_tiles

And this is what the load looks like with the `reload()` call turned off for raster sources (PR coming soon):

load_no_flicker

### PR DESCRIPTION
**Pull request by ChrisLoer**
Fixes #2380

## Summary (from Issue)
When a deferred load of the RTL text plugin completes, there's logic that causes the source caches to reload:

https://github.com/maplibre/maplibre-gl-js/blob/9f713cd2299a567e4f2a8000d984cd3f4ca14a19/src/style/style.ts#L226-L238

The purpose of this logic is to cause them to regenerate their symbol buckets with the new RTL shaping applied. If the plugin loads before the initial tile load, this will be a no-op, but if some tiles have already loaded it will reparse them. This is some extra work and the tile cache is cleared out, but the old tiles can still display until the new tiles are ready.

This logic is unnecessary for raster sources, since they don't have any symbols to regenerate. Also, raster tiles tend to load faster (because no parsing/bucket-generation is necessary), and are thus more likely to load before the RTL plugin loads. This generates extra work, but might not be that noticeable except for the fact that reloading a raster tile also resets the tile fade animation to the beginning.

The upshot of all this is an unsightly flicker during map load (in this example I'm just loading a single satellite layer and setting the rtl text plugin).

load_flicker

Stepping through in the debugger, you can see loaded tiles getting dropped one at a time as reloaded images arrive:

reloading_raster_tiles

And this is what the load looks like with the `reload()` call turned off for raster sources (PR coming soon):

load_no_flicker

## Changes in this PR
This PR simply limits the sources that can reload to `vector` and `geojson`, the two types that contain symbol buckets. The bulk of the work was just setting up the mocking in the Style unit test to verify the new behavior.

cc @ibesora @HarelM 

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by ChrisLoer** [comment]
Oops, looks like the tests don't work on latest `maplibre:main` -- I was working off an older version. I'll try to get them updated either later tonight or tomorrow.

**Comment by HarelM** [comment]
Yea, that's not ideal, I agree. I had the same issue recently, I ended up introducing a default parameter to force clear cache... Wasn't too happy with that solution either...

**Comment by HarelM** [comment]
Can you better describe the issue with testing? because I see there's a `clearRTLTextPlugin` method that is used in the tests to clear, and when you create a new style you can spy on `jest.spyOn(Style, 'registerForPluginStateChange');` can't you?

**Comment by ChrisLoer** [comment]
> Can you better describe the issue with testing? 

At a high level -- it's callback hell. But going to describe the issues in more detail led me to some more satisfying fixes. The comment description explains it was basically two issues:

> - Make clearRTLTextPlugin also clear the _completionCallback
>   - Having a completion callback for an old plugin run is bad in general
>   - It specifically messed up the style tests by running during later tests
> - Call clearRTLTextPlugin when last plugin test is done
> - Set the stubMap style object -- this is a subtle one, but two frames _after_ this test runs, loadTileJSON triggered by this loadJSON will fail if the map doesn't have its style set, and the exception will get passed to a later style test.

I think the style unit tests will remain vulnerable to this kind of breakage though -- it's not just the global plugin logic but also the way the style defers work through `requestAnimationFrame` and can easily leave those requests pending even when any given test thinks it's already done. (in this case, we were marking ourselves `done()` in response to `style.load`, but loading the style had triggered source loading logic that would later fail)

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Thanks! Can you add a changelog entry for this bug/PR?

**Review by HarelM — APPROVED** [review]

**Pull request merged**
