### PR TITLE
Sort icon and text draw order

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

This is the same code from #145 - Sort icon and text draw order, I think it should fix #45.
I would expect the test under 
`npm run test-render -- tests/icon-opacity/text-and-icon`
to fail, but it seems that this commit although relevant to this test is not failing for some reason...
Other tests fail though...

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
This is strange, I expected some render test to fail and maybe other tests... Super odd...

**Comment by HarelM** [comment]
I tried to create a much more simple case with only two point as can be seen in the following style:
```json
{
    "version": 8,
    "metadata": {
      "test": {
        "height": 64,
        "width": 64
      }
    },
    "sources": {
      "geojson": {
        "type": "geojson",
        "data": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Point",
                "coordinates": [
                  0,
                  -5
                ]
              }
            },
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Point",
                "coordinates": [
                  0,
                  5
                ]
              }
            }
          ]
        }
      }
    },
    "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
    "sprite": "local://sprites/sprite",
    "layers": [
      {
        "id": "text",
        "type": "symbol",
        "source": "geojson",
        "layout": {
          "text-font": [
            "Open Sans Semibold",
            "Arial Unicode MS Bold"
          ],
          "text-allow-overlap": true,
          "text-ignore-placement": true,
          "icon-allow-overlap": true,
          "icon-ignore-placement": true,
          "text-field": "A",
          "icon-image": "bank-12",
          "icon-size": 2
        },
        "paint": {
            "text-color": "white"
        }
      }
    ]
  }
```
Which creates the following image "incorrect" image:
image
I've debugged the code a bit and it seems that there's only one segment and the `program.draw` is called only once.
I tend to say that either there's a bug in the code or the change should also be in the shaders...?

@JannikGM any change you can help out here a bit?
@xabbu42 did you test the code to make sure it behaves as expected? is this the results of the refactoring that was made to the code after it worked maybe?
I'm a bit lost here... any help would be appreciated...

**Comment by xabbu42** [comment]
@HarelM I was a bit occupied with other stuff at work, hopefully I can look into it next week. Your test case reproduces exactly the bug i was trying to solve. But as far as I remember it always takes a fast path if you don't give any order. As I did not want to introduce performance regression I left it like that. So perhaps you need to also give a sort-order so my fix kicks in?

**Comment by HarelM** [comment]
The following style seems to generate the right image:
```json
{
    "version": 8,
    "metadata": {
      "test": {
        "height": 64,
        "width": 64
      }
    },
    "sources": {
      "geojson": {
        "type": "geojson",
        "data": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "properties": { "index": 2},
              "geometry": {
                "type": "Point",
                "coordinates": [
                  0,
                  -5
                ]
              }
            },
            {
              "type": "Feature",
              "properties": { "index": 1},
              "geometry": {
                "type": "Point",
                "coordinates": [
                  0,
                  5
                ]
              }
            }
          ]
        }
      }
    },
    "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
    "sprite": "local://sprites/sprite",
    "layers": [
      {
        "id": "text",
        "type": "symbol",
        "source": "geojson",
        "layout": {
          "text-font": [
            "Open Sans Semibold",
            "Arial Unicode MS Bold"
          ],
          "symbol-sort-key": ["to-number", ["get", "index"]],
          "text-allow-overlap": true,
          "text-ignore-placement": true,
          "icon-allow-overlap": true,
          "icon-ignore-placement": true,
          "text-field": "A",
          "icon-image": "bank-12",
          "icon-size": 2
        },
        "paint": {
            "text-color": "white"
        }
      }
    ]
  }
  ```
This is the image:
image
While I think it's better and obviously solves a problem, I'm not sure it's very practical to define sort key to every feature (unless there's an automated way to generate the index), I would expect this to work out of the box, but that may require more work.
In any case, I'll add this test to this PR if someone else would like to hack this.

**Comment by xabbu42** [comment]
I think we should a) measure the performance diff of the fast path without order just to know how big the impact even is and b) probably disable the fast path for any symbol layer which combines text and icons *and* allows overlaps. the only downside I see is that there could be dynamic symbol layers which use text and icons but never combine them which would be slower without, but this seems like a very obscure use-case to me.

**Comment by HarelM** [comment]
I would love to help out, but I'm not sure how to do what you wrote.
In any case, this PR is open, this branch is part of this repo and you can easily push code straight to it or make a PR to this branch, what ever suites you :-)
I'm here to help if needed.
Note that #716 will probably conflict with these changes, so first come first served :-)

**Comment by xabbu42** [comment]
My original pull request for mapbox got closed given possible slow-downs for existing styles as a reason, so I think we should be careful here and measure the speed impact on existing styles.

**Comment by JannikGM** [comment]
I'm not familiar enough with this code to know how it groups draw calls, so take the following with a grain of salt.
But to me, this looks like a potential performance nightmare, too.

You should definitely check the amount of state-changes / draw-calls (with something like https://github.com/BabylonJS/Spector.js/). 

The only way I could imagine this could perform properly is, if you had all fonts and all sprites in the same atlas or at least in different texture inputs to some uber-shader (so you can draw all text and icons in the same draw-call).

I guess the `symbolTextAndIcon`-shader already tries to solve some of this: https://github.com/maplibre/maplibre-gl-js/blob/6e9becf599c07b16dfa559e5c089420145c8b01d/src/shaders/symbol_text_and_icon.fragment.glsl#L30

Currently there are a lot of blockers for this and I don't think it's easy to implement this.
For example, halos are also drawn in a separate draw-call (using the same shader, but a different uniform to distinguish it from icon and text). There is also an interesting issue about halo rendering at: https://github.com/mapbox/mapbox-gl-js/issues/596 (so halos should render before all of the text-inline, but after icons).
So if you had text with halo and icons, you'd totally break performance, as you'd have to render icons (~draw-call 1), then the halo (separate draw call because different uniform value! ~draw-call 2), and then continue with the actual text (~draw-call 3).. and you have to *do this for each symbol*.
So at N symbols, you end up 3 x N draw-calls.
Without this ordering, you'd only need 1 draw-call for all symbols, then 1 draw call for all halos, and then 1 draw call for all texts = 3 draw-calls, regardless of the number of symbols.

You'd also still require all glyphs from the font-textures as shader input.
Currently, text is broken into glyph ranges so the problem is solved by divide-and-conquer at a small performance impact in scenes with many different glyphs (and resulting ordering issues).
With your ordering you might have to split draw calls for glyph-texture changes, which would also perform poorly as you'd have to stop on each letter which isn't part of your atlas (going back to something similar to 3 x N performance, but potentially worse).

One potential solution could be to *also* differentiate halos using `v_data1.w`. That way you could move them into the same draw-call; regardless of the ordering, this could be a good performance optimization and it should be more or less "free" (but I might be missing something).
For the glyphs, the situation is trickier: You'd have to generate a custom atlas which will be potentially huge (potentially larger than the WebGL implementation supports) or you'll require a high amount of input textures (potentially more than the WebGL implementation supports).

**Comment by klokan** [comment]
I guess we could close this - as proposed on the steering comity meeting today.
If the performance issues and addressed problems are addressed.

**Comment by HarelM** [comment]
Closing this for now, we can alway revisit this in the future.

**Comment by HarelM** [comment]
If we can make sure we won't degrade performance when solving this issue in general (i.e. we improve the performance and then degrade it just a bit so in overall we are in a better spot) I think this is a good way forward.

**Comment by xabbu42** [comment]
> Because each bucket is per tile, the sorting is only good within a tile.
> So when drawing symbols by their global cross-tile sort-key, the renderer has to jump back and forth between tiles (but not layers!) while drawing.

I tried to reduce the window size and choose a position to have a map entirely consisting of only one tile in my examples. Even though the screen captures from Spector.js no longer show any tiling I still see the increase in draw calls with sorting enabled on 2.4.0. So it seems to me that even without any tiling effects the implementation of symbol-sort-key is inefficient? I'm asking because my idea in #2478 only changes how a single tile is handled and if the problem is with multiple tiles it would actually not make a difference.

It is my understanding that this code https://github.com/maplibre/maplibre-gl-js/blob/main/src/render/draw_symbol.ts#L382 results in a separate draw call per sort-key value and that this is the problem. Is that correct?

**Comment by xabbu42** [comment]
> This can be very expensive, depending on the architecture / driver. This will potentially require the CPU to wait (in the driver) until the GPU has finished drawing with the current program before submitting the next command chain.
>
> It's probably not that bad in practice, given that a bunch of existing maplibre / mapbox code is already doing some very bad things, like the sort-key cross-tile sorting by re-ordering draw-calls (which is a common theme with maplibre performance: lots of CPU involvement and inefficient GPU usage).

So would the additional useProgram calls be a blocker for this fix if I would port it on current maplibre-gl-js?

**Pull request closed without merging**
