### PR TITLE
fix for "is an ES module file" in node 12+ when using style-spec npm package

### PR DESCRIPTION
**Pull request by acalcutt**
When trying to use https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec with Node 12(+), an error like the following is shown

```
require() of /app/node_modules/@maplibre/maplibre-gl-style-spec/dist/index.js from /app/src/serve_style.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/@maplibre/maplibre-gl-style-spec/package.json.
```

Talking to @HarelM on slack I had found out this error had also occurred in maplibre-gl-js and it was fixed by adding a package.json file with the line "{ type: "commonjs" }" to the dist folder where the js files were located. I tested at https://www.npmjs.com/package/@acalcutt/maplibre-gl-style-spec and confirmed, putting the package.json with that line into src\style-spec\dist did  and it did fix the error above. The previous conversation on this fix was here ( https://github.com/maplibre/maplibre-gl-js/issues/370#issuecomment-972923342 )

I have tested the updated npm package I created ( https://www.npmjs.com/package/@acalcutt/maplibre-gl-style-spec ) in this upgraded Tileserver-GL ( https://github.com/acalcutt/tileserver-gl ) and it seems to work. before the fix I could not build the app in Node 12 or above, but now I have built it up to node 16 with no problem.

As an alternative to this, I also tested just removing `"type": "module"` from src\style-spec\package.json which also seemed to work. However with @HarelM and the previous comments in the thread above, it didn't sound like this was the way we would want to go.

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
I think this is not the solution to the problem.
If you install the latest version you'll see that in package.json `module` is pointing to index.es.js which doesn't exists.
I think the following PR fixes that: #1128
But I think there wasn't a package published since this fix.
@wipfli can you publish a new version of style-spec package and see if the issue described here is fixed?

**Comment by HarelM** [comment]
@acalcutt can you check if you apply the fix that is referenced in the PR works if you do it locally inside the node_modules?

**Comment by acalcutt** [comment]
It looks like someone has already done that. I removed the package.json in my local project and went to change that line to mjs, but it was already done ( https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/package.json#L16 )

Without the package.json it breaks again
```
/opt/tileserver-gl/src/serve_style.js:1
Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/tileserver-gl/node_modules/@acalcutt/maplibre-gl-style-spec/dist/index.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /opt/tileserver-gl/node_modules/@acalcutt/maplibre-gl-style-spec/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/opt/tileserver-gl/src/serve_style.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/opt/tileserver-gl/src/server.js:21:21)
    at Generator.next (<anonymous>)
    at startServer (/opt/tileserver-gl/src/main.js:80:10)
    at /opt/tileserver-gl/src/main.js:211:12
    at FSReqCallback.oncomplete (node:fs:199:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

The only thing I was thinking was maybe the package.json could be generated as part of the style spec build steps (when index.js gets built)

**Comment by acalcutt** [comment]
And the package I am using at https://www.npmjs.com/package/@acalcutt/maplibre-gl-style-spec was build a few days ago from 2.1.9 source, so it has this fix in it already.

**Comment by HarelM** [comment]
I'm not sure this is the same.
Can you try the following:
`npm i @maplibre/maplibre-gl-style-spec` to install the version from npm.
edit `node_modules/@maplibre/maplibre-gl-style-spec/package.json` and change the line `"module": "./dist/index.es.js",` to `"module": "./dist/index.mjs",`

BTW, how do you get this error? what code are you using? something with `require` instead of using `import`?
We moved away from `require` throughout this package in order to avoid these kind of errors and also migrated from node 12 to node 16.
If you are maintaining tileserver-gl I suggest to do the same in order to upgrade to latest stable version of node.

**Comment by acalcutt** [comment]
It is using an import, not a require
https://github.com/acalcutt/tileserver-gl/blob/main/src/serve_style.js#L8

I gen this error by manually running tileserver-gl like this (which usually works)
/root/.nvm/versions/node/v16.14.2/bin/node /opt/tileserver-gl/ -p 8080

**Comment by acalcutt** [comment]
I tried it moving it back to the @maplibre package , making the change to package.json manually and same error

```
# /root/.nvm/versions/node/v16.14.2/bin/node /opt/tileserver-gl/ -p 8080
Starting @acalcutt/tileserver-gl v3.1.8
No MBTiles specified, using zurich_switzerland.mbtiles
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
undefined:0


/opt/tileserver-gl/src/serve_style.js:1
Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/tileserver-gl/node_modules/@maplibre/maplibre-gl-style-spec/dist/index.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /opt/tileserver-gl/node_modules/@maplibre/maplibre-gl-style-spec/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/opt/tileserver-gl/src/serve_style.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/opt/tileserver-gl/src/server.js:21:21)
    at Generator.next (<anonymous>)
    at startServer (/opt/tileserver-gl/src/main.js:80:10)
    at /opt/tileserver-gl/src/main.js:173:14
    at /opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:300:28
    at ensureCenter (/opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:367:38)
    at /opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:297:17
    at ensureBounds (/opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:338:38)
    at /opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:295:13
    at ensureZooms (/opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:306:60)
    at Statement.<anonymous> (/opt/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:293:9) {
  code: 'ERR_REQUIRE_ESM'
}
```

If I just add that package.json with "type": "commonjs", it loads as expected

```
# /root/.nvm/versions/node/v16.14.2/bin/node /opt/tileserver-gl/ -p 8080
Starting @acalcutt/tileserver-gl v3.1.8
No MBTiles specified, using zurich_switzerland.mbtiles
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8080/
Startup complete
```

**Comment by HarelM** [comment]
I'm trying to run this on windows and it fails miserably...
The docs around how to run the code are super lacking unfortunately so I'm not sure I can help here.
I also couldn
If you are upgrading the package I suggest to remove all `require` usage, migrate to `import` everywhere and use `type: "module"` in your package.json file.
This can be read here:
https://javascript.plainenglish.io/how-to-use-import-instead-of-require-statements-in-a-node-app-short-f3eff5d3a90d

Another options is to change the extension of `index.js` to `index.cjs` as proposed by the error and release a breaking change version of the style-spec.
Since you have a version of your own, I would try that first.
Adding a package.json to the dist folder is a hack I would like to avoid, sorry for nagging...

**Comment by acalcutt** [comment]
I don't think the tileserver-gl will run directly on windows right now, at least without being run through docker.

The maplibre-gl-native build process I am using only makes bins for linux and macos, so on windows it tries to build from source and like you said, fails miserably.

I am running debian 11 here, with all the tools the pre-reqs docker has ( https://github.com/acalcutt/tileserver-gl/blob/main/Dockerfile#L30-L47 ), so I am able to run this directly without docker.

**Comment by acalcutt** [comment]
I tested changing the file to cjs, updating the package.json to reflect that name, and removing the "hack" package.json and that does seem to work.

This index.js is a generated file by  "npm run build-style-spec" right? So would be change this to make a cjs named file?

**Comment by HarelM** [comment]
I'm using wsl2 now and I was able to build the image but I'm unable to run it.
I'm not sure what I'm doing wrong, so I can't help actually debugging this.
I did 
`sudo docker build . -t tileserver-gl`
`sudo docker run --rm -it -v $(pwd):/data -p 8080:80 tileserver-gl`
and I'm getting the error:
`standard_init_linux.go:228: exec user process caused: no such file or directory`
Which I think has to do with a missing entry point file to run in the image if I have to guess.

In any case, this is not related to this issue.
@birkskyum what do you think about changing the `index.js` to `index.cjs`?

**Comment by acalcutt** [comment]
your using my package at https://github.com/acalcutt/tileserver-gl/ ?

docker build --no-cache -t wifidb/tileserver-gl:latest .
run --rm -it -v $(pwd):/data -p 8080:80 wifidb/tileserver-gl:latest

**Comment by HarelM** [comment]
Yes...

**Comment by acalcutt** [comment]
in the tileserver-gl directory, can you try downloading the test mbtiles file

wget https://github.com/acalcutt/tileserver-gl/releases/download/test_data/zurich_switzerland.mbtiles

**Comment by acalcutt** [comment]
I confirmed I was able to get this working with WSL + Docker Desktop here. 
image

but I did have to download that test file to the tileserver-gl directory first with
wget https://github.com/acalcutt/tileserver-gl/releases/download/test_data/zurich_switzerland.mbtiles

I'll look into that

**Comment by acalcutt** [comment]
I've updated this PR so 'npm run build-style-spec' generates a cjs file instead of a js file and removed the original fix

I've also updated the instructions a bit at https://github.com/acalcutt/tileserver-gl to make them a bit more clear that the file needs to be downloaded first. It did actually say before that docker should be run in the path with your mbtiles file, but it was easy to miss.

**Comment by HarelM** [comment]
Thanks, I need someone else besides me in order to approve this as this is a breaking change in style-spec package.

**Comment by wipfli** [comment]
Bump the style-spec major version.

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
Let me trigger the release for the style spec package...

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/runs/6295429269?check_suite_focus=true

**Comment by wipfli** [comment]
@acalcutt can you check if https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec/v/16.0.0 works for you?

**Comment by acalcutt** [comment]
Seems to work for me, The Tileserver-GL build, test, and publish completed successfully ( https://github.com/acalcutt/tileserver-gl/runs/6295867858?check_suite_focus=true )

And I am testing it at my https://tiles.wifidb.net and it worked fine there.

**Comment by wipfli** [comment]
Great, thanks for the patch!

**Pull request merged**
