### PR TITLE
Fix flicker on map resize

### LINKED ISSUE #2971: White flickering on resize in version 3.x.x
**maplibre-gl-js version**:
3.3.0 and 3.2.0
**browser**:
Firefox & Chrome
### Steps to Trigger Behavior

 1. Resize your browser with a full screen map

### Expected Behavior
Does not flicker. 
Especially because the behaviour in 2.4.0 on resize was better. Only the resized area was rerendered but not the complete map. 

### Actual Behavior
In Firefox is flickers very heavy on resize. In Chrome it gets completely white for a short time.

Thank you

### PR DESCRIPTION
**Pull request by daylightwarbler**
Fixes #2971 and #4158. Flicker on resize was introduced in #2157, released in v3.0.0, when map resizing was switched to using resizeObserver from using window resize events.

The fix is to immediately render the map upon resizing. The lead was this [thread](https://github.com/pixijs/pixijs/issues/3395#issuecomment-328495407).

Caveat: I'm not sure what to pass for the `paintStartTimeStamp` for [`map._render()`](https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.ts#L3021). I set it to `Date.now()`. `0` also works fine.

Before and after gifs (half speed):

before
after

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Looks good, can you fix the failing tests, and add another test if needed please?

**Comment by daylightwarbler** [comment]
Not sure how to debug the failing test yet. I can confirm that `jest --coverage --selectProjects unit` returns a nonzero exit code when I run it with the changes (`echo $?` prints `1`), but it doesn't print any error output on my machine. The CI job produced a type error in [`painter.ts`](https://github.com/maplibre/maplibre-gl-js/pull/4429/files#file-src-render-painter-ts-L412), but I don't get any errors for `npm run lint`.

**Comment by HarelM** [comment]
npm run test-unit --reportes=default
See more options here: 
https://github.com/maplibre/maplibre-gl-js/tree/main/test#running-tests

**Comment by HarelM** [comment]
Any updates on this?

**Comment by birkskyum** [comment]
I don't see any failing ci test.. which is it?

**Comment by birkskyum** [comment]
It seems like merging main fixed the test... Trying again to make sure it's not a fluke.

**Comment by HarelM** [comment]
I'm not sure I understand how this solves the problem.
When calling `_update`, which is done in the resize event, the `_update` method should add a `requestAnimtionFrame` with a call to `_render`.
So, I'm not sure I understand how forcing a call to render solves this issue...

Also, as stated before, please add a test for this bug.

**Comment by daylightwarbler** [comment]
@HarelM I think it’s a timing problem. [_update()](https://github.com/maplibre/maplibre-gl-js/blob/b2ec00e1300e925dcb54084a167cffa0d0744431/src/ui/map.ts#L2985) calls [triggerRepaint()](https://github.com/maplibre/maplibre-gl-js/blob/b2ec00e1300e925dcb54084a167cffa0d0744431/src/ui/map.ts#L3208), which calls [_render()](https://github.com/maplibre/maplibre-gl-js/blob/b2ec00e1300e925dcb54084a167cffa0d0744431/src/ui/map.ts#L3022), but in testing this I noticed that since the _render() call is in this [browser.frameAsync callback](https://github.com/maplibre/maplibre-gl-js/blob/b2ec00e1300e925dcb54084a167cffa0d0744431/src/ui/map.ts#L3211), it happens after about a ~10ms delay, compared to if it’s called [directly in the resize handler](https://github.com/maplibre/maplibre-gl-js/blob/b2ec00e1300e925dcb54084a167cffa0d0744431/src/ui/map.ts#L633), like in this commit. When I add an explicit 10ms delay before the new _render() call in the resize handler, the flicker comes back. Perhaps this points to a simpler solution.

**Comment by xabbu42** [comment]
Maybe #4535 can help here too?

**Comment by HarelM** [comment]
This needs a test nevertheless, but if #4535 solves this, it will be a better solution from my point of view.

**Comment by xabbu42** [comment]
> Maybe #4535 can help here too?

Unfortunately thats not the case. I can reproduce the flicker in that branch.

**Comment by HarelM** [comment]
Closing in favor of: 
- #4632

If the linked PR is not enough, please comment on it or comment in the linked closed issue.

**Pull request closed without merging**
