### PR TITLE
Add 38 render test baselines for Ubuntu 22 and Windows

### PR DESCRIPTION
**Pull request by zhangyiatmicrosoft**
## Launch Checklist

- 36 baselines for ubuntu22
- 2 for windows
- Refactored render.test.ts a little 
 -- move HTML template outside for easier reading
 -- generate failed/error test id as plain text report: very useful when working with this many failed cases.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Write tests for all new functionality.
 - [x] Manually test the debug page.

### CODE REVIEW

**Comment by zhangyiatmicrosoft** [comment]
Issue #1913

**Comment by HarelM** [comment]
Can you try and update the CI files as well to see that the CI passes with the new ubuntu?

While I get the idea behind moving the html code to different files, it was like this in the past and was annoying to maintain (it was more than 3 files, more like 6, but still), mainly since it was hard to understand where things are changed and how they will look.
I know render test file is a bit long but keeping it all in one place has its merits...
See here #1003 the original change, note that it might have been the extra `.ts` template files which were hard to read and make sense of. Your approach might be better, IDK.
@birkskyum what do you think?

**Comment by birkskyum** [comment]
In this case, I prefer the templates in template files because the IDE can make sense of it compared to the multiline strings. If it had been i.e. JSX or similar, I'd have preferred it stay together as well.

**Comment by HarelM** [comment]
JSX/React would be an overkill for this I believe.
@birkskyum I'm not sure I fully understand your answer here, can you clarify it? Do you approve this PR or do you think another form is better?

**Comment by birkskyum** [comment]
I approve the code changes, but I'd also like to see the CI render test pass using ubuntu 22 as well before merging.

Basically, I just prefer this:
Screenshot 2022-12-18 at 10 09 06

To this:
Screenshot 2022-12-18 at 10 09 18

**Comment by birkskyum** [comment]
I did try to run the render test, but I couldn't see any new log file generated.

**Comment by zhangyiatmicrosoft** [comment]
> I did try to run the render test, but I couldn't see any new log file generated.

It will generate new txt only if something failed or errored.

**Comment by zhangyiatmicrosoft** [comment]
> Can you try and update the CI files as well to see that the CI passes with the new ubuntu?
> 
> While I get the idea behind moving the html code to different files, it was like this in the past and was annoying to maintain (it was more than 3 files, more like 6, but still), mainly since it was hard to understand where things are changed and how they will look. I know render test file is a bit long but keeping it all in one place has its merits... See here #1003 the original change, note that it might have been the extra `.ts` template files which were hard to read and make sense of. Your approach might be better, IDK. @birkskyum what do you think?

Keeping the HTML approach for now after reading all the comment.

Updated to use "ubuntu-latest" in YML. Wonder if it is possible to specify u22...in case later GitHub moves to something new like u24 without letting us know. :)

Maybe after several weeks we can do a follow up PR to remove current baselines and rename all ubuntu22 to be the default.

**Review by birkskyum — APPROVED** [review]
Thanks for updating the CI

**Pull request merged**
