### PR TITLE
Bump documentation to latest upsteam commit

### PR DESCRIPTION
**Pull request by birkskyum**
While we wait for a release of documentation.js to be cut, we can just use the latest commit in the repo. We currently use a very outdated version of the library and it fills up the terminal with deprecation warning.

The linter in the new version is more thorough so we a set of newfound warnings are fixed too.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Note that this will throw dependbot off, and it will not notify us on a new version release so we need to monitor this manually, I think.
Just FYI.

**Comment by birkskyum** [comment]
Now all we need is a release to npm of the latest documentation.js, because `npm ci` doesn't like the url to a specific commit hash in package.json.

**Comment by birkskyum** [comment]
The render test breaks because it's running using node 16.13, which whips with npm 8.1.2 which can't handle the commit hash in npm. Node 16.16 which the other tests are running with has npm 8.16 bundled. [npm versions higher than 8.5.2 works](https://github.com/npm/cli/issues/2971).

**Comment by birkskyum** [comment]
> Note that this will throw dependbot off, and it will not notify us on a new version release so we need to monitor this manually, I think. Just FYI.

I published a 14.0.0-alpha.0 release to npm so and remove the dependabot-ignore, so hopefully it will work as expected now.

**Comment by wipfli** [comment]
I am surprised that `package-lock.json` has 20k+ insertions and deletions. Is this because of an npm version mismatch, @birkskyum?

**Comment by wipfli** [comment]
And cool that you were able to update the documentation.js version! Does `maplibre/maplibre-gl-js-docs` need anything updated now?

**Comment by birkskyum** [comment]
> I am surprised that `package-lock.json` has 20k+ insertions and deletions. Is this because of an npm version mismatch, @birkskyum?

good question. it's actually because the npm format changed from sha1 to sha256 for validating package integrity some years ago [link](https://stackoverflow.com/questions/47638381/why-did-package-lock-json-change-the-integrity-hash-from-sha1-to-sha512). So because i had to update the file it now use the sha256 throughout.

**Comment by birkskyum** [comment]
The docs will need an update once 2.20 is out, as i believe the maplibre-gl-js submodule in the docs repo is still locked to the 2.19 tag

**Comment by birkskyum** [comment]
The docs will need an update once 2.20 is out, as i believe the maplibre-gl-js submodule in the docs repo is still locked to the 2.19 tag. I gave the documentation.js library a facelift and made a prerelease that we depend on now. I got write access to the repo so let me know if you experience complications if you try to update the docs at some point.

**Comment by wipfli** [comment]
Cool, thanks!

**Pull request merged**
