### PR TITLE
Mark failed render tests as red on console

### PR DESCRIPTION
**Pull request by zhangyiatmicrosoft**
Failed test messages are buried and hard to spot. Mark them red.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by zhangyiatmicrosoft** [comment]
After 
image

**Comment by zhangyiatmicrosoft** [comment]
Before
image

**Comment by zhangyiatmicrosoft** [comment]
I think simple a cosmetic fix like this does not need to be in changelog. Please let me know otherwise. Thanks

**Comment by HarelM** [comment]
There's a problem with the tests, I'm not sure why and when it started.
I've seen some PRs that are failing for no good reason...
Might be a node version update if I need to guess... :-/

**Comment by zhangyiatmicrosoft** [comment]
> 

This change is not related to the current problem of tests failing in build pipeline.

We have been seeing render tests failing on different systems such as windows, ubuntu on physical machine or VM or different video cards (AMD/Nvidia/intel) -- mainly because of the thread hold varies slightly.

Therefore, I am making this change so people can spot failing tests easier among thousands of messages.

**Comment by HarelM** [comment]
I know, I'm trying to fix it here #1912. I think this PR is great, I just want to make sure everything is OK before merging it...

**Pull request merged**
