### PR TITLE
Release 2.2.0-pre.4

### PR DESCRIPTION
**Pull request by birkskyum**
A lot of good work [has happened](https://github.com/maplibre/maplibre-gl-js/compare/8373c9d...88a3bc3) since last prerelease over a month ago, so let's cut a new one. 

@HarelM , @astridx , @wipfli

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
BTW, what's keeping us from creating an official release?

**Comment by birkskyum** [comment]
@HarelM , I was actually going to raise that question in the meeting today. The only thing I can think of here is that 2.2.0 contains the terrain feature which might still be a bit experimental, but that shouldn't hold it back I think.

**Comment by ntadej** [comment]
Stupid question: Is there a reason prereleases do not have a changelog? It may still be useful.

**Comment by HarelM** [comment]
It's a bug in our release code... Change log is your friend here :-)

**Comment by birkskyum** [comment]
@HarelM  The concern around geojson that you mentioned [here](https://github.com/maplibre/maplibre-gl-js/pull/1231)  is the reason I hesitate to make an official, because I don't know if it is resolved.

**Comment by HarelM** [comment]
I think the version is out enough time to make sure this is not an issue.

**Pull request merged**
