### PR TITLE
Minify internal exports

### LINKED ISSUE #3194: Use `minifyInternalExports` to decrease bundle size
Adding this option to rollup decreases bundle size by about 9kb (1.7kb gzipped) and also makes the bundle size less sensitive to hoisting shared code from main/worker into shared chunk:

```diff
--- a/rollup.config.ts
+++ b/rollup.config.ts
@@ -22,7 +22,8 @@ const config: RollupOptions[] = [{
         format: 'amd',
         sourcemap: 'inline',
         indent: false,
-        chunkFileNames: 'shared.js'
+        chunkFileNames: 'shared.js',
+        minifyInternalExports: production
     },
     onwarn: (message) => {
         console.error(message);
```

We decided not to include in #3185 but should pursue in a separate release to isolate potential issues.

Given these 3 files:

```js
// shared.ts
export default function exportedFunction() {
    return 1;
}
```

```js
// index.ts
import exportedFunction from './shared';

export default function () {
    console.log('from main', exportedFunction());
}
```

```js
// worker.ts
import exportedFunction from '../shared';

export default function () {
    console.log('from worker', exportedFunction());
}
```

the minified build outputs this currently:

```js
define(["exports"],(function(n){"use strict";n.exportedFunction=function(){return 1};}));
define(["./shared"],(function(e){"use strict";return function(){console.log("from worker",e.exportedFunction());}}));
define(["./shared"],(function(n){"use strict";return function(){console.log("from main",n.exportedFunction());}}));
```

but with `minifyInternalExports: true` it outputs this:

```js
define(["exports"],(function(e){"use strict";e.e=function(){return 1};}));
define(["./shared"],(function(e){"use strict";return function(){console.log("from worker",e.e());}}));
define(["./shared"],(function(n){"use strict";return function(){console.log("from main",n.e());}}));
```

_Originally posted by @msbarry in https://github.com/maplibre/maplibre-gl-js/issues/3185#issuecomment-1752814295_

### PR DESCRIPTION
**Pull request by msbarry**
## Launch Checklist

Fix #3194 by adding `minifyInternalExports` option to rollup config when building minified output. See https://github.com/maplibre/maplibre-gl-js/issues/3194#issue-1932927704 for more details on what this does.

Minified build size before: 772,277 (before) -> 761,628 (after)
Gzipped: 203,721 (before) -> 201,981 (after)

### CODE REVIEW

**Comment by HarelM** [comment]
How will this affect external minification tools like when using this library and webpack for example?

**Comment by HarelM** [comment]
Let's wait a bit to see that we can overcome the async issue that we found out.
After that we'll merge this assuming everything is working as expected.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Can you add a change log entry? This way if we find issue we might look into this PR for reference.
THANKS!!

**Comment by msbarry** [comment]
Thanks! Added a changelog entry for this.  I also tested in my create-react-app build and everything seems to work fine. It reduced the gzipped build js file by ~2kb.

**Pull request merged**
