### PR TITLE
Generate benchmark PDF

### PR DESCRIPTION
**Pull request by wipfli**
With this pull request we can run the up-coming benchmarks in CI in a headless chrome browser which gets controlled like a puppet by puppeteer. Currently this compares the pull request against `main` but we could also compare against releases. 

The pdf with the benchmark results gets uploaded as an artifact.

### CODE REVIEW

**Comment by HarelM** [comment]
Generating PDF as part of the CI is nice, but if there was a good criteria for pass/fail it would be better I think...
Otherwise how would you decide if this is OK or not? Do the reviewers need to look at it before accepting a PR?

**Comment by wipfli** [comment]
That's a good question. I think pull requests should be compared to main. However, what the threshold should be for pass vs fail is hard to say. Also the runner is a bit slow and it might take hours for all benchmarks to go through.

**Comment by wipfli** [comment]
In general we have to ask the question of how will the benchmarks be used in the review process?

**Comment by xabbu42** [comment]
Whatever the automatic process for benchmarks will be (and the threshold), keep in mind that it is not possible to fully automate these decisions. A new feature may be expensive but worth it whereas a simple bugfix should usually give no slowup at all or something is wrong. Also many small slowups may not be significant/measurable but a new release with all the changes together may be significantly slower than the last release. So it is not possible to give an absolute threshold per pull request without any exceptions.

**Comment by HarelM** [comment]
I agree, nevertheless, we need to define guidelines...

**Comment by wipfli** [comment]
Let's discuss this at #427.

I close this pull request. Making benchmark pdfs in ci seems the wrong approach to me.

**Pull request closed without merging**
