### PR TITLE
Migrate benchmark files to Typescript WIP

### PR DESCRIPTION
**Pull request by chippieTV**
- [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] briefly describe the changes in this PR

- run[ babel-plugin-flow-to-typescript](https://www.npmjs.com/package/babel-plugin-flow-to-typescript) against files in `bench/benchmarks` and `bench/lib`
- fix formatting (2 space to same as rest of project) and switch out double quotes for single
- TODO tsc gives 77 errors (updated formatting so you can easier see the problems)

since it doesn't run tsc to completion treat with caution.. it might be a step backwards!

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks a lot! For easier review it would be great if git was able to detect that file names were changed and show line-by-line diffs. I guess right now the overlap between the old and the new files are too small.

**Comment by wipfli** [comment]
Let me try and see what happens if I put the `babel-plugin-flow-to-typescript` into a commit with nothing else.

**Comment by chippieTV** [comment]
one possible way.. is just keep the extensions. make another commit where they are all set to .js still with the changes, then another commit with git mv to rename

**Comment by wipfli** [comment]
Ah with lower overlap settings git will detect that the file was moved:

```bash
➜  benchmarks git:(benchmarks) ✗ git status -M10
On branch benchmarks
Your branch is up to date with 'origin/benchmarks'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    expressions.js -> expressions.ts
```

**Comment by chippieTV** [comment]
oh.. I did the other way.. here's an alternative PR if it's easier. Feel free to close whichever one.

https://github.com/maplibre/maplibre-gl-js/pull/394/files

**Comment by HarelM** [comment]
I didn't use this plugin to convet. I used flowts command-line tool to preserve formatting, which later on git recognized, I think it's a better approach.
Also when staging a deleted file and a added file for will show you if it thinks they are the same...

**Pull request closed without merging**
