### PR TITLE
Terrain3D symbol cutoff at horizon

### PR DESCRIPTION
**Pull request by prozessor13**
Hello,

i found an easy solution to cutoff symbols near the horizon. Maplibre already calculates a `perspectiveRatio` value for every collision-box and collision-circle. So we can use this value to check if the symbol is near the horizion. The implemented cutoff value is evaluated by trial & error.

Be aware that this and the horizion logic has an impact on 2D & 3D code. The horizon logic is alreay implemented and can be found at:

* https://github.com/maplibre/maplibre-gl-js/blob/terrain3d/src/geo/transform.ts#L698
* https://github.com/maplibre/maplibre-gl-js/blob/terrain3d/src/geo/transform.ts#L857

### CODE REVIEW

**Comment by prozessor13** [comment]
Grrr, made the branch somehow wrong, how to fix that? did:

    git checkout -b terrain3d-symbol-cutoff terrain3d

**Comment by prozessor13** [comment]
Ok, i think i know what i did wrong, simply should do:

    git branch terrain3d-symbol-cutoff terrain3d

right? Can please someone delete this branch and pull-request? because i am not so familiar with github, and i do not want make another mistake :)

Thx.

**Comment by HarelM** [comment]
You opened the PR against main and not against terrain3d branch :-) I've just changed that.

**Comment by HarelM** [comment]
Can you add a test to cover this scenario?
Also worth fixing the `getBounds` method somehow?

**Comment by prozessor13** [comment]
thx @HarelM ,

added a getBounds fix, tests will follow!

**Review by HarelM — APPROVED** [review]
Looks good, Thanks!!

**Pull request merged**
