### PR TITLE
Convert plantuml diagrams to mermaid

### PR DESCRIPTION
**Pull request by msbarry**
## Launch Checklist

Github supports mermaid embedded markdown now, so we can convert the plantuml diagrams to mermaid and get rid of the extra build steps/tool.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [n/a] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
You are probably the only person aware of this technical info 😀

**Comment by msbarry** [comment]
Before/after:

<table>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
<td>
image
</td>
<td>
image
</td>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
</table>

You can see the live page here: https://github.com/msbarry/maplibre-gl-js/blob/mermaid/developer-guides/life-of-a-tile.md

**Comment by HarelM** [comment]
Yup! Thanks! This look great!

**Comment by msbarry** [comment]
Thanks! I realized that node-plantuml requires you to have java installed as well, so this should remove that dependency.

**Comment by msbarry** [comment]
One downside is that these won't show up on the github app (ios one at least)...

**Pull request merged**
