### PR TITLE
Upgrade jest to 28

### PR DESCRIPTION
**Pull request by birkskyum**
The playwright-jest PR mentioned in #1292  was merged, breaking compatibility with Jest 27.  I installed it and everything seems to be working now.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
Thanks!!

**Comment by HarelM** [comment]
Any chance you can take a lot at #1391?

**Comment by HarelM** [comment]
Oh, and do we need to update some configuration related to dependbot?

**Comment by birkskyum** [comment]
> Oh, and do we need to update some configuration related to dependbot?

We can indeed. #1398 

> Any chance you can take a lot at #1391?

I did have a look at it, and this is where it's at now: #1399

**Pull request merged**
