### PR TITLE
Fix uncautht OverscaledTileID error appearing with terrain enabled

### PR DESCRIPTION
**Pull request by zbigniewmatysek-tomtom**
Fixes https://github.com/maplibre/maplibre-gl-js/issues/1650.

## Context
Negative zoom levels were introduced by mapbox to handle displaying tiny maps. By negative zoom level they can scale down tiles. This PR is not questioning this design choice, just fixes issue with querying elevation caused by not handling negative zoom.

## Problem
[`OverscaledTileID` in `getElevation()`](https://github.com/maplibre/maplibre-gl-js/blob/main/src/geo/transform.ts#L503) was constructed with negative zoomLevel (not allowed by tile spec) and thus threw uncaught error.

## References:
* PR that introduced negative zoom levels: https://github.com/mapbox/mapbox-gl-js/pull/9028
* Previous attempt to fix: https://github.com/maplibre/maplibre-gl-js/pull/1733

## Launch Checklist
 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Write tests for all new functionality.
 - [x] Manually test the debug page.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you elaborate how removing this variable solves the issue?
@prozessor13 can you take a look and see if this seems like a good fix?

**Comment by zbigniewmatysek-tomtom** [comment]
@HarelM 
This line solves the issue:
`this.tileZoom = Math.max(0, Math.floor(constrainedZoom));`

I noticed `zoomFraction` is not used anywhere, so I removed it, but it's not related to the original issue.

**Comment by HarelM** [comment]
Ahh, then I focused on the wrong thing. Can you split the two changes in to separate PRs by any chance?

**Comment by zbigniewmatysek-tomtom** [comment]
@HarelM 
I would prefer to leave it - `zoomFraction` is based on `tileZoom` which I've changed, this variable doesn't make any sense nor is used. I played an archeologist and last time it had been used was around 9 years ago [here](https://github.com/maplibre/maplibre-gl-js/commit/1599a01878627001a6c5ba985f0892461a943b0a) and in another place file that doesn't exist anymore.:

**Review by HarelM — APPROVED** [review]

**Comment by sebastianoscarlopez** [comment]
Thanks, @zbigniewmatysek-tomtom, because of the fix and archeologist work 😄 and @HarelM, because of the review & merge

**Pull request merged**
