### PR TITLE
doc: added svelte-maplibre-components and sveltekit-maplibre-boilerplate on the plugins page

### PR DESCRIPTION
**Pull request by JinIgarashi**
Added the following two GitHub repository to develop maplibre application in svelte/sveltekit into the documentation.

- [sveltekit-maplibre-boilerplate](https://github.com/watergis/sveltekit-maplibre-boilerplate)
- [svelte-maplibre-components](https://github.com/watergis/svelte-maplibre-components)

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
THANKS!
Any change you can also create a PR in awesome-maplibre repo?

**Comment by JinIgarashi** [comment]
@HarelM Thanks. I will create a PR to that repo later when I will have time.

**Comment by JinIgarashi** [comment]
By the way, this repo’s contents should be merged to mkdocs one. There are many of them duplicated.

https://github.com/maplibre/awesome-maplibre

**Comment by JinIgarashi** [comment]
@HarelM I added same info to awesome-maplibre repo. Please check it and I really appreciate if you can merge these two PRs to main branch. Thanks.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Awesome maplibre is for all things relevant to maplibre (ntive, martin etc).
An optimization of linking to the plugins page can probably be done I guess.
Feel free to submit a PR.

**Pull request merged**
