### PR TITLE
fix: [issue-3157] 3d buildings example

### PR DESCRIPTION
**Pull request by sebastianoscarlopez**
The current 3D buildings example is not working as expected, it was reported in #3157 

Current behavior, we can see the buildings don't scale based on zoom.

https://github.com/maplibre/maplibre-gl-js/assets/10349981/5d914dfb-081f-43e1-afb1-889779568507

Behaviour with this pr

https://github.com/maplibre/maplibre-gl-js/assets/10349981/4d434856-be67-47e3-9f6b-2b359e85fe64

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by acalcutt** [comment]
That shrinking/rising effect looks really cool.

On thing i notice is` 'fill-extrusion-opacity': 0.6 ` got lost, which I think is useful because it helps see the roads through the buildings.

**Comment by neodescis** [comment]
Looks great to me! I could go either way on seeing the roads through the buildings.

**Review by neodescis — APPROVED** [review]

**Comment by sebastianoscarlopez** [comment]
the opacity has a bug, here my comments regarding to that also a codepen to see it  https://github.com/maplibre/maplibre-gl-js/issues/3157#issuecomment-1746868797

**Review by lopezgonzalo89 — APPROVED** [review]
Scale and colors, looks great to me.

**Pull request merged**
