### PR TITLE
Migrate react view to tsx

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Mainly added some types.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks, looks good so far code-wise but does not compile yet. It only produces a `benchmark_view_generated.js` file once I edit `bench/rollup_config_benchmarks.js` to:

```diff
 const viewConfig = {
-    input: 'bench/benchmarks_view.js',
+    input: 'rollup/build/tsc/bench/benchmarks_view.jsx',
     output: {
         name: 'Benchmarks',
```

And then it crashes in the browser with `TypeError: version.summary is undefined`.

**Comment by wipfli** [comment]
Closes #430.

**Comment by HarelM** [comment]
Hmm... Interesting... What command are you running? Why is it working for me?

**Comment by wipfli** [comment]
I am running `npm run build-dev && npm run start-bench`. Make sure to remove outputs for previous runs with `rm bench/**/*generated*` and maybe also `rm -rf rollup/build`.

**Comment by HarelM** [comment]
Can we move the generated code to rollup/build folder too? I think all generated code should be there.
I think this might be what I forgot to delete...
I'll continue work on this tonight and see what's not working...

**Comment by HarelM** [comment]
@wipfli I think I managed to fix all the errors. Can you give it a go?

**Comment by wipfli** [comment]
Thanks a lot. Compiles locally and I can run the first few benchmarks. However, in `Layout` I get this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'transformRequest')
```

Can you check if you can run all the benchmarks on your machine?

**Comment by wipfli** [comment]
* run `npm run build-dev && npm run start-bench`
* open chrome, go to http://localhost:9966/bench/versions?compare=main
* let it run, all goes well until Layout
* gets stuck in "Running..." state with this in the console:

**Comment by wipfli** [comment]
However, I get the same error also on the `benchmarks` branch. So this does not seem to be related to your proposed changes.

**Review by wipfli — APPROVED** [review]

**Pull request merged**
