### PR TITLE
Notice to not use Mapbox servers

### PR DESCRIPTION
**Pull request by arichnad**
changelog change:  do not use mapbox servers with this library.

### CODE REVIEW

**Comment by wipfli** [comment]
I think this is a correct statement.

**Review by wipfli — APPROVED** [review]

**Comment by nyurik** [comment]
Technically we shouldn't really ask users to not use the lib, but instead put a notification somewhere visible that if users use mapbox's service with a 3rd party lib like this one, they would be violating mapbox's license (at least that's my understanding)

**Comment by kylebarron** [comment]
> they would be violating mapbox's license

Along the same lines of https://github.com/maplibre/maplibre-gl-js/discussions/290#discussioncomment-1320751 is there concrete evidence of this, and if so, could we display it prominently on the documentation?

I quickly looked through Mapbox's [Terms of Service](https://www.mapbox.com/legal/tos) and the relevant bits seemed to be:

> 7.2: You acknowledge and agree that failure to use the current version of Mapbox Software may result in potentially different (and higher) fees being charged to you, and agree to pay any such fees as calculated by us
> 11.2: We may change the features and functions of the Services, including APIs. It is your responsibility to ensure that calls or requests you make to the Services are compatible with our then-current APIs.

I don't see anything that says using a third party library violates their terms of service, but maybe I missed something?

**Comment by nyurik** [comment]
@kylebarron thx, I am not certain about this point - it was mentioned several times in various discussions, so I assumed (possibly incorrectly) that it is a requirement.  On the other hand, I see very little value in MapLibre to maintain MB-specific code unless it prevents users from using their service (assuming it is allowed).  So ideally we should just support functionality common to all services, with possibility of service-specific extensions.  Perhaps we should have a dedicated section, maybe in the main readme, that discusses this - something along the lines of "if someone uses this lib with MB service, it is their responsibility to comply with all MB licensing requirements. Your millage may vary" :)

**Comment by HarelM** [comment]
The following file was removed, it states that if you change it you are breaking MB terms of service.
https://github.com/maplibre/maplibre-gl-js/blob/1.x/src/util/mapbox.js
In order to use MB you need some version of it.
To me it feels like breaking their terms, but I'm no lawyer.
I don't have any objections to adding stuff to the readme or changelog. Feel free to do so...

**Comment by marcelnormann** [comment]
I think  we should be more precise with the changelog item: _If you want to use this library with Mapbox servers please refer to https://github.com/maplibre/maplibre-gl-js/blob/1.x/src/util/mapbox.js#L3-L13 and the Mapbox  TOS_  

Probably changelog is not enough;, we also need to add this warning to Mapbox migration instructions.

**Comment by kylebarron** [comment]
> The following file was removed, it states that if you change it you are breaking MB terms of service

That text was [added in Mapbox 1.0.0](https://github.com/maplibre/maplibre-gl-js/commit/5dae56219bcf6942b81b4c455748f3754f7cdeba#diff-60612f29b10a34dab591cc56afc0bb3664ddc59650914bf0c5729b153f92877fR3-R14). Quickly reading the snapshot of the TOS [at the nearest date](https://web.archive.org/web/20191203000149/https://www.mapbox.com/legal/tos/) I didn't see any relevant text.

My opinion is an amalgam of https://github.com/maplibre/maplibre-gl-js/pull/336#issuecomment-919093381, https://github.com/maplibre/maplibre-gl-js/discussions/290#discussioncomment-1325087, and https://github.com/maplibre/maplibre-gl-js/discussions/290#discussioncomment-1324795. I think instead of a blunt "do not use this library with Mapbox services" I'd suggest a very prominent section of the README that says

> This project is entirely unaffiliated with Mapbox. No warranties or compatibility guarantees are provided to ensure Maplibre GL JS works with Mapbox services. If you wish to use Maplibre GL JS with Mapbox services, we suggest carefully reading the Mapbox Terms of Service and https://github.com/maplibre/maplibre-gl-js/blob/1.x/src/util/mapbox.js#L3-L13 to evaluate compliance with Mapbox terms.

**Comment by aggretoso** [comment]
hey @nyurik - here's the short abstract that we discussed a few minutes ago on the OSS sync call:

This library is based on the <name> by Mapbox (Copyright Mapbox), <URL where we got the code> with heavy modifications. [if we already have attribution of the source material, we don't need to include this part]

This library is licensed to you under the BSD 3-Clause License. If you choose to use this code with a tile service, your use of the tile service may be governed by its own separate terms of use. You should make sure you comply with both the BSD 3-Clause License and any terms of use applicable to the tile service.

**Pull request merged**
