### PR TITLE
Set required for geojson data

### LINKED ISSUE #1396: GeoJSONSourceSpecification problems
In GeoJSONSourceSpecification it would be better to have (based on documentation):
* "data?": string | GeoJSON; // assuming Geometry, Feature and FeatureCollection are valid here
* "clusterProperties"?: {[propertyName: string]: ExpressionSpecification}

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Partially fixes #1396 - it only adds required to data field, other specification are missing due to the fact that one can set both string and feature collection, and specifying the definition for feature collection can be challenging if not more.

### CODE REVIEW

**Comment by wipfli** [comment]
That is a breaking change, right?

**Comment by HarelM** [comment]
In terms of code, maybe, in terms of documentation no.
This is basically to align the code with the documentation.
I don't know if this can be considered a breaking change...

**Comment by wipfli** [comment]
If there is no test for this, it would be great if you could add one...

**Comment by HarelM** [comment]
I actually removed a test that failed since this is now required. So it feels like this is covered...

**Comment by wipfli** [comment]
Ah yes, you are right regarding the test. 

I am a bit worried that this change will break some maps... Should in general be the docs or the style spec/code be the source of truth for how stuff behaves?

**Comment by HarelM** [comment]
@wipfli where are we on this?
Since the next version is 3.0 and we are planning to break things, why not this too? :-)

**Comment by wipfli** [comment]
v3 would be great for this... Could you create a lable "breaking" such that we will know what were the breaking pull requests?

**Comment by HarelM** [comment]
Added to this change and also the css.

**Comment by HarelM** [comment]
@wipfli can you review and if approved merge?

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
By the way we have some bad coupling here between MapLibre GL JS and the docs repo. This change here of the API for example we justified by the fact that the documentation in the docs repo says that the source is required.

So we changed GL JS because of:

https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/pages/style-spec/sources.md

**Comment by HarelM** [comment]
True, I said that it might be better to incorporate the docs repo inside this repo in another thread :-)

**Pull request merged**
