### PR TITLE
Move @types to devDependencies

### PR DESCRIPTION
**Pull request by birkskyum**
All @types/x dependencies should be in 'devDependencies' as it's not used by runtime

### CODE REVIEW

**Comment by HarelM** [comment]
Nope, these should be where they are.

**Comment by birkskyum** [comment]
Okay, that is a bit surprising to me. How come that is?

**Comment by HarelM** [comment]
You already did that in the past :-) it breaks the typescript typing that comes with this library if these are not installed with it.

**Comment by birkskyum** [comment]
Okay, thanks :) Forgot about it

**Comment by rotu** [comment]
> You already did that in the past :-) it breaks the typescript typing that comes with this library if these are not installed with it.

This seems strange. How does it break? (and why doesn’t it fail the PR checks?)

**Comment by HarelM** [comment]
I terms of testing, this is not easy to test as you need to install the package, which is not easy in a PR.
The typescript definitions that come with the library reference these two packages' types. If these are not included the types are broken.
I think there was a version with this problem you can see. 2.3 or 2.1.sonething... You can easily see in unpkg if you want.

**Comment by rotu** [comment]
> I terms of testing, this is not easy to test as you need to install the package, which is not easy in a PR

Challenge accepted.

It will require some changes to work, but this package *should* be installable from a PR via, e.g. `npm install github:maplibre/maplibre-gl-js#pull/1987/merge`

> The typescript definitions that come with the library reference these two packages' types. If these are not included the types are broken.

I was thrown off by the synthesized `dist/package.json` (which has no runtime dependencies and no version number):

https://unpkg.com/browse/maplibre-gl@2.4.0/package.json
https://unpkg.com/browse/maplibre-gl@2.4.0/dist/package.json

----

What are the actual expected runtime dependencies?
Is there any reason to keep `dist/package.json` around?

**Comment by HarelM** [comment]
A far as I remember, there's no runtime dependencies, this library is mainly standalone.
This package.json file is there to indicate this is a commonjs package as opposed to the definition in the main package.json for `type: module` which causes webpack and other to fail packing this library.
We can consider renaming the js file cjs as part of version 3, but that's a big breaking change which I'm not sure is valuable to the user...

**Pull request closed without merging**
