### PR TITLE
Allow auto merge to Dependabot PR if they pass CI

### PR DESCRIPTION
**Pull request by HarelM**
Enable auto merge to dependent bot if CI passes.

Heavily relies on https://rednafi.github.io/reflections/automerge-dependabot-prs-on-github.html

I've been spending a lot of time simply clicking approve on dependant bot PRs.
I hope this will reduce the time I need to spend on this.

@birkskyum @zhangyiatmicrosoft

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for the info! I see that they have automatic approve there as well, I'll add that too.

**Comment by stepankuzmin** [comment]
https://github.com/maplibre/martin/blob/main/.github/workflows/dependabot.yml

**Comment by HarelM** [comment]
Thanks @stepankuzmin! I've updated the action according to the example in martin.

**Comment by birkskyum** [comment]
It's a good idea, but it has to run tests for each commit - had issues in the past that it merge a ton of commits at once, and some were incompatible.

**Comment by HarelM** [comment]
I think it will run the tests as far as I read.

**Review by zhangyiatmicrosoft — APPROVED** [review]

**Comment by HarelM** [comment]
Let's see how it works, worst case we remove this...

**Comment by wipfli** [comment]
The dependabot open pull request limit is at 20 I think currently. If you get too many incompatibility conflicts, you might want to turn this number down again...

**Pull request merged**
