### PR TITLE
Fix level of detail at high pitch

### PR DESCRIPTION
**Pull request by NathanMOlson**
This (failing) unit test demonstrates the issue reported here: https://github.com/maplibre/maplibre-gl-js/issues/3983 and https://github.com/maplibre/maplibre-gl-js/issues/4703

### CODE REVIEW

**Comment by NathanMOlson** [comment]
This fixes https://github.com/maplibre/maplibre-gl-js/issues/3983 and improves https://github.com/maplibre/maplibre-gl-js/issues/4703 by calculating the desired zoom level for each tile independently. Each tile zoom is calculated by scaling  the center point zoom by the ratio of (3D) distance-to-tile to distance-to-center. Old behavior is preserved when there is no terrain and pitch < 60 degrees.

Before at 70 degrees pitch:
before_lodfix
After:
after_lodfix

Before at 80 degrees pitch:
before_lodfix_80
After:
after_lodfix_80

**Comment by HarelM** [comment]
Thanks for taking the time to open this PR!
We are working on the globe branch where we moved a lot of the tile fetching logic to a different file.
There are two options here from my point of view:
1. Merge this to main and then merge/rewrite this in globe branch.
2. Merge this to globe branch and wait for version 5 release.

Let me know which works better for you.

Can you also show before and after of the showtilesboundries when terrain is disabled?

**Comment by NathanMOlson** [comment]
The previously-posted images are with terrain disabled. Here is the before/after with terrain enabled:

Before:
before_lodfix_terrain
After:
after_lodfix_terrain

**Comment by NathanMOlson** [comment]
> Thanks for taking the time to open this PR! We are working on the globe branch where we moved a lot of the tile fetching logic to a different file. There are two options here from my point of view:
> 
> 1. Merge this to main and then merge/rewrite this in globe branch.
> 2. Merge this to globe branch and wait for version 5 release.
> 
> Let me know which works better for you.

I just took a look at the `globe` branch and it looks like there's been some extensive rearrangement. So I think this will need a rewrite either way. Given that there will be no new 4.x releases, I don't see a reason to merge it to `main`. I'll work on moving it to `globe`.

**Comment by HarelM** [comment]
I can carve out a new release if 4.x if this is something you absolutely need, but I would prefer to simply move this to 5.x if this is not urgent for you as it might take around 2 month to release a stable 5.x version.

**Comment by NathanMOlson** [comment]
I'm happy to move this to 5.x.

**Comment by NathanMOlson** [comment]
Superceded by https://github.com/maplibre/maplibre-gl-js/pull/4750

**Pull request closed without merging**
