### PR TITLE
use glyph-metrics from tinySDF.draw call

### PR DESCRIPTION
**Pull request by prozessor13**
In some of our stylesheets we get "mismatched image size" errors. This is because tinySDF glyphs has hardcoded width & height properties, which do not match with the generated width & height generated by TinySDF.draw calls.

I do not know anything about tinySDF and what it is used for in detail, but the below lines fixes the issue in our case.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Write tests for all new functionality.

### CODE REVIEW

**Comment by HarelM** [comment]
I'm not sure the impact of this in terms of performance, but the tests are failing and needs to be fixed...

**Comment by HarelM** [comment]
@wipfli @xabbu42 Can you guys take a look at this in terms of performance?
Seems like this is solving some error people are experiencing (mainly #718 I believe)...

**Comment by HarelM** [comment]
Nevermind, I looked at the code again and there's not actual change in the flow of the code, it uses the same method that was used before, but extract more data out of it.
I think the code is good and ready to be merged, but I would feel better if someone else review this too.

**Review by HarelM — APPROVED** [review]

**Comment by prozessor13** [comment]
Hallo,

i will create a test, but currently i am very busy. I think next week is realisitc.

Regards.

**Comment by HarelM** [comment]
Great! Thanks! Looking forward to it.

**Comment by HarelM** [comment]
I've created a similar PR in which I only updated the tests so that tinySDF is no longer mocked.
See #917

**Comment by HarelM** [comment]
Fixed by #917

**Pull request closed without merging**
