### PR TITLE
Adding `windows-latest` to OS matrix of CI build

### PR DESCRIPTION
**Pull request by kircher1**
This change attempts to add a CI build for the windows OS to reproduce errors that I've been encountering locally when running query/browser tests.

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by kircher1** [comment]
@HarelM, I'm not seeing Windows the running CIs of this PR, still just Ubuntu-- is this the right build.yml?

**Comment by HarelM** [comment]
I don't see the build running on either Windows or Linux, might be a typo somewhere there?

**Comment by birkskyum** [comment]
I believe this is what you want https://github.com/maplibre/maplibre-gl-js/actions/runs/2862624933

**Comment by birkskyum** [comment]
Do you see these tests if you run them locally?

**Comment by kircher1** [comment]
@birkskyum, I'm trying to get to the bottom of this #1501 (see error message in the issue)

**Comment by birkskyum** [comment]
Gotcha. So, I can see that the windows CI build was able to run the test-browser. That fails locally for you right?

**Comment by kircher1** [comment]
Yeah, fails locally. Sounds like this may be a local issue related to my setup.

**Comment by birkskyum** [comment]
You can see the specs of [windows-latest here](https://github.com/actions/runner-images). It's a Windows Server 2022 that does run it. Could you maybe try to run `npx jest --clearCache` and then `npm run test-browser`, just in case?

**Comment by kircher1** [comment]
Thanks for helping debug-- After `npx jest --clearCache`, all tests ran (although all 3 failed, but that's progress).

However, running the browser test a _second_ time (without clearing the jest cache) resulted in issue #1501. So it seems this issue only repros on subsequent runs, with a non-empty jest cache.

**Comment by birkskyum** [comment]
Okay, so until we fix the cache issue, alternating between clearing it and running will at least get us this fast. I have the exact same experience with jest, so will make a ticket about it.

**Comment by kircher1** [comment]
Sounds good-- closing the PR.

**Pull request closed without merging**
