### PR TITLE
Bugfix: setStyle->style.setState didn't reset _serializedLayers

### PR DESCRIPTION
**Pull request by CraigglesO**
## Launch Checklist

Fixes https://github.com/maplibre/maplibre-gl-js/issues/3101 and https://github.com/maplibre/maplibre-gl-js/issues/2587

Very minor bugfix so I didn't add testing or visuals. To explain why this works:
inside style.setState, it compares `diffStyles(serializedStyle, nextState)`. serializedStyle pulls from `this._serializedLayers` but since it was never reset, rather than rebuilding `_serializedLayers` it checks against the very first style no matter what. If you updated a layer or created a layer it would indirectly fix this bug.

You can see `this._serializedLayers` being 'reset' in [_updateLayer](https://github.com/maplibre/maplibre-gl-js/blob/d6fdbe449ed8f8195399490c57a2e061ba90bbb7/src/style/style.ts#L1246) and [_createLayers](https://github.com/maplibre/maplibre-gl-js/blob/d6fdbe449ed8f8195399490c57a2e061ba90bbb7/src/style/style.ts#L388)

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you add a unit test that "reproduces" this issue so that it won't break in the future?
@zhangyiatmicrosoft can you please check that this is OK as you have changed the behavior related to this in the following PR: #2306

**Comment by HarelM** [comment]
THANKS for taking the time to fix this issue!!

**Comment by CraigglesO** [comment]
@HarelM This test covers the issue, sorry about being a bit lazy there. Frustratingly, the windows test sometimes passes sometimes doesn't but I believe its no relation to this PR?

**Comment by HarelM** [comment]
Yea, I don't think it is related to this PR.
I added some retries in a PR that is waiting for a review, I hope it'll better after that...

**Comment by HarelM** [comment]
I want to wait for @zhangyiatmicrosoft to review this before I merge, seems like a simple enough solution.

**Comment by petrsloup** [comment]
Any progress on this?

**Comment by HarelM** [comment]
I don't seem to be getting a response from @zhangyiatmicrosoft and I think the change look good, so let's push it forward.
@CraigglesO can you resolve the conflic please?

**Review by HarelM — APPROVED** [review]

**Pull request merged**
