### PR TITLE
Fix null feature properties in resolve_tokens

### PR DESCRIPTION
**Pull request by mattesCZ**
There is a bug in `resolve_tokens`. When the feature properties are null, the code breaks with `TypeError: Cannot use 'in' operator to search for 'name' in null`. This can easily happen with GeoJSON source, that has some feature with `properties: null`, which is valid value according to GeoJSON specification.

### CODE REVIEW

**Comment by HarelM** [comment]
npm run lint -- --fix.

Can you link to the geojson spec, I think the code assumes in a lot of places that properties: null is not valid...

**Comment by mattesCZ** [comment]
It's described here https://datatracker.ietf.org/doc/html/rfc7946#section-3.2 in the last bullet point. The specification is linked at https://geojson.org/

The command `npm run lint -- --fix` passes, it seems to be some issue with initialization of github checks more than failing some new tests.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Yea, I tried to rerun but it's still failing, I'll try to rerun later tonight maybe.
Can you please add a changelog entry?

**Comment by HarelM** [comment]
Can you merge from main? It's related to node LTS change...

**Comment by mattesCZ** [comment]
Merged, works much better 👌 But somehow one check failed again. It's probably not related to my code changes.

**Review by HarelM — APPROVED** [review]
THANKS!

**Pull request merged**
