### PR TITLE
Remove stale and question and add coverage

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

This is an attempt to add coverage to PR.

### CODE REVIEW

**Comment by HarelM** [comment]
I'm not sure how helpful this is actually...
I mean coverage is a good measure, but this report isn't showing which is covered and how, which will need someone to run this locally and look into it, which beat the purpose.
@birkskyum, @wipfli what do you think?
The rest are important (remove question.md and remove stale.yml) nevertheless...

**Comment by wipfli** [comment]
I find the branch annotations interesting. But if we enable this code coverage, we should also add more tests such that there are no annotations in the pull request...

**Comment by HarelM** [comment]
What do you mean by no annotations?
The code coverage is at around 70% now.
There's a need to improve that, but that won't be overnight...

**Comment by birkskyum** [comment]
I'd also like some more in-depth coverage to really use it, and have a test like this more to guard against regression..

**Comment by wipfli** [comment]
See the "Unchanged files with check annotations" section in the files tab. There are a bunch of annotations which we might want to get rid of before we enable the workflow on code coverage. Otherwise you will always see these annotations in regular pull requests and it might be hard to differentiate them from lint warnings etc...

**Comment by HarelM** [comment]
Ah, thanks! didn't see it earlier.
I'm wondering if this will simply show which files that were changed and not covered, this is a good thing in theory.
Not sure about the worker and actor stuff though...

**Comment by HarelM** [comment]
@wipfli @birkskyum I've removed the annotation - the reason why we saw worker.ts and actor.ts is that it showed the first 50 of 11K.
I've opened a request to show only changed files in the annotation, I hope this will be possible in the future. https://github.com/ArtiomTr/jest-coverage-report-action/issues/308

For now this will add coverage report to every PR, I hope that in time we will improve it.
The goal from my perspective is more than 80% coverage.
It's possible that with the render tests and other tests we have a higher percentage, but it's hard to measure so, unit tests are the key here.

If we get to a higher number of coverage or the above request is implemented we can add back the annotation so that every PR will make sure there are tests covering the added code, but we are not there yet...

**Review by wipfli — APPROVED** [review]
Looks good to me, thanks. You may want to test if the jest-coverage-report-action actually works if someone makes a pull request which breaks a unit test...

**Comment by birkskyum** [comment]
If I run the test-unit-ci locally, it generates this report.json. Is there any way to examine it locally, or does it not make sense to use the test-unit-ci coverage report at all locally?

**Comment by HarelM** [comment]
Yes, remove the `--json` and `--outputFile` from the commandline args to get a report in the console with colors and everything :-)

**Comment by birkskyum** [comment]
Great! It's gonna be very helpful.

**Comment by HarelM** [comment]
BTW, when the following PR will merged we will be able to see missing coverage on changed files in our PRs, much like we do with lint issues, which is a great addition I think:
https://github.com/ArtiomTr/jest-coverage-report-action/pull/306
This will add the automatic check and presentation if there's a test covering the code which was added and I could stop (hopefully) nagging people to add tests to cover the code they added :-)

**Pull request merged**
