### PR TITLE
More tests for sparse tilesets

### PR DESCRIPTION
**Pull request by xabbu42**
Tests for sparse raster tilesets and sparse tilesets with 204 status codes.

I also added some base tests on zoom 0 to show the zoom level where data is available. If this are considered redundant I can revert the last commit.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by xabbu42** [comment]
This tests are intended to check and compare #1586 and #161.

**Comment by HarelM** [comment]
Since you are only adding tests there's no need to change the changelig file...
I'll review this soon

**Comment by HarelM** [comment]
Can you update the fork? Hopefully the tests are now OK.

**Comment by HarelM** [comment]
Do we need the png file next to the mvt file? I'm not sure I've seen this before...

**Comment by xabbu42** [comment]
I can also put the raster tilesets and vector tilesets in separate directories, how should they be called?

**Comment by HarelM** [comment]
Ahh, these are different data input.
I would place them in two different folders: vector and raster.

**Comment by xabbu42** [comment]
I noticed that we already mix raster and vector tiles in the directory above. Should I still move the files in sparse and sparse204? Or is it approved as is?

**Comment by HarelM** [comment]
Both work for me...

**Comment by xabbu42** [comment]
@HarelM What info do you need? I actually wanted to merge the pull request myself just now but now I'm not sure :-).

**Comment by HarelM** [comment]
Your final decision on the folder structure :-)

**Pull request merged**
