### PR TITLE
Make request for ImageSource cancelable

### PR DESCRIPTION
**Pull request by blinkzz**
Added missing cancelation feature for ImageSource, this way any pending request for image will be canceled if updateImage is used, or if source is being removed
This closes [#1798](https://github.com/maplibre/maplibre-gl-js/issues/1798)

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Write tests for all new functionality.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by blinkzz** [comment]
@HarelM 
Isn't it already backported?

https://github.com/maplibre/maplibre-gl-js/blob/3c83a6ba5f2a49fd0d8206ccae482657a0540bbf/src/util/ajax.ts#L318-L332

**Comment by HarelM** [comment]
Yea, this was backported, my mistake.
There is another stuck PR in this repo which I'm not sure what to do with related to image source:
https://github.com/maplibre/maplibre-gl-js/pull/1323
Would be nice if you can take a look at it and let me know if this can be integrated as well as part of this PR since it seems like it's in the same location...

**Comment by blinkzz** [comment]
@HarelM
It looks like solution for #1323 was influenced by fix introduced in mapbox@2.11.0-beta.1 (but we can assume that this is the only viable solution, since it also being used in other source types too)
But i think both this PR and mapbox solutions could be conditional based on if current browser is Safari (using isSafari from src/util/util), to prevent unnecessary image conversions for other browsers and therefore performance drop

**Comment by HarelM** [comment]
Sounds right I guess... We should make sure we don't copy form mapbox though...

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
@blinkzz The code look good, thanks!
Let me know if you would like to push forward the other fix as well, maybe as part of a different PR.

**Comment by blinkzz** [comment]
@HarelM, will have a look on it for sure, but definetly as separate PR

**Comment by HarelM** [comment]
@blinkzz what's missing in order to merge this besides resolving conflicts?

**Review by HarelM — APPROVED** [review]

**Comment by blinkzz** [comment]
@HarelM, this PR is for sure 100% complete, i had no time to check another PR we've discussed above, but it looks good to merge tho without any additional changes

**Pull request merged**
