### PR TITLE
Main docs readme links fixes

### PR DESCRIPTION
**Pull request by HarelM**
I've aligned the group to the original doc's structure and fixed the linked in the main readme.
I also changed the main exported const to be a static class - this is mainly so it would show up in the docs with all the relevant information - I'm not super excited about this change so I'll need a second opinion here.

Added also the build to the CI, although I'm not sure what it actually checks...

### CODE REVIEW

**Comment by HarelM** [comment]
@birkskyum, I have published an initial version of the docs to the following address (using this repo's github pages under the `docs` folder):
https://maplibre.org/maplibre-gl-js/docs/

Feel free to review.
I still need to work on making the CI run as expected, but this shouldn't be an issue.

Any feedback is welcomed.

**Comment by birkskyum** [comment]
Do you have an example of where this static class changes the Docs?

**Comment by HarelM** [comment]
The default.md looks very different if it's not a static class

**Comment by birkskyum** [comment]
I think it all looks good, except the `static`'s which are quite annoying. Does it i.e. make a change to use the `@next` version of the typedoc markdown plugin? It's quite a big update, so it could be.

**Comment by HarelM** [comment]
There's a need to tests and see how it looks I guess...

**Comment by HarelM** [comment]
Generally speaking, these methods are static in nature basically. So it's not "wrong", just weird...

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
