### PR TITLE
Use createImageBitmap when supported

### PR DESCRIPTION
**Pull request by clementgayvallet**
When converting a byte buffer to a [CanvasImageSource](https://developer.mozilla.org/en-US/docs/Web/API/CanvasImageSource), maplibre uses either an [ImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap) if supported or an [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) as fallback.
HTMLImageElement has many flaws, such as [the transparent pixel hack to avoid memory leaks](https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/ajax.ts#L304-L308). Therefore the ImageBitmap seems more reliable and is the preferred image source.

In order to load the byte buffer to an ImageBitmap the library checks if the feature is available on the browser. Currently the function checks if the function createImageBitmap is defined **and** if the  [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) feature is available. 
However the OffscreenCanvas is not required to create an ImageBitmap and on browsers like Firefox where createImageBitmap is supported but not OffscreenCanvas (which is still experimental), the image source falls back on HTMLImageElement.

This PR simply checks for the availability of the createImageBitmap function instead of the unneeded OffscreenCanvas feature.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [x] Suggest a changelog category: "feature".
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog>getImage uses createImageBitmap when supported (#650)</changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
Is this the only place that uses the offscreen camvas check? Can you think why offscreen was checked here?
Also, I think I wrote a function to check for imagebitmap support somewhere...

**Comment by clementgayvallet** [comment]
No, the OffscreenCanvas check is also used in the [raster_dem_tile_source](https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/raster_dem_tile_source.ts#L56) but in this case the check is relevant since the feature is used in the worker.

For the getImage function however, I don't see any reason to check the OffscreenCanvas support here and to be reassured mapbox-gl-js relaxed the check too in this [commit](https://github.com/mapbox/mapbox-gl-js/commit/da4ce5906a2b5c71daa5bb7c826809ae8f6d1969#diff-b8348cacdb48580068674ead1fde22109f850cb349eaabe558308ae1b9e02a58L356).

Regarding the ImageBitmap support check that you wrote, you may be referring to this [commit](https://github.com/maplibre/maplibre-gl-js/commit/086b97fc1b64da2b0fe47cd196066b6b1b223fc4#diff-ba4b3251e17e13bef6af303ecb4b01e6a603367f733b9c6feeaf664a59682f4a). I did not find any other occurrence of createImageBitmap in the code.

**Comment by HarelM** [comment]
Thanks for the clarification, in that case my comments are the following:
1. Move offscreenCanvasSupported into `raster_dem_tile_source` since it is only used there, unless this doesn't feel right to you
2. Remove `offscreen_canvas_supported` file (since it should be empty after 1)
3. do not use `window.` to test for `createImageBitmap` as it might be used from worker where window is not defined.

I got confused with `isImageBitmap` I wrote which is not related to this issue.

Thanks!

**Comment by clementgayvallet** [comment]
1. I'd rather let the offscreenCanvasSupported function in a separate file since the function uses a private variable as cache to prevent the costly context creation I suppose. I find it's cleaner that way.
3. done :)

**Comment by HarelM** [comment]
Thanks!! Can we add some tests to this behavior?

**Comment by clementgayvallet** [comment]
I just tried but it wasn't very convincing. The problem is that it's browser dependent and during unit test the createImageBitmap is not defined. We can mock it with something like `window.createImageBitmap = () => Promise.resolve();` but we have to use window.createImageBitmap in the code too. But even with that I don't think the tests add a real value.

Do you have any idea on how to test this?

**Comment by HarelM** [comment]
You can override `global.create...` in order to mock this, you don't have to use window.
Writing a unit test to make sure the right branch is used in the if is a good unit test I believe.

**Comment by HarelM** [comment]
Change log entry? Please also tic the relevant checkboxes in the pr template to make sure this is not copied etc...

**Review by HarelM — APPROVED** [review]

**Pull request merged**
