### PR TITLE
Debug git history on `test-render` 

### PR DESCRIPTION
**Pull request by wipfli**
`test-render` currently fails for many tests. I would like to see if in the past this was not the case. GitHub makes it easy to change node versions, which is used in the `test-render.yml` workflow to go back to version 10 of node.

My focus is on `debug/overdraw` because it is the first test that fails.

### CODE REVIEW

**Comment by wipfli** [comment]
Great, so `debug/overdraw` passed before typescript and fails now. See https://github.com/maplibre/maplibre-gl-js/pull/365/checks?check_run_id=3644859539.

**Comment by wipfli** [comment]
Before the typescript migration only one render test out of 1200 fails: `debug/tile-overscaled`. See https://github.com/maplibre/maplibre-gl-js/runs/3644885743?check_suite_focus=true.

**Comment by HarelM** [comment]
Failing tests due to usage of `mapbox://` protocol is expected as latest version does not have support for `mapbox://` protocol (I removed it).
I'll share the rest of my thought in #326

**Comment by wipfli** [comment]
To give an example, `debug/overdraw` should look like this (expected.png):

image

However, with the latest version it looks like this (actual.png):

image

**Comment by wipfli** [comment]
> Failing tests due to usage of `mapbox://` protocol is expected

Yes, but only one render test uses it. See https://github.com/maplibre/maplibre-gl-js/issues/326#issuecomment-922462396.

**Comment by HarelM** [comment]
I see your point. Interesting... I saw a report with a lot more failing tests, not sure where I saw it (I think it was #343)...
In any case, we probably need to go over the typescript branch changes and try to find out which changes are causing the test to fail, the problem is that doing it in github is super painful as most of the files are kept closed and there's no good way to open them... :-(
I'm also not sure how to easily find the root cause for failing tests, but we'll need to learn, I guess :-)
I also saw some artifact lines when using safari, which might explain the failing tests. We should take care of this before releasing 2.0 official version.

**Comment by wipfli** [comment]
Here is a way to see all changes between just before migrating to typescript, and where we are now (Split CI):

https://github.com/maplibre/maplibre-gl-js/compare/49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f...37bcaf52b13ce4cad4307521f0a68a80bed801fb

**Comment by HarelM** [comment]
I know, but you can't search there and you need to click on "show diff" like 400 times to see all the file changes content... :-(

**Comment by wipfli** [comment]
To load all diffs to the files changed tab, open the console, and run:

```js
for(i=0; i<document.getElementsByClassName('js-button-text').length; i++){ document.getElementsByClassName('js-button-text')[i].click();}
```

Taken from http://www.antleon.com/2019/12/github-expand-all-collapsed-file-in-pr-diffs/

**Comment by HarelM** [comment]
Nice!! Thanks!

**Comment by wipfli** [comment]
The render test `debug/tile-overscale` is the only one that fails just before the migration to typescript. I wonder if this test always failed or if we introduced some changes that made it fail. For this I now look at `debug/tile-overscale` at the time we first released this library (tag `v1.14.0`).

**Comment by msbarry** [comment]
I tried git-bisect on commits in https://github.com/maplibre/maplibre-gl-js/pull/209/commits on my 2015 macbook pro - it wasn't too helpful since there were large ranges of commits where the render tests weren't runnable, but one thing I found was that if you check out a963b6e7930aae82ac555e9d95165077750bfd89 (about halfway through) then `git checkout a963b6e79 && git checkout main tests && npm ci && npm run build-dev && npm run test-render` then only 13 render tests were failing at that point:

```
* failed text-field/formatted-images-vertical
* failed text-writing-mode/point_label/cjk-arabic-vertical-mode
* failed text-writing-mode/point_label/cjk-horizontal-vertical-mode
* failed text-writing-mode/point_label/cjk-multiline-vertical-horizontal-mode
* failed text-writing-mode/point_label/cjk-punctuation-vertical-mode
* failed text-writing-mode/point_label/cjk-variable-anchors-vertical-horizontal-mode-icon-text-fit
* failed text-writing-mode/point_label/cjk-variable-anchors-vertical-horizontal-mode
* failed text-writing-mode/point_label/cjk-variable-anchors-vertical-mode
* failed text-writing-mode/point_label/cjk-vertical-horizontal-mode
* failed text-writing-mode/point_label/cjk-vertical-mode
* failed text-writing-mode/point_label/mixed-multiline-vertical-horizontal-mode-icon-text-fit
* failed text-writing-mode/point_label/mixed-multiline-vertical-horizontal-mode
* errored video/default
```

(Also, `debug/tile-overscaled` seems to pass for me there, and before the typescript conversion...? Might be some flakiness/inconsistency in CI on that one?)

So the text writing mode test failure was introduced somewhere between cf52cc98e4817117bd9f042c129e84d4d2cc5095...a963b6e7930aae82ac555e9d95165077750bfd89 and the rest between a963b6e7930aae82ac555e9d95165077750bfd89...8d789b70f6ef365d8dc4b67b2a67058459754711

Looking at the failing tests, it definitely seems like we want to fix them before a 2.0 release - sorry I didn't get these render tests up in CI early on, that would have made it easier to fix these during the conversion 😞

**Comment by HarelM** [comment]
The branch was not compiling for some time so this is hard to figure out. If the CI was up and running at that time it would only prevent the merge to main, figuring out what causes the tests to fail would have still been hard, much like now...
You can use the test-render-revert branch to try and see what changes causes the tests to pass. I think I did the obvious reverts, we're probably left with the not so obvious...
Thanks for looking into it! Much appreciated. I need a set of new eyes on this. :-)

**Comment by wipfli** [comment]
I am running the tests now on commit a963b6e which is one of the steps of the typescript migration. Thanks @msbarry for the bisection of the typescript branch.

**Comment by wipfli** [comment]
In CI on macos, the mentioned commit [is failing](https://github.com/maplibre/maplibre-gl-js/pull/365/checks?check_run_id=3699944706). Any idea what is different from your environment @msbarry?

**Comment by wipfli** [comment]
```yml
      matrix:
        ref:
          - f87090b70b8a6fbde1a779c44933ce32bffc5d2c # before fork
          - 49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f # before typescript
```

**Pull request closed without merging**
