### PR TITLE
Restore render test results page

### PR DESCRIPTION
**Pull request by drwestco**
## Launch Checklist

Restoring the test-render results page, requested via the optional `--report` param passed to `npm run test-render`.

e.g., 
image

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [X] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you simplify the reporting into one file some how (instead of two files with eval etc)?

**Comment by drwestco** [comment]
Don't see a way to retry the failing test. This PR doesn't affect the `test-browser` script, so failure should be unrelated.

**Comment by HarelM** [comment]
Just commit something small, seems like an issue with github...

**Comment by HarelM** [comment]
Something is very of with github... My comments are missing too...

**Comment by HarelM** [comment]
Two comments that are missing (I don't know why):
1. Do we care about passing tests in the report? Usually we only care about tests that didn't pass...
2. Change console.log summary to use "`" instead of c style console printing. This wasn't introduce by you, but caught my eye...

**Comment by drwestco** [comment]
Regarding showing passed tests, I can go either way. Right now, as with the old page, if there are any failed tests the passing tests start out hidden.

**Review by HarelM — APPROVED** [review]
Your call regarding passed tests, I never looked at passed tests in any place I worked, and removing the code around them can reduce the code significantly I believe, but feel free to keep it...

**Review by HarelM — APPROVED** [review]

**Pull request merged**
