### PR TITLE
Prepare to update the readme when we release version 2.0.

### PR DESCRIPTION
**Pull request by astridx**
Please check if this is OK for you.

While reading, I noticed that we haven't filled the roadmap for a while. I have entered a few things that I am sure are OK. Is that the case, or should I not change the roadmap?

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by astridx** [comment]
What do you think? Should I change this PR so that we can use it for the 1x version and then add the part for version 2 later?

**Comment by HarelM** [comment]
You mean split this PR and update the readme without the mention of 2.x and only add 2.x later on after we release it? Sure.

**Comment by astridx** [comment]
> You mean split this PR and update the readme without the mention of 2.x and only add 2.x later on after we release it? Sure.

Yes.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Fell free to merge

**Pull request merged**
