### PR TITLE
[Jest] migrate.ts

### PR DESCRIPTION
**Pull request by birkskyum**
Migrate style-spec/migrate.js to Jest

It had an unused test that looped over a non-existing folder of style v7 fixtures, which I removed since we don't have the needed fixtures.

 - [x ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

### CODE REVIEW

**Comment by HarelM** [comment]
Check out the script we created for this purpose that allows easy review.

**Comment by HarelM** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/5e9c746a0ad72b4d22ef3f47c74d8b2a8f0b5c2d/jest-migration.md

**Comment by birkskyum** [comment]
Thanks. This file was rather trivial, but would it still be helpful if I make a new PR?

**Comment by HarelM** [comment]
Yes, yes, otherwise I'll be I pain when reviewing :-)

**Comment by birkskyum** [comment]
Closed in favor of #804

**Pull request closed without merging**
