### PR TITLE
Memory usage in 3d and in general, references #1291

### PR DESCRIPTION
**Pull request by prozessor13**
I took this afternoon to analyze the memory usage of maplibre with/without 3d,

here are the changes/fixes:

* `TerrainSourceCache` had a bug which did not free old tiles, but this had a small footprint, because RTT tiles a very cheap
* `TerrainSourceCache.renderHistorySize` is setted to the value of the corresponding `SourceCache` cache-size, which is related to the screen-size (so mobile-devices with small screen should use less memory)

Bejond that i a played a lot with the ChromeDevTools memory profiles (which is really a great tool), and found out that 9/10 of the memory is eaten by the `TileCache` objects of each of the `map.style.sourceCache` instances. To free all these memory you can call the `reset()` method of the `TileCache` objects, which will dramatically reduces memory. So my conclusion is, that:

* the more sources you have the more cached tiles lies in memory (hundreds)
* ditto for screen-size
* when terrain is enabled, in normal circumstances, this is also an additional source, so see point (1)
* but the memory should not increase to infinity, there should be a upper-limit based on point 1-3

Finally from my perspective the code is working correct!

### CODE REVIEW

**Comment by prozessor13** [comment]
I mean the code is correct with the changes from this PR :)

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
@prozessor13 can you add a changelog entry please?

**Comment by prozessor13** [comment]
@HarelM thx for merge! And I will update the changelog on monday.

**Comment by HarelM** [comment]
I've updated the changelog. Once all the tests pass I'll merge this. Thanks @prozessor13!

**Pull request merged**
