### PR TITLE
Fix circular dependencies in the validation module for the style spec

### PR DESCRIPTION
**Pull request by VehpuS**
## Launch Checklist

Starting this PR to report on progress fixing https://github.com/maplibre/maplibre-gl-js/issues/1896. I managed to fix one source of circular imports by adding the validation function as an argument for the inner functions it calls, avoiding imports which caused this issue, and frankly replicating the way other validation functions were passed down.

This is still a WIP - there are a few remaining circular imports which I'll look into next:
```
src/style-spec/expression/parsing_context.ts -> src/style-spec/expression/compound_expression.ts -> src/style-spec/expression/parsing_context.ts
src/data/bucket/symbol_bucket.ts -> src/symbol/symbol_layout.ts -> src/data/bucket/symbol_bucket.ts
src/style/style_layer/symbol_style_layer.ts -> src/data/bucket/symbol_bucket.ts -> src/symbol/symbol_layout.ts -> src/style/style_layer/symbol_style_layer.ts
...and 3 more
```

Tests are passing but I need to run some manual tests to confirm nothing funky is happening before merging :P

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Manually test the debug page.

### CODE REVIEW

**Comment by HarelM** [comment]
Note that this is a big task to take.
I would consider the following:
1. Don't do everything in a single PR, but rather split the work into as small PRs as possible, even if nothing is solved in a single PR, it will be easier to review.
2. Try and present some diagram of the current problem and the proposed solution so that design wise it is approved before doing a lot of coding that might end up in the wrong direction.

Thanks for looking into it!!

**Comment by VehpuS** [comment]
> Note that this is a big task to take. I would consider the following:
> 
> 1. Don't do everything in a single PR, but rather split the work into as small PRs as possible, even if nothing is solved in a single PR, it will be easier to review.
> 2. Try and present some diagram of the current problem and the proposed solution so that design wise it is approved before doing a lot of coding that might end up in the wrong direction.
> 
> Thanks for looking into it!!

In that case I'll avoid fixing the rest of the circular imports in this PR and focus on clarifying  what I've done. I was thinking this might be a better approach anyway (which is why I opened the PR - in order to allow a more methodical review).

**Comment by HarelM** [comment]
Overall this looks great, I would consider making sure the style-spec validation scripts are still functional and working as expected after all these changes.
There are a lot of missing typescript types here, but this might be a different PR...

**Comment by VehpuS** [comment]
> Overall this looks great, I would consider making sure the style-spec validation scripts are still functional and working as expected after all these changes. There are a lot of missing typescript types here, but this might be a different PR...

The style-spec validation scripts don't run in the CI / jest tests? I'll check them again anyway.

With regards to typescript types - if there's something you think is worth addressing, I'll happily do it. I already included updates to existing types of course.

**Comment by VehpuS** [comment]
> Note that this is a big task to take. I would consider the following:
> 
> 1. Don't do everything in a single PR, but rather split the work into as small PRs as possible, even if nothing is solved in a single PR, it will be easier to review.
> 2. Try and present some diagram of the current problem and the proposed solution so that design wise it is approved before doing a lot of coding that might end up in the wrong direction.
> 
> Thanks for looking into it!!

With regards to diagramming, I'm not sure how to practically visualize it, but basically I replicated an existing solution that was already implemented for recursive styles - pass the validator in all "entry point" validation functions as an argument down the validation "tree", so that instead of importing in submodules (complex types such as arrays), a reference to tthe top validator instance is passed down the validation line.

Entry points:
- `src/style-spec/validate_style.min.ts`: https://github.com/maplibre/maplibre-gl-js/pull/1946/commits/7f3c9acfe2d4445c5a26423188a3d450289d9713#diff-84adc6011b637335628c12b8a719a863d6acc01296789c5d910094d635dcd92fR70
- `src/style-spec/validate/validate.ts`: https://github.com/maplibre/maplibre-gl-js/pull/1946/commits/7f3c9acfe2d4445c5a26423188a3d450289d9713#diff-5f422f90dc7709b4011a86c17e1e6c6f4d089c3ee0a288c5b02d01fb9493cfb5R63

Padding and terrain tests had to be fixed to account for the fact they are truly "unit" tests - calling the underlying validation logic directly, so they also "inject" the top validator manually.
- `src/style-spec/validate/validate_padding.test.ts`: https://github.com/maplibre/maplibre-gl-js/pull/1946/commits/7f3c9acfe2d4445c5a26423188a3d450289d9713#diff-7e33a6adc91e04aaa3c33c641385835e654502cbd86a0c285c4d0c4f47000a4f
- `src/style-spec/validate/validate_terrain.test.ts`: https://github.com/maplibre/maplibre-gl-js/pull/1946/commits/7f3c9acfe2d4445c5a26423188a3d450289d9713#diff-d045124d45bb6c201f9f8267a474e6a5d89664f01755887f60f56f7d3e5736cc

The rest of the changes are simply replacing the actual circular imports by accessing the passed instance instead, i.e. https://github.com/maplibre/maplibre-gl-js/pull/1946/commits/7f3c9acfe2d4445c5a26423188a3d450289d9713#diff-d045124d45bb6c201f9f8267a474e6a5d89664f01755887f60f56f7d3e5736cc

Let me know if further explanations are necessary and I'll happily provide them :).

**Review by HarelM — APPROVED** [review]
Please let me know that style-spec execution scripts are passing, this is not part of the CI unfortunately @rotu is looking into adding it to the CI I think.
If this is running as expected I'll merge this.
THANKS!!

**Comment by VehpuS** [comment]
The debug pages show no issues I could see and `npm run codegen` ran successfully (which I believe covers all the style scripts, but let me know if not).

**Comment by HarelM** [comment]
I mean running the style-spec command-line tool.

**Comment by VehpuS** [comment]
> 

How do I run it? I don't see a style-spec script in `./node_modules/.bin/`. The NPM scripts that seem to be relevant are the ones run by `npm run codegen`.

**Comment by HarelM** [comment]
Codegen runs code generation.
There are scripts in the bin folder under the stylespec folder with scripts that can run on a style json file and validate them, or migrate them.
Try running those, they are not covered by the tests unfortunately...

**Comment by VehpuS** [comment]
> Codegen runs code generation. There are scripts in the bin folder under the stylespec folder with scripts that can run on a style json file and validate them, or migrate them. Try running those, they are not covered by the tests unfortunately...

They're running the mapbox validator. Should I replace it with maplibre's?

After running `chmod -R 775 ./src/style-spec/bin/*`, I ran the validation like this: `for input in $(ls test/integration/style-spec/tests/*.input.json); do echo $input; ./src/style-spec/bin/gl-style-validate.js $input; echo ------; done`.

**Comment by VehpuS** [comment]
> 

```
test/integration/style-spec/tests/bad-color.input.json
test/integration/style-spec/tests/bad-color.input.json:16: layers[0].paint.fill-color: color expected, array found
test/integration/style-spec/tests/bad-color.input.json:17: layers[0].paint.fill-outline-color: color expected, "not a color" found
test/integration/style-spec/tests/bad-color.input.json:26: layers[1].paint.fill-outline-color: color expected, array found
------
test/integration/style-spec/tests/constants.input.json
test/integration/style-spec/tests/constants.input.json:9: constants: constants have been deprecated as of v8
test/integration/style-spec/tests/constants.input.json:28: layers[1].paint.fill-color: color expected, array found
------
test/integration/style-spec/tests/extrakeys.input.json
------
test/integration/style-spec/tests/filters.input.json
test/integration/style-spec/tests/filters.input.json:15: layers[0].filter: array expected, object found
test/integration/style-spec/tests/filters.input.json:22: layers[1].filter: filter array must have at least 1 element
test/integration/style-spec/tests/filters.input.json:29: layers[2].filter[0]: Unknown expression "=". If you wanted a literal array, use ["literal", [...]].
test/integration/style-spec/tests/filters.input.json:40: layers[3].filter: Expected two or three arguments.
test/integration/style-spec/tests/filters.input.json:47: layers[4].filter: Expected two or three arguments.
test/integration/style-spec/tests/filters.input.json:59: layers[5].filter[1]: string expected, number found
test/integration/style-spec/tests/filters.input.json:68: layers[6].filter[2]: Expected an array with at least one element. If you wanted a literal array, use ["literal", []].
test/integration/style-spec/tests/filters.input.json:82: layers[7].filter[2]: expected one of [Point, LineString, Polygon], "value" found
test/integration/style-spec/tests/filters.input.json:90: layers[8].filter: "$type" cannot be use with operator ">"
test/integration/style-spec/tests/filters.input.json:93: layers[8].filter[2]: expected one of [Point, LineString, Polygon], "value" found
test/integration/style-spec/tests/filters.input.json:103: layers[9].filter[1]: filter array must have at least 1 element
test/integration/style-spec/tests/filters.input.json:131: layers[12].filter[2]: Expected object but found string instead.
test/integration/style-spec/tests/filters.input.json:142: layers[13].filter[1]: Bare objects invalid. Use ["literal", {...}] instead.
test/integration/style-spec/tests/filters.input.json:152: layers[14].filter[2][1]: string expected, array found
test/integration/style-spec/tests/filters.input.json:159: layers[15].filter: "feature-state" data expressions are not supported with filters.
------
test/integration/style-spec/tests/functions.input.json
test/integration/style-spec/tests/functions.input.json:17: layers[0].paint.line-width.base: number expected, string found
test/integration/style-spec/tests/functions.input.json:18: layers[0].paint.line-width.stops: array must have at least one stop
test/integration/style-spec/tests/functions.input.json:28: layers[1].paint.line-width: missing required property "stops"
test/integration/style-spec/tests/functions.input.json:39: layers[2].paint.line-width.stops: array must have at least one stop
test/integration/style-spec/tests/functions.input.json:50: layers[3].paint.line-width.stops: array expected, object found
test/integration/style-spec/tests/functions.input.json:62: layers[4].paint.line-width.stops[0]: array expected, string found
test/integration/style-spec/tests/functions.input.json:75: layers[5].paint.line-width.stops[0]: array length 2 expected, length 0 found
test/integration/style-spec/tests/functions.input.json:89: layers[6].paint.line-dasharray.stops[0][0]: number expected, string found
test/integration/style-spec/tests/functions.input.json:106: layers[7].paint.line-width.stops[0][1]: number expected, string found
test/integration/style-spec/tests/functions.input.json:125: layers[8].paint.line-width.stops[1][0]: stop domain values must appear in ascending order
test/integration/style-spec/tests/functions.input.json:139: layers[9].paint.fill-translate[0]: number expected, object found
test/integration/style-spec/tests/functions.input.json:152: layers[9].paint.fill-translate[1]: number expected, object found
test/integration/style-spec/tests/functions.input.json:227: layers[12].paint.fill-color.stops[1]: object expected, number found
test/integration/style-spec/tests/functions.input.json:244: layers[13].paint.fill-color.stops[0]: object stop key must have zoom
test/integration/style-spec/tests/functions.input.json:263: layers[14].paint.fill-color.stops[0]: object stop key must have value
test/integration/style-spec/tests/functions.input.json:284: layers[15].paint.fill-color.stops[0][0].zoom: number expected, string found
test/integration/style-spec/tests/functions.input.json:305: layers[16].paint.fill-color.stops[0][0].value: stop domain value must be a number, string, or boolean
test/integration/style-spec/tests/functions.input.json:324: layers[17].paint.fill-color.stops[0][0]: number expected, string found
If you intended to use a categorical function, specify `"type": "categorical"`.
test/integration/style-spec/tests/functions.input.json:341: layers[18].paint.fill-color.stops[0][0]: number expected, string found
If you intended to use a categorical function, specify `"type": "categorical"`.
test/integration/style-spec/tests/functions.input.json:354: layers[19].paint.fill-color: "property" property is required
test/integration/style-spec/tests/functions.input.json:401: layers[22].paint.fill-color: missing required property "property"
test/integration/style-spec/tests/functions.input.json:415: layers[23].paint.fill-color.stops: identity function may not have a "stops" property
test/integration/style-spec/tests/functions.input.json:434: layers[24].paint.fill-color.stops[1][0]: number stop domain type must match previous stop domain type string
test/integration/style-spec/tests/functions.input.json:456: layers[25].paint.fill-color.stops[1][0].value: number stop domain type must match previous stop domain type string
test/integration/style-spec/tests/functions.input.json:474: layers[26].paint.fill-color.stops[0][0]: number expected, string found
test/integration/style-spec/tests/functions.input.json:492: layers[27].paint.fill-color.stops[0][0].value: number expected, string found
test/integration/style-spec/tests/functions.input.json:510: layers[28].paint.fill-color.stops[0][0]: number expected, string found
test/integration/style-spec/tests/functions.input.json:528: layers[29].paint.fill-color.stops[0][0].value: number expected, string found
test/integration/style-spec/tests/functions.input.json:564: layers[31].paint.fill-color.stops[0][0]: stop domain value must be a number, string, or boolean
test/integration/style-spec/tests/functions.input.json:581: layers[32].paint.fill-color.stops[0][0]: stop domain value must be a number, string, or boolean
test/integration/style-spec/tests/functions.input.json:595: layers[33].paint.fill-antialias: exponential functions not supported
test/integration/style-spec/tests/functions.input.json:616: layers[34].paint.fill-antialias: "property" property is required
test/integration/style-spec/tests/functions.input.json:621: layers[34].paint.fill-antialias.stops[0][0].value: number expected, string found
test/integration/style-spec/tests/functions.input.json:648: layers[35].paint.fill-opacity.stops[2][0]: stop domain values must be unique
test/integration/style-spec/tests/functions.input.json:666: layers[36].paint.fill-opacity.stops[0][0]: integer expected, found 0.33
test/integration/style-spec/tests/functions.input.json:692: layers[37].paint.fill-opacity.stops[1][0].value: stop domain values must appear in ascending order
test/integration/style-spec/tests/functions.input.json:718: layers[38].paint.fill-opacity.stops[1]: stop zoom values must appear in ascending order
test/integration/style-spec/tests/functions.input.json:754: layers[39].paint.fill-opacity.stops[2][0].value: stop domain values must be unique
test/integration/style-spec/tests/functions.input.json:826: layers[42].paint.fill-opacity.default: number expected, string found
test/integration/style-spec/tests/functions.input.json:839: layers[43].paint.fill-color.default: color expected, "invalid" found
test/integration/style-spec/tests/functions.input.json:857: layers[44].paint.fill-opacity.stops[1][0]: stop domain values must appear in ascending order
test/integration/style-spec/tests/functions.input.json:898: layers[47].paint.fill-color: Expected color but found number instead.
test/integration/style-spec/tests/functions.input.json:907: layers[48].paint.fill-color[2]: Expected number but found string instead.
test/integration/style-spec/tests/functions.input.json:916: layers[49].paint.fill-opacity: "zoom" expression may only be used as input to a top-level "step" or "interpolate" expression.
test/integration/style-spec/tests/functions.input.json:925: layers[50].layout.visibility: expected one of [visible, none], ["literal",true] found
test/integration/style-spec/tests/functions.input.json:934: layers[51].paint.fill-extrusion-opacity: data expressions not supported
test/integration/style-spec/tests/functions.input.json:943: layers[52].paint.line-dasharray: Type array<number> is not interpolatable.
test/integration/style-spec/tests/functions.input.json:952: layers[53].paint.heatmap-color: zoom expressions not supported
test/integration/style-spec/tests/functions.input.json:960: layers[54].paint.heatmap-color: zoom functions not supported
test/integration/style-spec/tests/functions.input.json:968: layers[55].layout.line-join: "feature-state" data expressions are not supported with layout properties.
test/integration/style-spec/tests/functions.input.json:981: layers[56].paint.line-width.stops[0][1]: expressions are not allowed in function stops.
------
test/integration/style-spec/tests/layers.input.json
test/integration/style-spec/tests/layers.input.json:23: layers[0]: either "type" or "ref" is required
test/integration/style-spec/tests/layers.input.json:28: layers[1]: missing required property "id"
test/integration/style-spec/tests/layers.input.json:42: layers[3]: "type" is prohibited for ref layers
test/integration/style-spec/tests/layers.input.json:43: layers[3]: "source" is prohibited for ref layers
test/integration/style-spec/tests/layers.input.json:44: layers[3]: "source-layer" is prohibited for ref layers
test/integration/style-spec/tests/layers.input.json:45: layers[3]: "filter" is prohibited for ref layers
test/integration/style-spec/tests/layers.input.json:46: layers[3]: "layout" is prohibited for ref layers
test/integration/style-spec/tests/layers.input.json:50: layers[4]: ref layer "not-found" not found
test/integration/style-spec/tests/layers.input.json:54: layers[5]: ref cannot reference another ref layer
test/integration/style-spec/tests/layers.input.json:56: layers[6]: missing required property "source"
test/integration/style-spec/tests/layers.input.json:63: layers[7]: source "not-found" not found
test/integration/style-spec/tests/layers.input.json:68: layers[8]: layer "vector-raster-mismatch" requires a vector source
test/integration/style-spec/tests/layers.input.json:73: layers[9]: layer "raster-vector-mismatch" requires a raster source
test/integration/style-spec/tests/layers.input.json:83: layers[11]: duplicate layer id "duplicate", previously used at line 77
test/integration/style-spec/tests/layers.input.json:90: layers[12].type: expected one of [fill, line, symbol, circle, heatmap, fill-extrusion, raster, hillshade, background], "invalid" found
test/integration/style-spec/tests/layers.input.json:100: layers[13]: layer "missing-source-layer" must specify a "source-layer"
test/integration/style-spec/tests/layers.input.json:112: layers[15]: layer "line-gradient-bad" specifies a line-gradient, which requires a GeoJSON source with `lineMetrics` enabled.
test/integration/style-spec/tests/layers.input.json:126: layers[16]: layer "line-gradient-missing-lineMetrics" specifies a line-gradient, which requires a GeoJSON source with `lineMetrics` enabled.
------
test/integration/style-spec/tests/light-arbitrary.input.json
test/integration/style-spec/tests/light-arbitrary.input.json:14: foo: unknown property "foo"
------
test/integration/style-spec/tests/light.input.json
test/integration/style-spec/tests/light.input.json:10: anchor: expected one of [map, viewport], true found
test/integration/style-spec/tests/light.input.json:11: position: array length 3 expected, length 2 found
test/integration/style-spec/tests/light.input.json:12: color: color expected, array found
test/integration/style-spec/tests/light.input.json:13: intensity: 1.5 is greater than the maximum value 1
------
test/integration/style-spec/tests/malformed-glyphs-type.input.json
test/integration/style-spec/tests/malformed-glyphs-type.input.json:3: glyphs: string expected, boolean found
------
test/integration/style-spec/tests/malformed-glyphs.input.json
test/integration/style-spec/tests/malformed-glyphs.input.json:3: glyphs: "glyphs" url must include a "{fontstack}" token
test/integration/style-spec/tests/malformed-glyphs.input.json:3: glyphs: "glyphs" url must include a "{range}" token
------
test/integration/style-spec/tests/many-sources.input.json
------
test/integration/style-spec/tests/map-properties.input.json
------
test/integration/style-spec/tests/metadata.input.json
test/integration/style-spec/tests/metadata.input.json:10: constants: constants have been deprecated as of v8
------
test/integration/style-spec/tests/missing-glyphs.input.json
test/integration/style-spec/tests/missing-glyphs.input.json:17: layers[0].layout.text-field: use of "text-field" requires a style "glyphs" property
------
test/integration/style-spec/tests/no-sources.input.json
test/integration/style-spec/tests/no-sources.input.json:1: missing required property "sources"
test/integration/style-spec/tests/no-sources.input.json:7: layers[0]: source "raster" not found
------
test/integration/style-spec/tests/non-mapbox-references.input.json
------
test/integration/style-spec/tests/numbers.input.json
test/integration/style-spec/tests/numbers.input.json:42: layers[2].paint.circle-radius: -1 is less than the minimum value 0
test/integration/style-spec/tests/numbers.input.json:NaN: layers[3].paint.circle-radius: number expected, null found
test/integration/style-spec/tests/numbers.input.json:58: layers[4].paint.circle-radius: missing required property "stops"
test/integration/style-spec/tests/numbers.input.json:66: layers[5].paint.circle-radius: number expected, array found
test/integration/style-spec/tests/numbers.input.json:74: layers[6].paint.circle-radius: number expected, boolean found
------
test/integration/style-spec/tests/pitch.input.json
test/integration/style-spec/tests/pitch.input.json:3: pitch: number expected, string found
------
test/integration/style-spec/tests/properties.input.json
test/integration/style-spec/tests/properties.input.json:16: layers[0].paint.fill-opacity: -1 is less than the minimum value 0
test/integration/style-spec/tests/properties.input.json:19: layers[0].paint.fill-opacity-transition.delay: -1 is less than the minimum value 0
test/integration/style-spec/tests/properties.input.json:20: layers[0].paint.fill-opacity-transition: unknown property "bad"
test/integration/style-spec/tests/properties.input.json:22: layers[0].paint.bad-transition: unknown property "bad-transition"
test/integration/style-spec/tests/properties.input.json:25: layers[0].paint.fill-antialias-transition: unknown property "fill-antialias-transition"
test/integration/style-spec/tests/properties.input.json:36: layers[1].paint.fill-opacity: 1.5 is greater than the maximum value 1
test/integration/style-spec/tests/properties.input.json:NaN: layers[2].paint.fill-opacity: number expected, null found
test/integration/style-spec/tests/properties.input.json:56: layers[3].paint.fill-opacity: unknown property "foo"
test/integration/style-spec/tests/properties.input.json:62: layers[3].paint.fill-color.stops[1][0]: unknown property "magic"
test/integration/style-spec/tests/properties.input.json:65: layers[3].paint.bad: unknown property "bad"
test/integration/style-spec/tests/properties.input.json:74: layers[4].paint.fill-opacity: "fill-opacity" does not support interpolation syntax
Use an identity property function instead: `{ "type": "identity", "property": "opacity" }`.
------
test/integration/style-spec/tests/required.input.json
test/integration/style-spec/tests/required.input.json:1: missing required property "version"
test/integration/style-spec/tests/required.input.json:1: missing required property "sources"
test/integration/style-spec/tests/required.input.json:1: missing required property "layers"
------
test/integration/style-spec/tests/root-properties.input.json
test/integration/style-spec/tests/root-properties.input.json:2: version: expected one of [8], 1 found
test/integration/style-spec/tests/root-properties.input.json:3: constants: constants have been deprecated as of v8
test/integration/style-spec/tests/root-properties.input.json:4: sources: object expected, array found
test/integration/style-spec/tests/root-properties.input.json:5: layers: array expected, object found
test/integration/style-spec/tests/root-properties.input.json:11: light: object expected, boolean found
------
test/integration/style-spec/tests/sources.input.json
test/integration/style-spec/tests/sources.input.json:4: sources.missing-type: "type" is required
test/integration/style-spec/tests/sources.input.json:7: sources.invalid-type.type: expected one of [vector, raster, raster-dem, geojson, video, image], "invalid" found
test/integration/style-spec/tests/sources.input.json:26: sources.video-missing-coordinates: missing required property "coordinates"
test/integration/style-spec/tests/sources.input.json:34: sources.video-wrong-coordinates.coordinates[0]: array expected, number found
test/integration/style-spec/tests/sources.input.json:34: sources.video-wrong-coordinates.coordinates[1]: array expected, string found
test/integration/style-spec/tests/sources.input.json:34: sources.video-wrong-coordinates.coordinates[2][1]: number expected, string found
test/integration/style-spec/tests/sources.input.json:34: sources.video-wrong-coordinates.coordinates[3]: array length 2 expected, length 0 found
test/integration/style-spec/tests/sources.input.json:NaN: sources.canvas: Please use runtime APIs to add canvas sources, rather than including them in stylesheets.
test/integration/style-spec/tests/sources.input.json:49: sources.cluster-properties.zoom.map: "zoom" and "feature-state" expressions are not supported with cluster properties.
test/integration/style-spec/tests/sources.input.json:50: sources.cluster-properties.state.map: "zoom" and "feature-state" expressions are not supported with cluster properties.
------
test/integration/style-spec/tests/style-api.input.json
------
test/integration/style-spec/tests/terrain.input.json
test/integration/style-spec/tests/terrain.input.json:13: source: string expected, number found
test/integration/style-spec/tests/terrain.input.json:14: exaggeration: number expected, string found
------
test/integration/style-spec/tests/text-field-format.input.json
test/integration/style-spec/tests/text-field-format.input.json:42: layers[1].layout.text-field: First argument must be an image or text section.
test/integration/style-spec/tests/text-field-format.input.json:53: layers[2].layout.text-field: Expected at least one argument.
test/integration/style-spec/tests/text-field-format.input.json:99: layers[6].layout.text-field[1]: Expected number but found string instead.
test/integration/style-spec/tests/text-field-format.input.json:111: layers[7].layout.text-field[1][0]: Unknown expression "Helvetica". If you wanted a literal array, use ["literal", [...]].
test/integration/style-spec/tests/text-field-format.input.json:147: layers[10].layout.text-field[1]: Expected array<string> but found number instead.
------
test/integration/style-spec/tests/text-font.input.json
test/integration/style-spec/tests/text-font.input.json:57: layers[4].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:67: layers[5].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:77: layers[6].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:87: layers[7].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:97: layers[8].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:107: layers[9].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:117: layers[10].layout.text-font: Invalid data expression for "text-font". Output values must be contained as literals within the expression.
test/integration/style-spec/tests/text-font.input.json:127: layers[11].layout.text-font: "text-font" does not support identity functions
------
test/integration/style-spec/tests/unknown-keys-nested.input.json
------
```

**Comment by VehpuS** [comment]
I now confirmed that no changes in output occurred by running a changed version of the script, then `git diff`:

```
for input in $(ls test/integration/style-spec/tests/*.input.json); \
do echo $input; \
./src/style-spec/bin/gl-style-validate.js $input --json > ${input[0,-11]}output.json; \
echo ------; \
done
```

**Comment by HarelM** [comment]
THANKS!!!

**Pull request merged**
