### PR TITLE
[Jest] Browser tests

### PR DESCRIPTION
**Pull request by birkskyum**
browser.test.js was used to generate before each and after each for drag.test.js and zoom.test.js. I combined them all in browser.test.ts, as it's much easier to reason about.

Change jest.config.cjs to:

```
  "roots": [
    "<rootDir>/src",
    "<rootDir>/test/browser",
  ],
```

Run

`npm install`
`npm run test-jest -- test/browser/browser`

### CODE REVIEW

**Comment by birkskyum** [comment]
The tests fail because "map" is undefined. Both the drag and zoom test load html file test/browser/fixtures/land.html where it's defined, but map doesn't seem to be passed to  the local scope of the jest tests.

**Comment by HarelM** [comment]
I would focus on finish migrating the rest of the unit tests as these tests are more integration tests...?

**Comment by birkskyum** [comment]
The end seems to be near. I believe the ajax.test.ts is ready to be merged, and I did what I could on the image_source, which are the only two places tap is used apart from the browser tests.

**Comment by HarelM** [comment]
I had no clue we were finishing up with the unit tests, so cool!! :-)
Also I think the build tests are easier, so we might want to do them first.
I'll take a look at this later this week and see if I can help with the problem at hand.

**Comment by birkskyum** [comment]
I'll have a go at the build tests then

**Comment by HarelM** [comment]
I've reviewed the changes.
Looks good in general.
It still needs to pass though :-)
Thanks for all the hard work!

**Comment by wipfli** [comment]
I am re-running the tests. Double-click often fails for no good reason.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
