### PR TITLE
[Typescript] Remove the usage of devicePixelRatio as a getter from browser.ts

### LINKED ISSUE #265: [Typescript] Remove the usage of `devicePixelRatio` as a getter from browser.ts
Remove the usage of `devicePixelRatio` as a getter from browser.ts as it is not needed and it can be used as a global variable as it is a property on `window` anyway...

### PR DESCRIPTION
**Pull request by fredj**
fixes #265

### CODE REVIEW

**Comment by fredj** [comment]
`test-unit` is working locally, any idea how to make it pass on github actions?

**Comment by HarelM** [comment]
I've reran the tests and they still fail, so it might be a real issue. Try cloning to a clean location and running it there...

Also note that `window` might not be defined in worker running context, this implementation here might be problematic...?

**Comment by fredj** [comment]
@HarelM I've removed the `window.` in the code and it works, thanks for the hint !

**Comment by HarelM** [comment]
I think this is good.
The only concern I have I about readability - I.e. When reading this code there no good way to know that this is a globally defined value.
Having said that, I'm not sure there's a better way to address this.
I you feel comfortable with this I'll merge it.
@wipfli what do you think?

**Comment by wipfli** [comment]
Looks good to me.

**Pull request merged**
