### PR TITLE
[Jest] Migrate Attribution.js

### PR DESCRIPTION
**Pull request by astridx**
A new attempt. 
This is a draft. I want to see if the CI is successfully passed. 

I will take a closer look at this in the next few days.

### CODE REVIEW

**Comment by astridx** [comment]
I have taken a closer look at the attribution control and my [comment ](https://github.com/maplibre/maplibre-gl-js/pull/583#issuecomment-957322187)is correct:

Because we always start the source ID with 1 in the tests, it repeats itself in every test.  

For example https://github.com/maplibre/maplibre-gl-js/blob/d668369ac5b92e39cc098c3e08fabc98d7cca368/test/unit/ui/control/attribution.js#L106
and 
https://github.com/maplibre/maplibre-gl-js/blob/d668369ac5b92e39cc098c3e08fabc98d7cca368/test/unit/ui/control/attribution.js#L138


Because we do not reinitialise the map, one test has an influence on the subsequent tests since this commit: https://github.com/maplibre/maplibre-gl-js/commit/476ce360b6f27b0abae7a8db1c9dde6bb8629264#


In the file `src/style/style.js` we put the `source `in the variable `sourcesUsedBefore `and later fire a new `"data"` event with `sourceDataType: 'visibility'` when the map is reinitialised. If we do not reload the map, the source has already been used and the event is not fired. 

Also, our CI causes problems if we don't reinitialise the map in every test.

So I addes [this changes](https://github.com/maplibre/maplibre-gl-js/pull/646/commits/0640a6f9d3e826d24efe73b972bd5c75d705a36a) to the ["normal" manuell changes](https://github.com/maplibre/maplibre-gl-js/pull/646/commits/207f1cb5e4ff4ffda81453c250800f70f3b5d86c).

**So this is ready for review now.**

**Comment by HarelM** [comment]
LGTM, can you add a test for the following bug that you solved: #640

**Comment by astridx** [comment]
Yes, I thought about this, too. I would add it as inline-snapshot test. Would this be fine?

**Comment by HarelM** [comment]
Sure, as long as we add a test for every bug we fix I'm good :-)

**Pull request merged**
