### PR TITLE
Add a script to watch run tests in watch mode for a specific folder

### PR DESCRIPTION
**Pull request by VehpuS**
While I was refactoring some code I was looking for a script to watch specific subfolders while developing to make the test runs fast enough to aid in test driven development. Since I could not find an implemented script - I added one myself, and thought others may find this useful too.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by HarelM** [comment]
This is great, can you update the relevant readme.md file with this addition?

**Comment by VehpuS** [comment]
> This is great, can you update the relevant readme.md file with this addition?

I'm not sure which README.md file you mean 😅

**Comment by VehpuS** [comment]
> > This is great, can you update the relevant readme.md file with this addition?
> 
> I'm not sure which README.md file you mean 😅

Do you mean a section in CONTRIBUTING.md?

**Comment by HarelM** [comment]
No, there are a few readme file scattered in interesting places. Find the one talking about the jest unit tests.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
