### PR TITLE
Update CHANGELOG.md with node upgrade

### PR DESCRIPTION
**Pull request by HarelM**
In continue to #3452, where I forgot to add this...

### CODE REVIEW

**Review by louwers — COMMENTED** [review]
Not really relevant for end-users?

**Comment by HarelM** [comment]
No, more for developers and for me to know when things changed so I can backtrack issues without looking at the git history which is filled with dependencies updates.

**Comment by HarelM** [comment]
@louwers let me know if you want me to remove this changelog comment or not, I don't have strong feelings either way.

**Review by louwers — APPROVED** [review]
Ah OK, sure. Maybe a new category for this makes sense, since probably a lot more users that are not developers read the changelog?

**Pull request merged**
