### PR TITLE
Exposed the DOM util class to the public

### PR DESCRIPTION
**Pull request by TheSpartaPT**
Very small change that only exposes the DOM util class to the public. This will be useful for people wanting to make custom controls, and will allow them to use the same DOM manipulation util class as the bundled controls.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
I'm sure there are better DOM utilities packages in npm, I'm not sure this is the best one or there.
But if this is to be exposed, every public method should be documented using tsdocs comments.

**Comment by HarelM** [comment]
I've looked through the file, I don't think it will be a good candidate for a public API kinf if class...

**Comment by TheSpartaPT** [comment]
yeah, there probably are better, more in-depth libraries that only focus on dom manipulation, but the idea here was to be able to use the same utils maplibre is using for custom controls and such

**Comment by HarelM** [comment]
Should we close this PR?
The alternative is to really invest in the DOM utils class to have it publicly, meaning good docs, well though of API, etc.
This is currently not the case with this PR.
Please decide which direction you would like to go.

**Pull request closed without merging**
