### PR TITLE
Migrate query tests from puppeteer to playwright

### PR DESCRIPTION
**Pull request by birkskyum**
We currently use both selenium and puppeteer, for the following reasons:

- selenium offers cross-browser support
- puppeteer is maintained by chrome team and doesn't need to run an additional server, and is much more ergonomical.

Fortunately, playwright is an evolution after puppeteer (and made by main puppeteer devs) almost with same api, and with cross-browser support. 

I think we'll be better off just using playwright throughout, as it works well with jest as test runner, so this pr ports the query tests.

### CODE REVIEW

**Comment by HarelM** [comment]
I think cypress is currently the market leader in terms of UI tests. Why not use it?
npm trends are very helpful to see that easily I guess.
Having said that, the changes are minimal so removing puppeteer and adding playright is a good change in that aspect.
Can we remove puppeteer as part of this RP?

**Comment by birkskyum** [comment]
Puppeteer is still used in benchmarks, and I can have a look at replacing it there as well.

Cypress is great, having this nice gui etc., but it requires a 100% opt-in to their test-runner, folder structure etc., so it's a bit bigger operation that we might want still. Playwright is more modular, allowing us to just use the browser emulation in this case, while keeping jest as the test-runner.

**Review by HarelM — APPROVED** [review]

**Comment by birkskyum** [comment]
@HarelM , I removed puppeteer as well in new commit

**Comment by HarelM** [comment]
Since benchmarks are not part of the CI you'll need to make sure they run locally by manually running them.
Otherwise this is approved. Thanks!

**Review by HarelM — APPROVED** [review]

**Review by HarelM — APPROVED** [review]

**Pull request merged**
