### PR TITLE
Rollback to mapbox gl draw example

### PR DESCRIPTION
**Pull request by birkskyum**
I think it's best to roll back this for now. I learned a ton about the library in the process of migrating, and want to reconsider the approach taken.

This mapbox gl draw examples still has it's turf.js dependency upgraded compared to before.

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by andrewharvey** [comment]
as I realised in #37 mapbox-gl-draw is not fully compatible with maplibre-gl-js and as it stands the current example at https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-draw/ is incredibly confusing because the description says its using your project but the actual example is not.

**Comment by HarelM** [comment]
Yeah, I asked @birkskyum to revert the description, sorry for that...

**Comment by andrewharvey** [comment]
No worries. I'll make a new PR.

**Comment by andrewharvey** [comment]
-> #5393

**Pull request merged**
