### PR TITLE
Fix renderWorldCopies regression

### PR DESCRIPTION
**Pull request by NathanMOlson**
This fixes #5024.

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.

### CODE REVIEW

**Comment by birkskyum** [comment]
Thanks @NathanMOlson  - I tried it, but I don't think it's sufficient.

**Comment by HarelM** [comment]
Please add the relevant tests so this won't break in the future...

**Review by birkskyum — APPROVED** [review]
That does appear to work like I'd expect it to

**Comment by birkskyum** [comment]
i'm trying to figure how we can test this. The render test suite has a style.json set initially, but this bug show up after changing the style.

**Comment by HarelM** [comment]
@NathanMOlson any updates on this?

**Comment by NathanMOlson** [comment]
> @NathanMOlson any updates on this?

No. I haven't figured out how to write a test for this.

**Comment by HarelM** [comment]
Do you need my help for this? A unit test works probably be sufficient I guess...

**Comment by HarelM** [comment]
The copies are shown, but not at the appropriate size, once you pan the map a bit, the size of the map changes to fit the screen:
image

So I believe this is not fully fixed. I'm working on a test, maybe a render test, to showcase this issue.

**Comment by HarelM** [comment]
It has something to do with the zoom change between globe and mercator, and probably a constraint around the zoom which is not being respected when setting the projection from globe to mercator...

**Comment by HarelM** [comment]
I'll merge it to a branch under maplibre to allow collaboration.

**Pull request merged**
