### PR TITLE
Remove unused devDependencies

### PR DESCRIPTION
**Pull request by birkskyum**
The following devDependencies appear to be unused and should therefore be removed.

- @octokit/rest
- jsonwebtoken
- list-npm-contents
- npm-packlist
- pirates
- qrcode-terminal

Also, I moved all types/* packages that were in dependencies to devDependencies.

### CODE REVIEW

**Comment by HarelM** [comment]
Did you use a tool to find them?
Also we should probably remove some of the @types packages too...?

**Comment by birkskyum** [comment]
I often use npm-check-updates to get an overview of versions, but in this case I just went through all the packages manually, and checked that they weren't imported anywhere or cli-tools.

**Comment by HarelM** [comment]
This means all the rest are in use? Seems like a lot of packages...

**Comment by birkskyum** [comment]
many are related to tape, testem etc

**Comment by HarelM** [comment]
Hmm, this explains as there are a lot of dev dependencies mainly...

**Review by HarelM — APPROVED** [review]

**Pull request merged**
