### PR TITLE
Unblock github runners by using ubuntu

### PR DESCRIPTION
**Pull request by birkskyum**
I find that the macos-latest and windows-latest runners tend to be extremely slow partially because they are queued to start due to a small agent poll. In the attached picture a test is stalling almost half an hour to start due to a lack of macos agents.

Screenshot 2022-08-06 at 19 25 01

### CODE REVIEW

**Comment by birkskyum** [comment]
The hardcoded browser test with CJK Characters is for some reason breaking with anything but macos-latest.

**Comment by HarelM** [comment]
That's because this test isn't great - I added it to make sure CJK characters are not breaking, but the image is "hard coded" and I used the results from the test to update the expected. So it only passes on the build machine, it's not passing locally for developers as well.
To improve this I guess the pixelmatch from the render test should be used, but the problem is that it's hard to update a failing test in this case I think (if it fails in the CI and passes locally).
In any case you can either copy the `Received: "<html><head></head><body>...` and put it in the browser test expected for the test to pass...

**Comment by birkskyum** [comment]
I tried to copy the received output from the git runner to update the expected.html, but it looked different than i expected. This was the output from the ubuntu runner, so I wonder if we have a platform specific render issue:

download

**Comment by HarelM** [comment]
There might be a problem with ubuntu and CJK characters.
The CI runner might not have everything installed (such as `fonts-noto-cjk`) maybe.
@Kanahiro might know better that I do :-) (I know RTL stuff well, not CJK :-))

**Comment by birkskyum** [comment]
Installing the font helped :)  So this is the macos that we had:

Screenshot 2022-08-06 at 21 50 41

And this is the ubuntu one:


Screenshot 2022-08-06 at 21 50 47

**Comment by HarelM** [comment]
Cool! :-) looks very similar, which is good.

**Comment by birkskyum** [comment]
I made a folder where we can have different variations of this image, like ubuntu, macos etc. and if just one of them passes the test will pass.

**Review by HarelM — APPROVED** [review]
Cool! thanks!

**Pull request merged**
