### PR TITLE
Rename .js to .ts in doc/life-of-a-tile.md

### PR DESCRIPTION
**Pull request by astridx**
Rename .js to .ts in doc/life-of-a-tile.md

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks!! Did you check that the line numbers have not changed by any chance?

**Comment by astridx** [comment]
> Thanks!! Did you check that the line numbers have not changed by any chance?

Yes. I think they were already wrong before. 

So my main point was that you don't end up on an error page when you click on something. And it helps to search if you want to find out if there is still a renamed file linked somewhere. 

Do you think it's worth completely reworking the developer documentation? Do we even use this guide to create a release?

**Comment by HarelM** [comment]
There are two different questions here: 
1. life of a tile documentation is not about release, If we don't maintain the line numbers in it we should remove them and simply link to the file itself, I think. I agree there shouldn't be an error. Also it might be better to place this in the docs repo, I don't know...
2. The release document is not relevant anymore, there's a `RELEASE-PROCESS.md` outside the docs folder which is correct and up-to-date I think. We should decide if we want to keep it out side or replace the document inside the docs folder. Either way works for me...

**Comment by astridx** [comment]
> 1. If we don't maintain the line numbers in it we should remove them

If only the line numbers are deleted, it is still wrong. Look at the first link with line number. The panTo method is no longer in the Map class. Map inherits it from Camera. The UML diagrams have also never been updated in this repo so far.  And obviously no one paid attention to the fact that there is a description for creating a release here, otherwise this file would have been deleted or updated.

You are right. I'll close this PR . Either a more extensive rewrite is needed or it should be deleted altogether.

**Pull request closed without merging**
