### PR TITLE
Remove access token

### LINKED ISSUE #216: [Typescript] Remove access token and telemetry
**maplibre-gl-js version**:^1.14.0

**browser**: any

### Steps to Trigger Behavior

 1. Init a map with `accessToken: 'no-token'`
 3. See a HTTP request to mapbox servers

### Expected Behavior
Setting is ignored and HTTP call to mapbox servers never happens.

Thanks for setting up this fork, your timing couldn't be better & its appreciated.

This is probably a duplicate of a wider issue but all HTTP calls to mapbox should be removed ASAP as it an "information leak" to some extent.

### PR DESCRIPTION
**Pull request by HarelM**
This PR is for removing access token from the code.
This will replace #21 but the code changes are very similar.
This also fixes #216.
Replaces #293 due to merge conflicts...

 - [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] briefly describe the changes in this PR: 
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by HarelM** [comment]
@wipfli @lseelenbinder @fredj @nyurik @petr-pokorny-1 any chance for a review? There're not much here besides removing telemetry and mapbox access token...

**Review by petr-pokorny-1 — APPROVED** [review]
I havent found any issues. Great job!

**Comment by wipfli** [comment]
Looks good to me as well. Removing code that talks to mapbox servers is really a relief. Thanks for the cleanup Harel.

One thing that can be improved is renaming of files. GitHub tells me for example that `util/mapbox` was deleted and `util/request_manager` was added. I assume that this is because you run something like this:

```bash
$ mv util/mapbox util/request_manager
$ git add util/request_manager
```

If instead you run only

```bash
$ git mv util_mapbox util/request_manager
```

GitHub will probably show that the file was renamed and which parts were then deleted. This would make reviewing easier. Let me know if I got something wrong.

**Comment by wipfli** [comment]
Regarding migrating from Mapbox v1 to MapLibre v2: We recently came up with the idea that `addProtocol` could be used to facilitate custom protocols and also access token management. Can you draft an example of how one can migrate after the removal of `accessToken`?

**Comment by HarelM** [comment]
I think it's better this way - take a look at the top of the file of mapbox. It says that if you change it you violate their terms and conditions. So I decided to delete it and add a file instead.
Regarding the addProtocol, and due to the message above I'm not sure I should document this officially as it feels like a violation of their terms again. I don't know...

**Comment by xabbu42** [comment]
@wipfli git does not really track file moves but detects them based on similarities, so `git mv` is just a shorthand for `git rm` and `git add`.

**Comment by wipfli** [comment]
Beautiful, I didn't know that.

**Pull request merged**
