### PR TITLE
Attribution default open for osm

### PR DESCRIPTION
**Pull request by acalcutt**
This is an attempt to Show OSM attribution by default, like mentioned in ( https://github.com/maplibre/maplibre-gl-js/issues/205 )

This change makes the compact mode default to being open to comply with the [OpenSteetMap Attribution Guidelines](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines#Interactive_maps) that expect attribution is [visible for at least some time](https://lists.openstreetmap.org/pipermail/osmf-talk/2021-June/007914.html) without user interaction to fall within the safe harbour rules. 

- code has been added so the button is default open when going into compact mode.
- code has been added so attribution will close automatically when there is a drag action
- code has been added to not show the compact button if there are no attributes to prevent a open attribute button with no attributes. (I actually noticed the compact button existing when there were no attributes bug on the maplibre site on <= 640 screen width, but it is more noticeable when it is open by default. )

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [X] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by acalcutt** [comment]
Here's an example page 
https://stackblitz.com/edit/web-platform-ralmch?file=index.html

**Comment by HarelM** [comment]
Please update changelog file.

**Comment by acalcutt** [comment]
I updated the changelog and did a re-merge, but it seems like some other junk I didn't touch in "test/integration/assets/sprites/ " and "build/generate-query-test-fixtures.ts" are causing issues now. 

not sure what I should do to fix those things since they arn't part of what I changed

**Comment by wipfli** [comment]
Can you share the diffs of the failing render tests?

**Comment by wipfli** [comment]
Can you run the render tests locally, go to the folder of the failing tests, and check for the file `diff.png`? There should be these files after the tests run: `expected.png  style.json diff.png actual.png`

**Comment by acalcutt** [comment]
I upgraded the example page at ( https://stackblitz.com/edit/web-platform-ralmch?file=index.html ) to the latest version. still working as expected.

**Comment by wipfli** [comment]
Thanks @acalcutt! @astridx would you mind having a look at this?

**Comment by astridx** [comment]
I think this PR is a great improvement. It's not just that the Attribution Control probably fulfils Openstreetmap licence better. It also corrects some things that I think were not intuitive before. Thank you for this @acalcutt 
Here are my notes:


|attributionControl in Map|compact in AttributionControl|customAttribution  in AttributionControl|---|
|---|---|---|---|
| not set or true | no Control | no Control | 1 Expectation: No attribution control is displayed. Neither above nor below 640 pixels. At the moment, an empty frame is displayed if the screen is smaller than 640. This PR corrects this. | 
| not set or true | false | not set | 2 Same as before | 
| not set or true | false | small text | 3 Expectation: Text is displayed in a non-compact form. Above and below 640 pixels screen width. This is now also super. Before, an empty compact frame was displayed below 640. |
| not set or true | false | big text | 4 Same as before |
| not set or true | true | not set | 5 Expectation: As there is no text, nothing should be shown. This is great in the version of these PRs. Before, the empty compact control was displayed. Under 640 pixels even in double form.|
| not set or true | true | small text | 6 Expectation: The text is presented in a compact control because it is explicitly set. The Attribution Control was and is displayed in a compact form. In this PR, the display starts in open form and can be closed by the user. In my opinion, this is a good solution. It is admittedly a change of behaviour. But it is not a breaking change.|
| not set or true | true | big text | 7 Same as before |
| not set or true | - | - | 8 Same as 5  |
| not set or true | not set | small text | 9 Expectation: Text is displayed in a non-compact form above 640 Pixel because the option compact is not explicitly set. In our current version, the display switches to the closed compact version when the number of pixels is less than 640. This PR changes the switch to the open compact version ( and ensures that the empty control is no longer displayed. This is great!) |
| not set or true | not set | big text | 10 Same as 8. |
| false | no Control | no Control | 11 Expectation: No attribution control is displayed. That is fine bofore and actually. |
| false | false | - | 12 Expectation: No attribution control is displayed as there is no text. That is fine bofore and actually below and above 640 Pixel. |
| false | false | small text | 13 Expectation: Text is displayed in a non-compact form. That is fine bofore and actually below and above 640 Pixel.|
| false | false | big text | 14 Same as 13 |
| false | true | - | 15 Expectation: As there is no text, nothing should be shown. This is fine in this PR. Before below 640 Pixel an empty compact control is shown. |
| false | true  | small text | 16 Expectation: The text is presented in a compact control because it is explicitly set. That was correct before and is correct now. The difference is that now the compact control starts in open form. See 6 |
| false | true  | big text | 17 Same as 16. |
| false | - | - | 18  Same as 15 |
| false | - | small text |  19 Expectation: Text is displayed in a non-compact form above 640 Pixel because the option compact is not explicitly set. In our current version, the display switches to the closed compact version when the number of pixels is less than 640. This PR changes the switch to the open compact version. |
| false | - | big text | 20 Same as 18. |

**Review by astridx — APPROVED** [review]

**Pull request merged**
