### PR TITLE
Lossless Image Optimisation Example Images

### PR DESCRIPTION
**Pull request by coliff**
Saved 12.6 MB out of 20.8 MB. 30% per file on average.

I used ImageOptim app for macOS.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks!
Can you add some instruction to the readme file, may an optinal step?
https://github.com/maplibre/maplibre-gl-js/blob/cdf93b0484bcf1790310e3983be9b081783a8ebf/docs/README.md?plain=1#L61

**Comment by HarelM** [comment]
If you can do it in a github action, then you should be able to simply add it to the generate-images.ts script, assuming this is something that anyone can do without installing too much stuff.

**Comment by YohanSciubukgian** [comment]
Could it be interesting to move to webp image format as it is widely adopted for a while now ?
https://caniuse.com/webp

It could help to further reduce file size as par https://developers.google.com/speed/webp/docs/webp_study

**Comment by HarelM** [comment]
I have no objections as long as there's an easy way to generate them as part of the image generation script.

**Comment by HarelM** [comment]
@coliff @YohanSciubukgian any updates on this?

**Comment by coliff** [comment]
> @coliff @YohanSciubukgian any updates on this?

As it stands, the changes in this PR is a huge improvement. I personally think it's worth merging as it is for now. I don't really have the time/motivation to move the generate images to WebP.

(separately though, we should also lazy-load the images. That way not all 99 images all load on the page right away, and will only load as a user scrolls near. That will help a huge amount! Mkdocs-Material supports this:
https://squidfunk.github.io/mkdocs-material/reference/images/?h=lazy+load#image-lazy-loading )

**Comment by HarelM** [comment]
Can you add a comment at least in the readme for users who are generating images using the script to let them know how to compress it?
Feel free to add lazy load to mkdocs config, sounds like a good addition.

**Comment by HarelM** [comment]
I was not able to reduce a png image size with https://squoosh.app/
I'll update the docs to use https://compresspng.com/ as part of #3645 PR.

**Comment by coliff** [comment]
> I was not able to reduce a png image size with [squoosh.app](https://squoosh.app/) I'll update the docs to use [compresspng.com](https://compresspng.com/) as part of #3645 PR.

Hmm, Maybe you were not doing it correctly then? I think [squoosh.app](https://squoosh.app/) is the best and is updated regularly with the best/latest compression. Select OxiPNG in the Compress dropdown.
image

**Comment by HarelM** [comment]
I got 9% at best with squoosh. With https://compresspng.com/ I got 63%.

**Comment by coliff** [comment]
> I got 9% at best with squoosh. With [compresspng.com](https://compresspng.com/) I got 63%.

ok up to you, but I think compresspng.com likely won't work well for high fidelity images if they are reducing them to 8-bit (256 colors). it appears to rename files too.

**Comment by HarelM** [comment]
These are "thumbnails" for the examples, I don't need it pixel perfect and use a lossless compression, on the contrary, I need the image to be small and represent the example well, much like the addition of lazy.

**Comment by YohanSciubukgian** [comment]
Hi @HarelM, sorry to be late on this. I just made a PR to address the webp image format optimization.

**Pull request merged**
