### PR TITLE
Post tap to jest migration clean-up

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

Implements todo list of @Astridx #458 of clean-up steps after the tap to jest migration.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by birkskyum** [comment]
I think tap can be safely removed now as well  (#810)

**Comment by HarelM** [comment]
Also rename jest-test to test...?

**Comment by astridx** [comment]
Also delete `replace-in-file` and `jscodeshift `(https://github.com/maplibre/maplibre-gl-js/blob/main/jest-migration.md#after-the-migration-to-jest)?

**Comment by wipfli** [comment]
See #862

**Pull request closed without merging**
