### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by jleedev**
Fixes these two build errors when using pnpm, yarn, or when using one of npm's newer (more correct) [install-strategy]s.

> [!] (plugin typescript) RollupError: @rollup/plugin-typescript: Could
> not find module 'tslib', which is required by this plugin. Is it
> installed?
> (!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find
> module 'expect' or its corresponding type declarations.

Note that the [plugin says] "The `tslib` helper module always must be used", so it's needed to run even though we're using `importHelpers: false`.

[install-strategy]: https://docs.npmjs.com/cli/v9/commands/npm-install#install-strategy
[plugin says]: https://www.npmjs.com/package/@rollup/plugin-typescript#ignored-options

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by jleedev** [comment]
Although the version of expect did change from 29.4.3 to 29.5.0, those versions are identical in code, so I would assume these build failures to be flakes.

**Review by HarelM — APPROVED** [review]
THANKS!

**Comment by HarelM** [comment]
CI is failing, but I don't think it's related to this PR.
cc: @birkskyum

**Comment by HarelM** [comment]
I can't make the tests pass, I have no clue why. I have re-ran them like 5 times already...

**Comment by birkskyum** [comment]
Is this rebased to the latest main?

**Comment by birkskyum** [comment]
When #2499 is in, let's try to rebase this to the latest main and try again.

**Comment by birkskyum** [comment]
It's in now

**Comment by birkskyum** [comment]
The tests now fail for a different reason. This color gradient is breaking both render and expression tests, because it has a slightly different gradient than the expected.

Screenshot 2023-05-10 at 17 59 09
[render-test-report-ubuntu-latest.zip](https://github.com/maplibre/maplibre-gl-js/files/11443956/render-test-report-ubuntu-latest.zip)

**Comment by birkskyum** [comment]
The failing expression tests:

**interpolate-lab/linear**

      Expected [[1,0,0,1],[0.843015,0,0.446122,1],[0,0,1,1],{"error":"Could not parse color from value 'oops blue'"}]
      Result   [[1,0,0,1],[0.8140950912052022,0,0.4447724350959299,1],[0,0,1,1],{"error":"Could not parse color from value 'oops blue'"}]

**interpolate-hcl/linear**

      Expected [[1,0,0,1],[1,0,0.405375,1],[0,0,1,1],{"error":"Could not parse color from value 'oops blue'"}]
      Result   [[1,0,0,1],[1,0,0.4251124784649884,1],[0,0,1,1],{"error":"Could not parse color from value 'oops blue'"}]
      
@kajkal , @drwestco , any ideas what could go wrong here? These tests pass in the main thread on the same type of ubuntu runner.

**Comment by HarelM** [comment]
The style-spec in the lock file had changed, which causes the hcl to fail as we need to get the latest version of style spec and update the render tests...
Not related to this PR, but caused due to the change in the lock file...

**Comment by birkskyum** [comment]
@jleedev , if you find at some point a way to remove any of these packages again, that would be awesome because it's a bit confusing that we don't use them directly.

**Pull request closed without merging**
