### PR TITLE
Bump to v2.0.0

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

This pull request bumps MapLibre GL JS to v2.0.0.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
Resolves #610

**Review by HarelM — APPROVED** [review]

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
Closes #648

**Comment by wipfli** [comment]
Houps, sorry for constantly adding more commits. That should be it I think.

**Comment by wipfli** [comment]
Fingers crossed...

**Pull request merged**
