### PR TITLE
Bump test dependencies

### PR DESCRIPTION
**Pull request by birkskyum**
With the jest migration done, we can remove a lot of packages, but these are still in use and at least one major version behind their latest versions - so dependabot won't update them.

JSDom (jest test environment)
testem (query tests)

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Are the browser test actually running???
image

**Comment by birkskyum** [comment]
I don't believe they currently run. (#862)

**Comment by HarelM** [comment]
Did they used to run? When did they stop running?

**Comment by birkskyum** [comment]
I think they were running previously, and disabled here (#810 ). I will make a PR hooking up the jest to the test-browser script.

**Comment by HarelM** [comment]
Thanks!

**Comment by birkskyum** [comment]
It's in here (#866)

**Pull request merged**
