### PR TITLE
Fix CI - match ChromeDriver version with Chrome

### PR DESCRIPTION
**Pull request by nyurik**
Ensure the version of the ChromeDriver is the same as the Chrome version installed locally.

### CODE REVIEW

**Comment by nyurik** [comment]
@msbarry i'm reverting your 15b991160149 because it now breaks CI. Any reason not to do this?

**Comment by msbarry** [comment]
> @msbarry i'm reverting your [15b9911](https://github.com/maplibre/maplibre-gl-js/commit/15b99116014909a61c061e2189d1b0ceca979f6b) because it now breaks CI. Any reason not to do this?

@nyurik if the chrome browser test passes with this it should be fine. The problem before was that the browser tests would fail due to incompatible chrome versions.

**Comment by nyurik** [comment]
@msbarry want to approve it in the files tab?

**Review by Joxit — APPROVED** [review]
LGTM, good job! 👍

**Comment by msbarry** [comment]
Ah sorry about that. Looks like @Joxit got it. Thanks for fixing!

**Comment by nyurik** [comment]
@Joxit @msbarry np, its ok :). One thing though -- it is usually better to `approve` rather than `merge` (for the members) -- because it gives the final control of the merge to the author, so in case the author doesn't feel its ready to merge for some reason, or sees something last second, they could stall until fixed. In other words - the author who is a member of the project should be responsible for merging rather than throwing it over the wall to whoever else to merge. It has worked out better in such projects in my experience.

**Pull request merged**
