### PR TITLE
Remove remaining gl-style-composite references

### LINKED ISSUE #1981: Remove the `gl-style-composite` utility
## Motivation
The `gl-style-composite` utility is `mapbox://`-specific optimization tool. It is used to reduce the tile consumption costs for MapBox customers by replacing several sources with a single "composite" source. See the [MapBox API](https://docs.mapbox.com/api/maps/vector-tiles/#retrieve-vector-tiles) for some details.

The code clearly handled only `mapbox://` sources:

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L14-L16

IMO it need not and should not be released as part of the MapLibre release.

Related to #1963

### PR DESCRIPTION
**Pull request by zstadler**
Resolve #1981

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    - Not applicable
 - [ ] Write tests for all new functionality.
    - Not applicable
 - [ ] Document any changes to public APIs.
    - Not applicable
 - [ ] Post benchmark scores.
    - Not applicable
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.
   - There is no externally visible change in this PR. The external change was already entered into `CHANGELOG.md`

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
THANKS!

**Comment by HarelM** [comment]
Oh, forgot to ask to update the version of style-spec and add changlelog in style-spec changelog file.

**Comment by zstadler** [comment]
This PR only removed dead code.

**Comment by HarelM** [comment]
Right, sorry, my mistake, this was mentioned already in the changelog here:
> Fix errors when running style-spec bin scripts and added missing help. Removed unnecessary script 'gl-style-composite'. (https://github.com/maplibre/maplibre-gl-js/pull/1971)

**Pull request merged**
