### PR TITLE
Upload coverage to codecov

### PR DESCRIPTION
**Pull request by HarelM**
This should allow uploading coverage report to codecov.

### CODE REVIEW

**Comment by HarelM** [comment]
This seems to be working as expected, yay!
So much easier than it was in the past, it's just amazing!
@louwers, thanks for the nudge!
image

**Comment by HarelM** [comment]
There's a question now if there's actually a need to upload the coverage report to github artifcats, it's not very intuitive to find it and codecov has a great UI to see coverage by all kind of sorting methods.

**Review by birkskyum — APPROVED** [review]

**Comment by birkskyum** [comment]
This is great! :) How is the UI easiest to access?

**Comment by HarelM** [comment]
From here:
https://app.codecov.io/gh/maplibre/maplibre-gl-js
I'll add a badge in the readme once I'll see the coverage on main.

**Pull request merged**
