### PR TITLE
Un-bump `@mapbox/tiny-sdf`

### PR DESCRIPTION
**Pull request by wipfli**
Reverts the tiny-sdf version bump from 1 to 2, see https://github.com/maplibre/maplibre-gl-js/pull/387#issuecomment-927618809.

What am I doing wrong with the lockfile?

### CODE REVIEW

**Comment by wipfli** [comment]
The lockfile version seems off. I get this warning:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

**Comment by HarelM** [comment]
Wait, I want fix the dude with the latest version instead of downgrading...

**Comment by HarelM** [comment]
Which version of npm are you on?

**Comment by wipfli** [comment]
Ah cool, then I will hold back :) The conflicts are trivial, my bad.

```
npm --version
6.14.15
```

**Comment by HarelM** [comment]
You need to upgrade to 7.x.

**Pull request closed without merging**
