### PR TITLE
Move kdbush to be a dependency instead of dev dependency

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

kdbush was introduced in a recent PR.
When using version 3.0.0-pre.2 with typescript it saids that you need to install the kdbush types.
This is not a great expericence.
This is similar to geojson, point, vctor-tiles etc.

image

### CODE REVIEW

**Comment by rotu** [comment]
This is puzzling to me. When is the above message happening?

Is kdbush an externalized dependency? It seems to me like it’s bundled and it (and certainly its types) should be under devDepencencies.

**Comment by HarelM** [comment]
The generated types definition is creating the maplibre.d.ts file with `import KDBush from 'kdbush';` When using this without installing the types you'll get the following error.
It might be a limitation of the tool we are using to generate the `maplibre.d.ts` file, IDK...

**Comment by rotu** [comment]
Two things:
1. I think we should only export types for exposed interfaces (not sure how hard to make this change, but essentially ` --export-referenced-types `)
2. In the near-term, we should use `--external-inlines kdbush` etc. so that the d.ts is self-contained.

**Comment by HarelM** [comment]
Feel free to try it out and replace this solution. I don't have a strong feelings about the current solution.
Note that inlining packages definitions might cause issue for people referencing these external libraries, I guess...
In any case, there's a big that needs to be fixed in the current pre-release...

**Comment by rotu** [comment]
I don't *really* know what I'm doing here, but I gave it a whack in #2015.

**Comment by wipfli** [comment]
I think we had similar things in the past. If that fixes the issue for now I guess it is fine to merge...

**Pull request merged**
