### PR TITLE
Remove @rollup/plugin-json

### PR DESCRIPTION
**Pull request by rotu**
`@rollup/plugin-json` and `rollup-plugin-import-assert` both convert imported JSON files to importable javascript modules. This means that, not only is only one needed, but the second one that runs on a given JSON file actually errors out. Since `@rollup/plugin-json` is erroring out anyway, we remove it.

Note that `rollup-plugin-import-assert` has an additional bug with importing JSON files from node modules. So this PR should probably be merged in *after* #1898 (which removes exposure to that bug) or after PR https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/11 (which fixes the upstream bug).

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [X] Include before/after visuals or gifs if this PR includes visual changes.
 - [X] Write tests for all new functionality.
 - [X] Document any changes to public APIs.
 - [X] Post benchmark scores.
 - [X] Manually test the debug page.
 - [X] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by rotu** [comment]
I'm still not totally sure about this. I was getting some errors from `rollup-plugin-import-assert` due to the files no longer being valid JSON after going through `@rollup/plugin-json` but I'm now getting errors due to the missing `@rollup/plugin-json`.

Does `npm run start-bench` really work for you without this PR?

**Comment by rotu** [comment]
I found the reason for some other build problems with this PR and fixed upstream:
https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/11

(`rollup-plugin-import-assert` does not process json files when the import is within a node module, or is otherwise not just a path)

**Comment by HarelM** [comment]
Does this mean there's a need to use the yet to be released version of the assert plugin?
I'm not sure I understand the status of this PR... Can you better explain the motivation and solution (better to have it in the first message of the PR)?

**Comment by HarelM** [comment]
Can you please rebase? The tests are failing due to a problem with ubuntu image changes. This is fixed in main.

**Comment by rotu** [comment]
> Does this mean there's a need to use the yet to be released version of the assert plugin? I'm not sure I understand the status of this PR... Can you better explain the motivation and solution (better to have it in the first message of the PR)?

No, that should not be necessary. #1898 removes exposure to the upstream bug, so it should be merged first.

**Comment by HarelM** [comment]
Thanks for the info! what error did this issue created then? According to the topmost message, there's an issue that this PR fixes, how does this issue manifests?
Generally speaking, this PR looks good, I just better want to understand the issue and the soltuion.

**Review by HarelM — APPROVED** [review]

**Comment by rotu** [comment]
> Thanks for the info! what error did this issue created then? According to the topmost message, there's an issue that this PR fixes, how does this issue manifests? Generally speaking, this PR looks good, I just better want to understand the issue and the solution.

The issue is, as far as I can tell, just log noise at the moment.

During the build process, the json plugin hits a parsing problem (it can't process the file, since it's not valid JSON after being processed by `rollup-plugin-import-assert`). This then causes the `@rollup/plugin-json` plugin to try and log this as a warning. But due to a bug there (it tries to parse the JSON parser's `SyntaxError` and throws a brand new `TypeError` in the process), it crashes the plugin (fixing this in https://github.com/rollup/plugins/pull/1361).

Since the `@rollup/plugin-json` plugin is not actually succeeding, I rip it out in this PR. I'm surprised the build process actually succeeds and rollup doesn't complain louder!

**Comment by rotu** [comment]
Rebased

**Comment by rotu** [comment]
> ~~The issue is, as far as I can tell, just log noise at the moment.~~

> ~~I'm surprised the build process actually succeeds and rollup doesn't complain louder!~~

Scratch that. This *does* cause `npm run build-dev` and consequently `build-dist` to fail on Windows.

**Pull request merged**
