### PR TITLE
Losslessly Optimized all Images

### PR DESCRIPTION
**Pull request by coliff**
Used https://imageoptim.com/mac

Saved 39.MB out of 104 MB. 42.5% Average.

smaller file sizes = Faster loading, improved performance and more eco. :-)

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Seems like this can't be properly reviewed by github :-(
Can you make sure to add instructions in the readme that talks about the examples image generation to use this tool to reduce the image size.
Is there an API call one can use on a file to automate this?

**Comment by HarelM** [comment]
The browser gets stuck when I try to look at this.
Can you split this into multiple PRs somehow? 100 files in each?
I can open a branch for it so you can merge it to it, and then merge that branch using squash...?

**Comment by coliff** [comment]
Sorry, I can't really make separate PRs for this - it would take far too long to prepare.

Moving forward, we could possibly use a GitHub Action to automate it for future PRs... something like this: https://github.com/twbs/blog/blob/main/.github/workflows/calibreapp-image-actions.yml

**Comment by HarelM** [comment]
I'm not sure I can merge it without being able to know which files have changed... :-(
Any ideas how to solve this?

**Comment by coliff** [comment]
> I'm not sure I can merge it without being able to know which files have changed... :-( Any ideas how to solve this?

If it was me, I'd use Beyond Compare and have a folder of the `main` branch on one side and do a compare to a checked out branch. You can set it to only show changed files and can view side by side. Awesome app - highly recommended and can use it free for a while.

**Comment by coliff** [comment]
Maybe the GitHub VS Code extension could be helpful for this too:
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

image

**Comment by HarelM** [comment]
I'll take a look at those! Thanks!

**Comment by HarelM** [comment]
I was finally able to review this.
Knowing how git work, this is actually increasing the size when cloning and forking since git saves the history of the files that were deleted too, so when cloning (without setting the deep flag, and using the default) you'll get both versions of the files..
Having said that, for the images in the docs this will save bandwidth and improve load performance for the documentation site.
I'm surprised the render test didn't fail as they compare pixels and it seems like the images look the same for the comparison.
Having said that, I don't see a real value in updating the images of the tests.

So I think a better approach here would be to undated the examples' images here:
https://github.com/maplibre/maplibre-gl-js/tree/main/docs/assets/examples
And stuff that are under assests folder, but not the "expected.png" images in the tests.

What do you think?

BTW, thanks a lot for all the help in improving this repo text and size, this is truly appreciated!

**Comment by coliff** [comment]
> So I think a better approach here would be to undated the examples' images here:
[main/docs/assets/examples](https://github.com/maplibre/maplibre-gl-js/tree/main/docs/assets/examples?rgh-link-date=2024-05-28T05%3A46%3A14Z)

Cool, no problem. I'll close this and make a new smaller PR :-)

**Pull request closed without merging**
