### PR TITLE
Remove `test-render`

### PR DESCRIPTION
**Pull request by wipfli**
See https://github.com/maplibre/maplibre-gl-js/pull/351#issuecomment-922047997

### CODE REVIEW

**Comment by HarelM** [comment]
You can probably still remove the lint, I guess...

**Comment by wipfli** [comment]
Beautiful, now `test-browser` failed again. Probably it did so for no good reason.

**Comment by HarelM** [comment]
Yup, timeout of some sort. This is why I opened an issue to split the ci into different files, to allow rerun a single test suite... It should be hard now suffer you are an expert in github action :-)

**Comment by wipfli** [comment]
> You can probably still remove the lint, I guess...

I agree, but at this point I don't dare changing it anymore.

**Comment by wipfli** [comment]
Another false alarm occurred in macos. Rerunning...

**Comment by wipfli** [comment]
Out-of-memory error occurred.

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
My current understanding is that `test-render` will not work until we have a data provider for the tiles. We can set this up in a separate pull request. Until then, `test-render` should not be part of CI on the main branch.

**Pull request merged**
