### PR TITLE
Initial work on a ROADMAP document.

### PR DESCRIPTION
**Pull request by lseelenbinder**
Goal: I want users to know we don't plan to move fast and break things, especially API compatibility.

### CODE REVIEW

**Comment by klokan** [comment]
Don't you want to place the Roadmap to https://github.com/maplibre/maplibre-gl-js/projects - made with notes instead of tickets?

**Comment by lseelenbinder** [comment]
That's a good idea @klokan! Let me rework this…

**Comment by lseelenbinder** [comment]
How's that look @klokan?

**Review by klokan — APPROVED** [review]

**Review by snickell — APPROVED** [review]
This looks great @lseelenbinder , thanks for putting this together, I know writing a "short+_sweet amount of text" is usually harder than writing "a huge block of text"

**Pull request merged**
