### PR TITLE
fix compact attribution style when using windicss

### PR DESCRIPTION
**Pull request by lukashass**
## Launch Checklist

Explicitly sets `box-sizing: content-box;` for compact attribution details. This is necessary because frameworks like WindiCSS or TailwindCSS are setting `box-sizing: border-box;` globally.

### Before

image

### After

image

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Suggest a changelog category: bug
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog>Fix compact attribution style when using frameworks like TailwindCSS</changelog>`.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks @lukashass for this suggestion. 

Do you know if this was always a problem or if it only came with a recent version? 

And do you know if we could add some test to make sure that the layout of this info box stays centered?

**Comment by wipfli** [comment]
I saw that the "i" is indeed not nicely centered in the maplibre-gl-directions examples on https://maplibre.org/maplibre-gl-directions/#/examples/user-interaction. I think @smellyshovel uses tailwind, too.

**Comment by lukashass** [comment]
> Do you know if this was always a problem or if it only came with a recent version?

This is also an issue in 2.0.0 (tested) and since these lines are the same in 1.15.x I would guess this problem is quite old.

> And do you know if we could add some test to make sure that the layout of this info box stays centered?

One idea would be a test suite that can take browser screenshots e.g. [playwright](https://playwright.dev/). If you don't have something like this already setup, I could take a look. This might be a bit overkill to only test some layout though :thinking:.

**Comment by HarelM** [comment]
There are browser tests that use playwright, but I think screen capture is a bit of an overkill in this situation. I would simply make sure the css attribute exists in the relevant case.

**Comment by wipfli** [comment]
I think then it is fine to not do a test here. @lukashass can you share a minimal example with tailwind such that I can check myself that this pull request fixes the issue?

**Comment by lukashass** [comment]
Minimal reproduction: https://stackblitz.com/edit/map-libre-pr-1250-repro?file=index.html,fixed.html

@wipfli I just included the build artifacts from this PR so it should be easy to test.

**Review by wipfli — APPROVED** [review]
Great, thanks for the fix and for the demo @lukashass

**Comment by wipfli** [comment]
Ah, changelog... Can you add an item?

**Comment by lukashass** [comment]
> Ah, changelog... Can you add an item?

In `CHANGELOG.md` or in the PR description?

**Comment by wipfli** [comment]
In CHANGELOG.md

**Review by wipfli — APPROVED** [review]
Thank you

**Pull request merged**
