### PR TITLE
Build process cleanup

### PR DESCRIPTION
**Pull request by rotu**
- Moved code generation from postinstall to prepare hook
- Remove unused file (that typescript didn't like anyway)
- Unify typescript config
- Remove top-level rollup directory

### CODE REVIEW

**Comment by HarelM** [comment]
Any chance to unify build and rollup folders as well while you are on it?
I don't think there's a need for a rollup folder as it is a technology and not a "thing" like src, tests etc...
Bottom line, I think the build folder should stay but not the rollup.

**Comment by birkskyum** [comment]
Good progress on this. When running `npm run start-bench` I get:

`[!] Error: ENOENT: no such file or directory, open 'rollup/bundle_prelude.js'`

**Review by HarelM — APPROVED** [review]
Looks good! Ist it ready to be merge?

**Comment by rotu** [comment]
I think it’s ready. I’d like to get rid of the staging files for good in a future PR (basically replace the main build with the CSP build), but this is good to go!

**Comment by birkskyum** [comment]
What does CSP refer to in this context?

**Comment by HarelM** [comment]
Great work, thanks!

**Pull request merged**
