### PR TITLE
Test opacity of a partly visible marker

### PR DESCRIPTION
**Pull request by sbachinin**
Concludes https://github.com/maplibre/maplibre-gl-js/issues/3458

### CODE REVIEW

**Comment by HarelM** [comment]
For some reason codecov didn't send a message, can you make sure the line is now fully covered?

**Review by HarelM — APPROVED** [review]

**Comment by sbachinin** [comment]
From my understanding, this line is now ok. There are test cases that reach this line and execute both truthy and falsy part

**Review by HarelM — APPROVED** [review]

**Comment by sbachinin** [comment]
Noticed that marker loses opacity on window resize. Is it worth creating an issue?

**Comment by HarelM** [comment]
Can you attach a video?

**Comment by sbachinin** [comment]
https://github.com/maplibre/maplibre-gl-js/assets/11789697/bc9d2b2a-44ab-4729-9085-b02c67291ce8

**Comment by HarelM** [comment]
I would recommend opening a new issue, maybe an issue with the coordinates buffer.

**Pull request merged**
