### PR TITLE
Lint build-folder TypeScript scripts

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

#928 made me think that the build-folder TypeScript files are not linted. This pull request removes `build/.eslintrc` and lints the TypeScript files.

Note that the top-level `.eslintrc` excludes all `.js` files, so that `build/.eslintrc` has no effect on the js files in that folder.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by wipfli** [comment]
What has to change in `package.json`?

**Comment by HarelM** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/6c41b23443c7e23aa4e30d28db414fa30bbd2507/package.json#L179

**Comment by HarelM** [comment]
Wait, build folder is already there :-/
Never mind me...
But the linked issue is still relevant if you would like to solve it as part of this PR...

**Comment by wipfli** [comment]
Any objections to speeding up the linting step by adding the `--cache` flag back in again? I saw it was there before #209

**Comment by wipfli** [comment]
Regarding #272, I am adding the test folder back to linting. That seems to be the only difference.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
