### PR TITLE
Bump rollup from 2 to 3

### PR DESCRIPTION
**Pull request by birkskyum**
Dependabot can't handle major updates. Rollup 3 requires us to use an extra "--bundleConfigAsCjs" flag in package.json, and it has [built-in support for import assertions](https://github.com/rollup/rollup/pull/4646) with @rollup/plugin-json, so the import assertion plugins are removed.

### CODE REVIEW

**Comment by rotu** [comment]
Why the `--bundleConfigAsCjs`?

**Comment by birkskyum** [comment]
@rotu we haven't managed to do the esm yet, but I'd love for us to support it  - see https://github.com/maplibre/maplibre-gl-js/issues/1595

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
There was an issue with import asserts in the docs repo. Do you think the new rollup version might solve the problems we have seen there too?

**Comment by HarelM** [comment]
I think so, there's a need to make sure the import now uses the `assert` and that you are using 16.14 or later node version.

**Comment by birkskyum** [comment]
Right now we run the 'remove-assert.js' script in the docs anyway.

**Comment by birkskyum** [comment]
I'd like to test these change against the docs, but right now I struggle to run the main branch with node 18. It return an "ERR_OSSL_EVP_UNSUPPORTED" error, and I think we might lack a flag somewhere: NODE_OPTIONS="--openssl-legacy-provider"

**Pull request merged**
