### PR TITLE
Revert commits to fix `test-render`

### PR DESCRIPTION
**Pull request by HarelM**
This is related to #326, #365.
It shouldn't be merged just yet...
It should make a lot more tests pass and allow to find other places that were not reverted, I hope...

Expand all to allow seeing diff in all files:
```js
for(i=0; i<document.getElementsByClassName('js-button-text').length; i++){ document.getElementsByClassName('js-button-text')[i].click();}
```
Before typescript commit ref:
49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f

Latest commit:
a12092bdcaa09732f34ad537a5d2e83523d8e7b8

Diff:
https://github.com/maplibre/maplibre-gl-js/compare/49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f...a12092bdcaa09732f34ad537a5d2e83523d8e7b8

### CODE REVIEW

**Comment by HarelM** [comment]
Current status - seems better on linux than my mac:
```
1120 passed (92.4%)
1 passed but were ignored (0.1%)
10 ignored (0.8%)
80 failed (6.6%)
1 errored (0.1%)
```

I think the way forward is to compare the current latest commit on this branch to the commit before typescript and see what else needs to be reverted, I hope...

**Comment by wipfli** [comment]
Nice. It is great that you fixed already the memory leak. Two places come to mind where further errors could have happened:

* [point.ts](https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/point.ts)
* [copy-glsl-files.js](https://github.com/maplibre/maplibre-gl-js/blob/main/rollup/copy-glsl-files.js)

**Comment by HarelM** [comment]
Interesting thought, but is be surprised if these will cause any changes as the code there didn't change but simply moved from one place to the other. I might be wrong of course, but I need to look at all the file changes and find other suspicious changes. This won't be easy :-( any help would be appreciated...

**Comment by wipfli** [comment]
By default `mat4` will use `Float32Array`, see https://github.com/toji/gl-matrix/blob/0b4bfe9d80001cc2a3afeab415d0f5f8ebdf3b62/src/common.js#L8.

In many instances such as for example rotation or inverse matrices `Float64Array` was used.

I wonder what happens one writes

```js
const m = new Float64Array(16) as any as mat4
```

Will this actually mean that `m` uses 32-bit floating point numbers?

**Comment by HarelM** [comment]
I believe it will use a 64 floating point numbers for extra accuracy. `as something ` doesn't get translated to js, it is simply being removed in transpilation...

**Comment by HarelM** [comment]
Everything is suspicious in theory. I created this branch to allow sending PRs against it for testing what helps...

**Comment by wipfli** [comment]
`src/util/point.ts` seems like a correct copy of the original mapbox version to me.

**Comment by wipfli** [comment]
I updated https://wipfli.github.io/debug-test-render to show the test output [before](https://wipfli.github.io/debug-test-render/37bcaf5) and [after](https://wipfli.github.io/debug-test-render/a12092b) this pull request.

**Comment by wipfli** [comment]
It is interesting and confusing to see what has changed in the output images. Anyway, @JannikGM if you have any idea how to debug this it would be great.

**Comment by HarelM** [comment]
I have reviewed all the files in src and the categorized the changes' risk level (my assumptions of course, feel free to double check me).
I have updated the initial comment in this PR to allow easy usage of tools to show diff and relevant commits.
I'll try to revert later on changes in high risk and see how they change the failing test if at all.

### High risk:
src/geo/transform.ts - `mat4.scale(m, m, [1, 1, mercatorZfromAltitude(1, this.center.lat) * this.worldSize, 1]); // 1 at the end`
src/style/style_layer/circle_style_layer.ts - queryIntersectsFeature, queryRadius
src/style/style_layer/custom_style_layer.ts - hasTransition() { return false; }, onAdd, onRemove
src/style/style_layer/fill_extrusion_style_layer.ts - queryRadius, queryIntersectsFeature, 
src/style/style_layer/fill_style_layer.ts - same as above
src/style/style_layer/heatmap_style_layer.ts - same as above
src/style/style_layer/symbol_style_layer.ts - same as above
src/data/feature_position_map.ts - MAX_SAFE_INTEGER
src/style/style_layer/line_style_layer.ts - MAX_SAFE_INTEGER
src/symbol/check_max_angle.ts - Number
src/util/vectortile_to_geojson.js - toJSON

### Medium risk:
src/data/bucket/line_bucket.ts - undefined points
src/data/bucket/symbol_bucket.ts - writemapmode
src/data/feature_index.ts - id !== undefined
src/symbol/symbol_layout.ts - isSDFIcon
src/source/source_cache.ts - _addTile
src/style-spec/migrate.ts - migrateToExpressions
src/style/style_layer.ts - endWith
src/util/primitives.ts - pointsInside

Low risk:
src/render/draw_debug.ts - devicePixelRatio
src/render/texture.ts - ImageBitmap
src/source/raster_dem_tile_source.ts - ImageBitmap
src/source/raster_dem_tile_worker_source.ts - ImageBitmap
src/render/painter.ts - window./browser.
src/render/program/circle_program.ts - browser.
src/render/program/line_program.ts - browser.
src/render/program/symbol_program.ts - browser.
src/source/canvas_source.ts - HTMLCanvasElement
src/source/geojson_source.ts - browser.
src/style-spec/migrate/v8.ts - source['url']
src/style/style.ts - options.validate : true; (used to be isMapboxUrl)
src/ui/camera.ts - convert
src/ui/control/attribution_control.ts - _updateEditLink
src/ui/control/fullscreen_control.ts - window.document
src/ui/control/geolocate_control.ts - _setupUI
src/ui/handler_manager.ts - window.
src/ui/map.ts - BitmapImage, window, redraw
src/ui/popup.ts - window
src/util/ajax.ts - accesstoken removal, window
src/util/dom.ts - passiveSupported, InstallTrigger
Point.ts - was copied from mapbox
src/util/tile_request_cache.ts - window, isFresh
src/util/webp_supported.ts - window.
src/util/worker_pool.ts - new WebWorker

**Comment by wipfli** [comment]
`mat4.scale(m, m, [1, 1, mercatorZfromAltitude(1, this.center.lat) * this.worldSize, 1]); // 1 at the end`

Removing this 1 at the end is necessary because `mat4.scale()` needs scales a `mat4` by a `vec3`. See https://glmatrix.net/docs/module-mat4.html.

**Comment by HarelM** [comment]
I know, and yet... :-)

**Comment by HarelM** [comment]
Last two commits didn't seem to change much the failing tests.
I have made some ugly hacks locally and the `WriteModeMap` alongside the `WritingMode` enum revert seems to fix some tests (around 11). Unfortunately, I don't like the ugly solution I found (remove the enum and use regular numbers).
I won't commit this just yet... I have updated the summary with my findings.

**Comment by chippieTV** [comment]
Minor changes to keep enum and get your 11 test fix win.. I could put in a PR for this commit, but I'm trying to find the minimum changes from the reverts so we keep as much of the good changes as possible. I think approaching this from both directions is good and we meet in the middle somewhere. 

```
diff --git a/src/data/bucket/symbol_bucket.ts b/src/data/bucket/symbol_bucket.ts
index c044697d1..a72423117 100644
--- a/src/data/bucket/symbol_bucket.ts
+++ b/src/data/bucket/symbol_bucket.ts
@@ -23,7 +23,7 @@ import {TriangleIndexArray, LineIndexArray} from '../index_array_type';
 import transformText from '../../symbol/transform_text';
 import mergeLines from '../../symbol/mergelines';
 import {allowsVerticalWritingMode, stringContainsRTLText} from '../../util/script_detection';
-import {WriteModeMap, WritingMode} from '../../symbol/shaping';
+import {WritingMode} from '../../symbol/shaping';
 import loadGeometry from '../load_geometry';
 import toEvaluationFeature from '../evaluation_feature';
 import mvt from '@mapbox/vector-tile';
@@ -356,7 +356,7 @@ class SymbolBucket implements Bucket {
     sourceLayerIndex: number;
     sourceID: string;
     symbolInstanceIndexes: Array<number>;
-    writingModes: Array<number>;
+    writingModes: WritingMode[];
     allowVerticalPlacement: boolean;
     hasRTLText: boolean;
 
@@ -397,7 +397,7 @@ class SymbolBucket implements Bucket {
         this.sortFeaturesByY = zOrderByViewportY && this.canOverlap;
 
         if (layout.get('symbol-placement') === 'point') {
-            this.writingModes = layout.get('text-writing-mode').map(wm => WriteModeMap[wm]);
+            this.writingModes = layout.get('text-writing-mode').map(wm => WritingMode[wm]);
         }
 
         this.stateDependentLayerIds = this.layers.filter((l) => l.isStateDependent()).map((l) => l.id);
diff --git a/src/style/properties.ts b/src/style/properties.ts
index d982e6a42..248e45f8f 100644
--- a/src/style/properties.ts
+++ b/src/style/properties.ts
@@ -465,7 +465,7 @@ export class PossiblyEvaluated<Props, PossibleEvaluatedProps> {
 
     constructor(properties: Properties<Props>) {
         this._properties = properties;
-        this._values = (Object.create(properties.defaultPossiblyEvaluatedValues) as any);
+        this._values = Object.create(properties.defaultPossiblyEvaluatedValues);
     }
 
     get<S extends keyof PossibleEvaluatedProps>(name: S): PossibleEvaluatedProps[S] {
diff --git a/src/symbol/shaping.ts b/src/symbol/shaping.ts
index d9e0822af..c68406d2f 100644
--- a/src/symbol/shaping.ts
+++ b/src/symbol/shaping.ts
@@ -22,12 +22,6 @@ enum WritingMode {
     horizontalOnly = 3
 }
 
-export class WriteModeMap {
-    'horizontal': WritingMode.horizontal;
-    'vertical': WritingMode.vertical;
-    'horizontalOnly': WritingMode.horizontalOnly;
-}
```

**Comment by chippieTV** [comment]
sorry if this conversation should happen elsewhere, we might end up with another 450+ comment thread on fixing this stuff if we're not careful!

There are places where 0 was passed for 'no WritingMode'. We have an enum so we can add a 'none' mode.. but what's the best way to call it?

```
function addSymbol(bucket: SymbolBucket,
             iconOffset,
             iconAlongLine,
             feature,
             // false, // original evaluates to 0
             // false as unknown as WritingMode, // to keep ts happy with types
             WritingMode.none, // we can make up our own name for this false/undefined/none case..
             anchor,
             lineArray.lineStartIndex,
             lineArray.lineLength,
```

```
enum WritingMode {
    none = 0, // add this
    horizontal = 1,
    vertical = 2,
    horizontalOnly = 3
}
```

Any preference on what we should call this lack of writing mode?

undefined // feels weird as its a JS keyword
none // maybe makes most sense?
any // typescript type so again feels a bit weird
...? better suggestions?

**Comment by HarelM** [comment]
I like none.
Please submit a PR with the fix to this branch.
Thanks!!

**Comment by chippieTV** [comment]
in the interest of easing the frustration debugging this stuff, I started adding some local console logs in the code that get output to the console when running tests. This was nice but it's hard to compare much so I have been outputting them (only for 1 test so far) to a file so I can compare versions. It's not perfect and I'm sure there's a much better way to do this, but I found that console logging the 'map' instance was quite useful for projection matrices etc.

in `suite_implementation.js` I added like the following

```
import {inspect} from 'util';

...
// inside map.once('load', around line 122 for me or write out whatever you want to compare
fs.writeFileSync(path.join(__dirname, '../notes/tests', options.id), inspect(map), () => console.log('done'));
```

You need to have the full path existing **as it can only write files, not create directories** (if anyone wants to make a better write command it'd be nicer I'm sure), so for the test that I picked, I added the folder `/notes/test/line-triangulation/round`.

I have a clean copy of the repo on 1.x branch with node 10 that I made the same chage to and run to get map from as a base to compare from.

There are some spacing issues so I wrote a poor hacky one-liner to help (I know there are probably better ways but it was quick and good enough)

`npm run build-dev && npm run test-render line-triangulation/round && cat notes/tests/line-triangulation/round | tr -d ' ' | tr , '\n' | tr : '\n' | tr '[' '\n' | \grep . > notes/tests/line-triangulation/round-nospaces`

This outputs a version of the file with commas and colons turned to new lines.. which is useful because I can diff the 1.x with my changes to see what's going on.

Screen Shot 2021-09-23 at 15 21 12

**The one-liner only takes maybe 10 seconds to run and the diff live updates in VSCode.**

Specifically now I am trying to track through where alignedProjMatrix becomes Float32Array as it's created as 64. Anyway I thought it was a little worth sharing as it took me a little while to get my head around how to poke into the running code when running the tests.

**Comment by chippieTV** [comment]
@HarelM 

> Please submit a PR with the fix to this branch.

https://github.com/maplibre/maplibre-gl-js/pull/375/files

**Comment by HarelM** [comment]
I'm honestly out of good ideas, maybe a good night sleep will help.
Seems like the high and medium risk reverts didn't cause tests to stop failing (locally) :-(
Main suspects right now for me are:
1. npm packages upgrade - maybe some of the changes there caused the failures.
2. devicePixelRatio change - removal of browser.devicePixelRatio getter

I hope @chippieTV approach will solve this issue better than mine. It appears that there are a lot of tests related to accuracy (32 - 64 probably) so solving them will get us to the last stretch and I can't seem to find the change in the code related to Float32/64Array as it seems I have reverted all of them, but I guess I didn't.

As a side note, I don't mind if we revert all the changes and have poor typings for a short while to have the tests running successfully and only after that see which changes were not helpful and have them back with better typyings, all this before merging this to main, but that's still far down the road...

Thanks everyone for helping out! This is truly appreciated.

**Comment by chippieTV** [comment]
Sorry for the long sprawling comment, there's a few things to share.

So I think reverting libraries is worth looking into a bit. I tried reverting a couple and saw no difference, although when I originally went through updating the libraries one by one and running tests between, the render tests weren't active in the CI, and I guess I wasn't familiar enough with the project to know what each test was really about. If the render tests were active at the time I may have held off on some of the updates and we might have identified what breaks.. I guess I could go back to 1.x and add libs one by one running render tests to see if one suddenly breaks. It was mentioned in another related issue/PR that doing bisect got to a range of commits where the render tests were mostly working.. this might be a good avenue too.

---

Looking at the pixel diffs, there's a couple of things that I'm trying to follow through the code, but it means understanding a bit deeper how the whole thing bootstraps itself.

### anti-aliasing
Some diffs are just showing jaggies, so there is possibly something that is changing the anti-aliasing settings for WebGL. It could be somewhere defaulting differently, or a different browser version (puppeteer/chrome in the test suite?). I haven't found anything that we have touched specifically related to this yet. In comments anti-aliasing seems to be off by default for performance reasons, again, it's possible that somewhere we have converted an optional bool to something different and it's defaulting differently. I will try updating some tests with explicit anti-aliasing on to see if it 'fixes' those, and if so, try to trace further into why it's defaulting differently in 2.0.

### overdraw
The diff for `debug/overdraw` is showing lines slightly brighter in some places, and it looked like maybe there was some blending or vector precision issue where tiles 'overlap', however looking at the original tiles in QGIS, **they do not** overlap..

Screen Shot 2021-09-24 at 9 54 25

Originally I thought the point of 'overdraw' is to extend lines at the tile's bounding box or something to avoid gaps, but according to the comment for overdraw inspector:

```
* Gets and sets a Boolean indicating whether the map should color-code
* each fragment to show how many times it has been shaded.
* **White fragments have been shaded 8 or more times**.
* Black fragments have been shaded 0 times.
* This information is useful for debugging.
```

It essentially sets all fragment shaders to return white pixels overriding the output of `gl_FragColor`. I assume that something higher up is updating the opacity and blending these outputs.

I haven't quite found what about this is useful for debugging but I'll keep digging.

I also tried to add `precision highp float` to all frag shaders as in #376 by adding it to  `_prelude.fragment.glsl` (probably not ok for performance but just to test) and it didn't improve on any render tests.

**Comment by chippieTV** [comment]
@HarelM  you mentioned `devicePixelRatio`.. so I dug a little, I think the changes are OK

In `src/render/program/circle_program.ts` for example,

if I hard code it to 1, it breaks 2 additional tests
if I hard code it to 2, it breaks 33 additional tests

So I assume at least in that file it is doing what it is supposed to.

`test/integration/lib/harness.js:37` defaults `pixelRatio` to 1, individual tests can override it.

**Comment by chippieTV** [comment]
Just to confirm (I think), the output from shader programs after pragma stuff has been processed and replaced is the same between 1.x and 2.0.

Looking at `within/paint-text`, I opened the expected and actual in Photoshop. Expected has a semi transparent background of 50% opacity as specified in the style.json file for the test, however the actual PNG has an opacity of 94%. Not sure if it's accurate but making 4 copies of 50% opacity gives about 94% opacity in photoshop for the background, so something is maybe calling these shaders too much. It would make sense with the above 'overdraw' debug mode which is specifically to identify when the fragment shader has been run more than 8 times for a pixel.

As a side note, the shaders have `#pragma mapbox:` which gets replaced with regex in `src/shaders/shaders.ts` (or .js depending if it's the compiled version I guess?)

```
// Expand #pragmas to #ifdefs.

function compile(fragmentSource, vertexSource) {
    const re = /#pragma mapbox: ([\w]+) ([\w]+) ([\w]+) ([\w]+)/g;
```

In a separate PR we can update these to maplibre. It's not really a problem in the output code since the string is just used as a hook for the regex to find and replace and doesn't make it into the compiled shaders, but still, replacing in all shaders and this shaders.ts file should remove another Mapbox reference from the project.

**Comment by HarelM** [comment]
Jackpot!! I reverted the npm packages upgrade and to be honest I didn't have a lot of expectations, but it seems like there's only two test failing now: `failed debug/tile-overscaled` (failed in 1.x as well), `errored video/default` (probably related to issues in the code I wrote to allow the tests to run)!
Other things seems to be passing as well. :-)
I think there are commits here that did not help to reduce the failing tests and we should consider reverting them (revering the revert) but we first need to address the last two failing tests and decide what to do with them: ignore them or fix them.
Also we need to decide what to do with the ignored tests - if they are ignored indefinitely why keep them?
Anyway, I'm happy with this progress :-)
Note to self: Alway keep a dog around so I'll have to take it to a walk and find good solutions to my issues :-)

**Comment by HarelM** [comment]
I've added the relevant missing code related to video mocking and fixed the `video/default` test.
So the only failed test that existed before the typescript change fails now I believe. (Yay! :-))

**Comment by HarelM** [comment]
This is now ready for review.
There might be other places here to improve the typings with the matrices etc, but in general this is ready.
For now (and temporary is the new for-ever as everyone knows) I added the failing test to the ignore list.
We can decide what to do with it as part of this code review.

**Comment by wipfli** [comment]
Good job, very happy to see this!

**Comment by wipfli** [comment]
> Note to self: Alway keep a dog around so I'll have to take it to a walk and find good solutions to my issues :-)

🐕 🐶 🐕‍🦺

**Comment by wipfli** [comment]
For the record, `debug/tile-overscaled` looks like this:



And we are going to discard this test by adding it to `test/ignores.json`. Note that this is not the first render test we ignore; already in https://github.com/maplibre/maplibre-gl-js/pull/95 we started ignoring tests that failed at the time of forking. `debug/tile-overscaled` was also already failing at the time of forking, see https://github.com/maplibre/maplibre-gl-js/pull/365#issuecomment-922497962.

**Comment by wipfli** [comment]
I am undoing as many reverts as possible. Please coordinate with me on slack if you are doing the same.

**Comment by HarelM** [comment]
I'm not sure the tests are passing on mac or Windows, I know that they did not fully pass on my local env , I.e. Mac. @msbarry can you see if it fully passes for you on your machine?

**Comment by wipfli** [comment]
I am factoring out the inheritance-related changes to https://github.com/maplibre/maplibre-gl-js/pull/378.

**Comment by msbarry** [comment]
Wow! Nice work on this. Just ran with 76e71c94462fbbfef89a724656c1e69cae98e90d and all render tests appear to be passing:

```
1200 passed (99.1%)
2 passed but were ignored (0.2%)
9 ignored (0.7%)
```

**Comment by wipfli** [comment]
I'm uploading `test/integration/render-tests/index.html` as artifact which I think will contain the test output images. Let's see.

**Comment by wipfli** [comment]
GitHub is quite fun. So the output files of test-render <a href="https://github.com/maplibre/maplibre-gl-js/actions/runs/1272743193">can now be downloaded</a> from the checks:

<a href="https://github.com/maplibre/maplibre-gl-js/actions/runs/1272743193"></a>

Mapbox' website also looks much better than mine...

image

**Comment by wipfli** [comment]
Test failing on `macos-latest` (these tests seem to suffer from some sort of offset):

* fill-extrusion-pattern/@2x
* fill-extrusion-pattern/2x-on-1x-add-image-dds
* fill-extrusion-pattern/feature-expression
* fill-extrusion-pattern/function-2
* fill-extrusion-pattern/function
* fill-extrusion-pattern/opacity
* filter/in
* within/paint-circle
* within/paint-icon
* within/paint-text
* within/within-feature-geojson

Failing on `windows-latest` (mostly aliasing I guess):

* custom-layer-js/depth
* custom-layer-js/null-island
* debug/raster
* debug/tile
* raster-resampling/function
* raster-resampling/literal
* regressions/mapbox-gl-js#7708

**Comment by HarelM** [comment]
@wipfli can you add Windows and mac to git history PR? So we can compare what failed in 1.x vs what's failing now?
I think test-render always ran on linux...?

**Comment by wipfli** [comment]
Result from [running render tests on windows and macos](https://github.com/maplibre/maplibre-gl-js/runs/3708073987?check_suite_focus=true) at commits before the fork and before typescript is that the render tests were always failing on macos and windows.

I will remove these operating systems from the render test CI workflow.

**Review by wipfli — APPROVED** [review]
Congratulations. Thanks for fixing this!

**Comment by wipfli** [comment]
Closes https://github.com/maplibre/maplibre-gl-js/issues/326

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/365

**Pull request merged**
