### PR TITLE
Use center for zoom when mouse above horizon (#3398).

### LINKED ISSUE #3398: Terrain 3D zoom is reversed in high pitch, when pointing above horizon
Demo here: https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

Try holding the mouse over the white sky, and scroll - it'll move in the opposite direction compared to if the mouse is on a mountain.

I'm scrolling my mouse in the same direction direction all the time, but the map zoom in opposite direction depending on what i hover

https://github.com/maplibre/maplibre-gl-js/assets/74932975/0f5ff5da-9fc5-4c2c-b12a-dabc2d525ba7

### PR DESCRIPTION
**Pull request by Pheonor**
## Launch Checklist

Fixes #3398

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [X] Write tests for all new functionality.
 - [X] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you include a before and after video?

**Comment by Pheonor** [comment]
Ok, I record this 2 videos with the same scroll wheel direction under and above the horizon.
Before:

https://github.com/maplibre/maplibre-gl-js/assets/2014432/4ea9d88a-57fb-47b9-96e6-b41c14178b14

After:

https://github.com/maplibre/maplibre-gl-js/assets/2014432/052389e4-ffa2-41d5-9b7c-67b8c05c76e5

**Comment by Pheonor** [comment]
After some manual test, I need to made a change to compute the real horizon position. I will update the PR.

**Comment by HarelM** [comment]
This looks great! Thanks!
I need to figure out why the coverage report is wrong and report lines that are comments etc as uncovered.
I'll use this PR to investigate, I hope it won't be long.

**Comment by HarelM** [comment]
OK, I found the root cause of the coverage issue.
I'll merge this PR now.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
