### PR TITLE
Reinstate CI unit test coverage

### PR DESCRIPTION
**Pull request by rotu**
## Launch Checklist

PR #2044 removed the unit test coverage reports. This PR reinstates them and uploads the coverage reports as build artifacts.

Per https://github.com/maplibre/maplibre-gl-js/pull/2044#issuecomment-1468107043

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [X] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [X] Document any changes to public APIs.
 - [x] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by rotu** [comment]
@HarelM Coverage reports are a cool resource, but we need to increase the baseline coverage (maybe include integration tests too?) before this report really becomes useful.

https://github.com/maplibre/maplibre-gl-js/suites/11560050540/artifacts/598609701

**Comment by HarelM** [comment]
I agree coverage should be increased, but I want to be able to easily see the current coverage on a file that was changed as part of a PR and thus let the PR owner know that they need to improve coverage.
Currently, this is far from easy, even with the zip you added, it's still too complicated.
I tried to add a PR comment about coverage but it didn't work well.
I guess codecov is the best solution for this, but it needs some setup.
In any case, base console coverage is better than nothing.

**Review by HarelM — APPROVED** [review]
Does this need .gitignore changes?

**Comment by rotu** [comment]
Yeah, this is not geared toward 

>  I want to be able to easily see the current coverage on a file that was changed as part of a PR and thus let the PR owner know that they need to improve coverage. Currently, this is far from easy, even with the zip you added, it's still too complicated.

Can you point me to a repo that does this well? I bet it's not too hard to check for coverage changes on PR (though I still have reservations about doing this while integration/render tests aren't considered in coverage numbers).

> I tried to add a PR comment about coverage but it didn't work well.

I don't know what you mean by this.

> Does this need .gitignore changes?

Nope. `coverage` is already in the gitignore.

**Comment by HarelM** [comment]
See here - I was hoping this action might do the trick, there might be other actions, IDK, I'm using codecov in another project and it works well.
https://github.com/ArtiomTr/jest-coverage-report-action/issues/313#issuecomment-1416768086

This is my other project:
https://app.codecov.io/gh/IsraelHikingMap/Site

**Comment by rotu** [comment]
> See here - I was hoping this action might do the trick, there might be other actions, IDK, I'm using codecov in another project and it works well. [ArtiomTr/jest-coverage-report-action#313 (comment)](https://github.com/ArtiomTr/jest-coverage-report-action/issues/313#issuecomment-1416768086)
> 
> This is my other project: https://app.codecov.io/gh/IsraelHikingMap/Site

I'm keeping this PR as-is. Let's see what we can do with the current coverage reports before we add another action item to each PR.

**Pull request merged**
