### PR TITLE
[Jest] Migrate mapbox gl.test.js

### PR DESCRIPTION
**Pull request by astridx**
## Launch Checklist

With the first two commits I followed this plan for migrating  mapbox gl.test.js: https://github.com/maplibre/maplibre-gl-js/blob/01e9a30de78cec132007bea811c22875500fdf8d/jest-migration.md

Then I got 3 errors:

---
1 Error

```
$ npm run test-jest

> maplibre-gl@2.0.0-pre.5 test-jest
> jest

 FAIL  src/symbol/anchor.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

    > 1 | window.performance.mark = () => { };
        |                                                                                   ^

      at Object.<anonymous> (setup.js:1:83)

 FAIL  src/maplibre-gl.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

    > 1 | window.performance.mark = () => { };
        |                                                                                   ^

      at Object.<anonymous> (setup.js:1:83)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.685 s, estimated 9 s
Ran all test suites.
npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c jest

npm ERR! A complete log of this run can be found in:
```

I solved this error by configuring jsdom as test testEnvironment.

---
2. Error
```

$ npm run test-jest

> maplibre-gl@2.0.0-pre.5 test-jest
> jest

 FAIL  src/maplibre-gl.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /maplibre/maplibre-gl-js/node_modules/@mapbox/tiny-sdf/index.js:3
    export default class TinySDF {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import loadGlyphRange from '../style/load_glyph_range';
      2 |
    > 3 | import TinySDF from '@mapbox/tiny-sdf';
        | ^
      4 | import isChar from '../util/is_char_in_unicode_block';
      5 | import {asyncAll} from '../util/util';
      6 | import {AlphaImage} from '../util/image';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (src/render/glyph_manager.ts:3:1)

 PASS  src/symbol/anchor.test.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        28.475 s
Ran all test suites.
npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c jest

npm ERR! A complete log of this run can be found in:


```

I know you don't like this. But: If I am right, then we need babel-jest to transform external node modules. Because `transformIgnorePatterns` omits the node modules by default, we need to set this variable wiht an emtpy value.

---
3. Error
```

$ npm run test-jest

> maplibre-gl@2.0.0-pre.5 test-jest
> jest

 PASS  src/symbol/anchor.test.ts (8.54 s)
 FAIL  src/maplibre-gl.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    //maplibre/maplibre-gl-js/src/shaders/_prelude.fragment.glsl:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){#ifdef GL_ES
                                                                                      ^^^^^^

    SyntaxError: Unexpected identifier

      2 | // Disable Flow annotations here because Flow doesn't support importing GLSL files
      3 |
    > 4 | import preludeFrag from './_prelude.fragment.glsl';
        | ^
      5 | import preludeVert from './_prelude.vertex.glsl';
      6 | import backgroundFrag from './background.fragment.glsl';
      7 | import backgroundVert from './background.vertex.glsl';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (src/shaders/shaders.ts:4:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        10.581 s, estimated 16 s
Ran all test suites.
npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c jest

npm ERR! A complete log of this run can be found in:

```

I solved this by adding an transformer for raw-values for the glsl-files.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for joining the effort Astrid! 

I'm happy if you take the tests in `src/geo`. 

Regarding `package-lock.json` you probably want to run `nvm use 14` such that you have `npm v6`.

**Comment by astridx** [comment]
> Why do we need to transform js files? The glsl files I get and the jsdom I get, since I mocked a lot of code in stub_loader, most of it is related to jsdom which I hope jest does better than I do...

Jest doesn't support ES6 modules and hence throwing this error. When I searched for a solution for my second Error I found this: https://stackoverflow.com/questions/64999897/jest-syntaxerror-unexpected-token-export

**Comment by HarelM** [comment]
But we are using typescript, this example is for a js file as far as I understand.

**Comment by astridx** [comment]
> Regarding `package-lock.json` you probably want to run `nvm use 14` such that you have `npm v6`.

I have just corrected

**Comment by HarelM** [comment]
I don't know if it's possible without babel, I'll see if I can find a better solution later on tonight.
Let's leave this PR open for now.
If I can't find a better solution I'll approve, fair enough?

**Comment by HarelM** [comment]
I've tried poking around locally and I think you have the right solution.
Having said that, maybe we don't need `ts-jest` as suggested in the SO answer?
I've found this which says that ts-jest is "better", but I don't know...:
https://kulshekhar.github.io/ts-jest/docs/babel7-or-ts/
Let's merge this and continue to other test using this definition, if we find that we need to change it we'll do it.

**Comment by HarelM** [comment]
The changes in the package.lock file are too big to present here.
Are you sure you are using npm version 6 and not 7?

**Comment by wipfli** [comment]
Node 16 brings npm 7 by default, however, we currently use node 14 which uses npm 6 by default. Let's stick to npm 6 for now.

**Comment by astridx** [comment]
I run `npm c`i with node 14.18.0 and npm 6.14.15

**Pull request merged**
