### PR TITLE
Typescript: Fix unit-tests

### PR DESCRIPTION
**Pull request by HarelM**
I'm not 100% sure about this solution but I have the feeling it will be the one with the minimal impact on the code itself.
The idea is to use the tsc output build folder from the unit tests.
Other solution it to migrate the unit tests to typescript and use `ts-node`. My main concern regarding this approach is that it will require to fix a lot of typings due to the fact that some uses of the javascript code it simply forbidden in typescript.
So one step will be to convert the files (which are mostly javascript and not flow) and second step will be to remove a lot of invalid test and fix the exiting remaining tests.
I think the lean approach of using the output folder, for now, is a good direction.
When all the test will run successfully we can have another effort to convert them to typescript and remove invalid tests.
This PR in not complete as not all tests are running suceesfully (related to browser stuff mostly I think).
But I wanted to share my thoughts.
@wipfli @nyurik @chippieTV 
I can work on this PR until all tests succeed or merge this to the TS branch and continue there, either will work for me...

Most of the file changes are simply changing the import to use the output folder.
Other are removing the run-tap batch file and add another command in package.json file and remove flow typings from the code...

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for driving this forward @HarelM. I think it is fine to merge this into the `typescript` branch. You are doing great work here and I think reviewing the entire migration and structuring it into small, understandable steps will only be possible once everything transpiles and passes the tests. Keep going 🐕

**Comment by HarelM** [comment]
OK, I've pushed some more commits related to window.js removal and the usage of stub_loader.
Most of the tests are now passing!!
  12751 passing (2m)
  336 failing

So fixing the remaining shouldn't be hard, probably related to the missing functions in window.js that existed...
I'll use this branch and merge it when all tests are passing...

**Comment by HarelM** [comment]
We need to get to: 16626/16626
Currently: 15964/16241

**Comment by HarelM** [comment]
OK, we are making good progress: 16471/16559
16471 passing (4m)
88 failing
less than 100 assertions (this is how tap counts the tests number) to go which will probably reveal when fixing the other tests.

It is important to note that the last tests I solved were basically reverting fixes we did while fixing the types.
It seems that we get different results when it comes to the changes in matrix,vec,etc and also in the handler of the map using the options.
I'm guessing that some test that fail (that are related to numbers) may fail due to changes made. It's hard to understand what change caused the test to fail though... :-(

**Comment by HarelM** [comment]
OK, the most tests are running, and a small number is failing:
1. frustum is failing due to precision inaccuracy - I think the best approach for now will be to revert changes that cause precision degradation - I've done the same for the `transform.ts` file - revert the code to the original using a lot of `as any` to allow ts compilation and the redo all the possible lines that doesn't cause the test to fail. (It can be seen in this PR - the reverts are mainly to Float64Array stuff).
2. ajax tests and image tests. I have tried to create a mechanism to allow loading of images in nodejs inside `stub_loader`. I though this mechanism works well as it seem to solve the issue when I used it in the integration tests. I don't think that's the case for the `style.test.js` and `image_source.test.js` - both fail on loading of the images and ajax request sutbbing. So both should be handled together... I'm pretty sure the problem there is with the mocking and what the code is doing. the problem is that debugging the tests causes timeout so I need to find a better way (besides logging) to understand what part of the mocking is missing. It won't be straight forward but shouldn't be hard to fix once there's an understanding of what needs to be mocked.
3. Zoom tests - might be related to 1 so I think it's worth looking into them only after solving 1
4. There's a buffer compare that fails in once of the tests for `geojson_worker_source.test.js` not sure what's wrong there honestly, I suggest to leave it to be last.

Other than the above, I think we are good. This is the final stretch :-)

**Comment by HarelM** [comment]
OK. almost all the tests are now passing.
The major changes I did is move all the stubbing logic into the stub_loader and remove it from the tests themself.
I reverted more changes to the `transform.ts` to fix camera tests (for now...?).
The last two tests that are failing are the following file:
`test/unit/source/geojson_worker_source.test.js`
Since tap is intended to allow running from a simple node execution the following will allow debugging without hitting a timeout:
`node --no-warnings --experimental-specifier-resolution=node --experimental-json-modules test/unit/source/geojson_worker_source.test.js`

The tests are failing because the objects are different, but I'm not able to understand what property exactly is different between the two object since tap is not really telling me. there's probably js tool to show the diff that I haven't tried yet but it's getting too late for today...

**Comment by HarelM** [comment]
Seems like the last test and the errors in render tests were originating from the same error.
Thanks to @JannikGM for the help finding the root cause.
I'm merging this branch to typescript branch so we can continue fixing the remaining tests.
Up until now, beside the mocking stuff that needed to be rewritten most issues with the tests are related to changes made in the typescript code. I'll start reviewing all the changes made in the files to see what needs to be reverted to make the tests pass. After everything is passing we can make other changes and fix the tests while doing so.

**Pull request merged**
