### PR TITLE
Webgl context creation issue under high volumn visits

### PR DESCRIPTION
**Pull request by cndv3996**
## Launch Checklist

<changelog>
WebGL context creation issue

Background:
Some of our users complain, as they enter our product, which leveraging MapLibre, they sometimes see “webglcontextcreationerror”.
MapLibre’s default behavior is to quit. Our product will then show blank page.

From the returned failure message, we don’t know the exact reasons. From data of UA, we see all the OS, not sure the root cause and don’t know how to reproduce.

The returned errors look like:
`Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x0000, ErrorMessage = OffscreenContext Creation failed, GpuChannelHost creation failed.`
`Web page caused context loss and was blocked`

Not look like running out of contexts, which definitely have a limit defined by browsers.
Some of our colleagues having experience of Chromium, WebGL development, they think, at creation time of WebGL context, might be a context lost going on (temporarily, generally not going on more than a dozen seconds), and caused the failure.

My plan is to add an async build function to return a Promise<Map>. And use setTimeOut() in the function to try a few times until we got the Map object and a valid WebGL context inside.

Usage example:
`maplibregl.Map.build({
    container: 'map',
    style: 'https://demotiles.maplibre.org/style.json', // stylesheet location
    center: [-74.5, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
}).then((map) => {
    console.info(map);
});`

image

Not sure if the approach is immature?

I think this is not an issue specific to our product. If the user visits are dense and continuous enough, this issue can happen sometimes.
I'd like to share the solution, and expecting other developers to verify and improve.

But if this is not quite compliant to policies of this community, we can skip it. Maybe this kind of workaround should only happen in downstream products?

Tested with following code:
image

Results:
image
</changelog>

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Do you have the data indicating that this solves the issue? Is the error totally gone or do you still see it after the retries are done as well?
What do you mean by "user visits are dense and continuous enough"? This is a client-side issue and not a server-side issue. How would one create a dense visit? by pressing the refresh button? Does this happen only in simulated tests or for real users as well?
Overall, from my point of view, this is more of a patch than a real fix, but if there are more poeple that needs it I don't mind adding this method to the library, but in general, I think people can simply write their own custom code according to their needs (send server info on every failure, define different retries, different interval etc).

**Comment by HarelM** [comment]
I still don't get the dense user part - you mean that the fact that you have a lot of users increases the chance of seeing webgl context failue just because you have more users, right?
Because every browser has its own webgl context and this is not shared by the users...

**Comment by cndv3996** [comment]
> I still don't get the dense user part - you mean that the fact that you have a lot of users increases the chance of seeing webgl context failue just because you have more users, right? Because every browser has its own webgl context and this is not shared by the users...

Yes, Harel, we have many many users.

**Comment by cndv3996** [comment]
> I still don't get the dense user part - you mean that the fact that you have a lot of users increases the chance of seeing webgl context failue just because you have more users, right? Because every browser has its own webgl context and this is not shared by the users...

We have millions of users per day and that yes - even for a very unlikely scenario we could potentially see a significant number of users impacted. You might also note that on certain browsers failure to create WebGl contexts is looking like it's not that uncommon.

If you think we can discuss further, you can reply my work email. We can loop all the stackholders.

**Comment by cndv3996** [comment]
Need to review the change. Abandon for now.

**Pull request closed without merging**
