### PR TITLE
Addition in ChangeLog 

### PR DESCRIPTION
**Pull request by astridx**
Since I think you need to know how to use the `devicePixelRatio `value, I would like to add the entry for
https://github.com/maplibre/maplibre-gl-js/issues/769 in the ChangeLog.

### CODE REVIEW

**Comment by HarelM** [comment]
I'll merge #347 first, so please rebase afterwards.

**Comment by wipfli** [comment]
I will fix the conflict here.

**Review by wipfli — APPROVED** [review]
Thanks @astridx

**Comment by astridx** [comment]
@wipfli Thanks

**Pull request merged**
