### PR TITLE
Bugfix/fix pattern

### PR DESCRIPTION
**Pull request by andreadapisa**
My changes do not include backports from Mapbox projects.

Summary
At high zoom levels there are a ton of pixels between the current pixel and the edge of the pattern polygon.
To guarantee that the drawing is correct, it was needed to increase the float precision to highp.

I found another issue that is caused by the same code:
https://github.com/mapbox/mapbox-gl-native/issues/14321

No change to public APIs

<changelog>[BUG] Fixed a precision problem in patterns shadeds.</changelog>

### CODE REVIEW

**Review by andreadapisa — COMMENTED** [review]
Fixed precision problem in patterns shaders.

**Comment by HarelM** [comment]
Thanks for taking the time to address this issue!
We are still fighting some render problems that were introduced due to typescript changes.
See #367.
So I would like wait a bit until this is fixed to introduce this change...

**Comment by wipfli** [comment]
Please rebase onto `main`. The render tests work now and I would like to hear what they say about your pull request :)

**Comment by andreadapisa** [comment]
Hello, I merged the code and now my PR is ready for review and merging.

There is a unittest that is failed, about zooming on double tap, it zoom also if touchstart events are > 500ms.
I don't understand why it happens.

**Comment by HarelM** [comment]
I've re-ran the tests.
But there's something off with the diff.
Most of the changes here are already in main.
Probably some git stuff...

**Comment by HarelM** [comment]
Can you please rebase/remerge/redo the changes?
Also please add a test to make sure this functionality is working as expected.

**Comment by andreadapisa** [comment]
Thank you, now all checks have passed.

I changed only two files (shaders) and all others files were changed by merging the main branch.
I'm checking what is happen, but I think to create a new PR.

About the test to add, could you suggest me how can I test a quality issue?

Before:

After:

**Comment by andreadapisa** [comment]
Replaced by new Pull Request #416

**Pull request closed without merging**
