### PR TITLE
Terrain3d - Put back 'mtk' encoding

### PR DESCRIPTION
**Pull request by acalcutt**
This pull request is to address https://github.com/maplibre/maplibre-gl-js/issues/1047 . It puts back 'mtk' encoding which was removed in  https://github.com/maplibre/maplibre-gl-js/commit/84674ef7df31c1c209404d1015b3d30cb5f7e79d . 

Since the 'mtk' encoding was removed, a custom exaggeration of 0.33 has to be used when using the mapboxtoolkit terrain source we are are using in our examples. When using other sources, exaggeration either need to be 1 or undefined, which leads to confusion.

This puts back 'mtk' encoding from the previous release and changes the examples to use that by default. This should make it so all source types can use an "exaggeration: 1" or undefined and get consistent results.

Here are some examples with this change. One uses the mapboxtoolkit with 'mtk' encoding, the other uses my 'mapbox' encoded source. I didn't have a terrarium source to test with,  but from the other post it sounds like a terrarium exaggeration of 1 would be consistent with these now.

'mtk' tile source example (using mapbox toolkit terrain source)
https://stackblitz.com/edit/web-platform-ybg8z4?file=index.html
mtk

'mapbox' tile source example (using my mapbox tiles made with rio-rgbify)
https://stackblitz.com/edit/web-platform-ihxkyl?file=index.html
mapbox

Without this, if you use mapboxtoolkit source without settings the custom 0.33 exageration, you get this, which isn't consistent at all
https://stackblitz.com/edit/web-platform-j8qkzs
mapboxtoolkit_mapbox_without_exaggeration

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Include before/after visuals or gifs if this PR includes visual changes.
 - [~ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
@prozessor13 can you comment on the decision to remove the support of mtk?

**Comment by prozessor13** [comment]
MTK encodes heights in steps of 0.03 meters instead of 0.1. Everything else is like the normal mapbox encoding. Reason: with this setting the hillshadings look much nicer in high zoomlevels. Based on this [thread](https://github.com/mapbox/mapbox-gl-js/issues/6027) i choosed this value by trial and error, so i think this should not be a standard. Furthermore the TerrainRGB Tiles gets bigger in size, and for terrain such a precision is not needed at all. So this TerrainRGB tiles are only a pragmatic solution to comply the needs of our company.

**Comment by prozessor13** [comment]
I discussed this issue in our company and the result is, that our global raster-dem-service is not designed to be a free service. So how deal with this issue?
I can create a test-region with the default-mapbox encoding, or i can help someone to create such a service. Or exists such a service? I can remember something on S3?

**Comment by HarelM** [comment]
Can I close this then?

**Comment by acalcutt** [comment]
Sure, I'll close it.

**Pull request closed without merging**
