### PR TITLE
added setTransformRequest to map to allow dynamically setting the transformRequestFn

### PR DESCRIPTION
**Pull request by thaddmt**
## Description
- Added api for setting a transformRequest instead of only being set in the constructor
  - This allows the map object to be created (without setting style so no rendering) and for the transformRequest to be dynamically set after the map object's instantiation
  - EX: 
```
var map = new Map({
     container: "map",
     center: [-123.1187, 49.2819],
     zoom: 10,
   });
map.setTransformRequest((url: string, resourceType: string) => {});
map.setStyle(style);
```

## Launch Checklist

 - [x] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs

### CODE REVIEW

**Review by lseelenbinder — APPROVED** [review]
This is great. Thanks @thaddmt!

**Comment by lseelenbinder** [comment]
@nyurik it appears we have an unrelated CI test failure (`test-browser`) across a few MRs now. Should we merge regardless or do you want to fix that before we proceed with these merges?

**Comment by thaddmt** [comment]
> @nyurik it appears we have an unrelated CI test failure (`test-browser`) across a few MRs now. Should we merge regardless or do you want to fix that before we proceed with these merges?

@lseelenbinder is there anything I can do to help here?

**Comment by wipfli** [comment]
We updated the CI recently. Maybe you can fetch upstream and merge it into your branch?

**Comment by wipfli** [comment]
Thanks for contributing 🐟

**Comment by wipfli** [comment]
Uh we forgot the changelog. Can you add an entry?

**Comment by thaddmt** [comment]
Sorry about that will add

**Comment by blq** [comment]
I know this is merged, but did you consider an API method like maybe `map.registerTransformRequest(xfrm)`, that would push xfrms in a queue and applied in a first-match style? I.e if an xfrm returns undefined the next one is tested until one returns an url-object.
You could of course implement such functionality by injecting it in this setTransformRequest, but thought I'd bring it up.

**Pull request merged**
