### PR TITLE
270 update dependencies

### PR DESCRIPTION
**Pull request by chippieTV**
- [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] briefly describe the changes in this PR

```
update testem to 3.5.0
update eslint
update selenium (from beta.4 to rc-1)
update rollup, plugin-strip and remove deprecated rolllup @types
update react, react-dom and types
update @babel/core to 7.15.0
update stylelint 9.10.1 -> 13.13.1, types and config
patch update to @types/jsonwebtoken
patch update to @types/request
update tape to 5.3.1
update sinon to 11.1.2 and types
update semver to 7.3.5
update chalk to 4.1.2
update browserify to 17.0.0
update cssnano to 5.0.8
update pngjs to 6.0.0 and types
update patch @babel/core 7.15.4
update puppeteer to 10.2.0
update json-stringify-pretty-compact to 3.0.0
update ejs to 3.1.6 and types
update st to 3.0.0
```

These were separate commits however rebasing ontop of main from typescript causes too many conflicts, so I squashed before cherry-picking to get this branch updated.

Original PR https://github.com/maplibre/maplibre-gl-js/pull/295

**before**
```
Package                                Current      Wanted      Latest  Location
@babel/core                             7.14.6      7.15.4      7.15.4  maplibre-gl
@mapbox/gazetteer                        4.0.4       4.0.4       5.1.0  maplibre-gl
@mapbox/mapbox-gl-supported              1.5.0       1.5.0       2.0.0  maplibre-gl
@octokit/rest                          16.43.2     16.43.2     18.10.0  maplibre-gl
@rollup/plugin-strip                     1.3.3       1.3.3       2.1.0  maplibre-gl
@types/d3                              4.13.12     4.13.12       7.0.0  maplibre-gl
@types/diff                              4.0.2       4.0.2       5.0.1  maplibre-gl
@types/ejs                               2.7.0       2.7.0       3.1.0  maplibre-gl
@types/jsonwebtoken                      8.5.4       8.5.5       8.5.5  maplibre-gl
@types/pngjs                             3.4.2       3.4.2       6.0.1  maplibre-gl
@types/puppeteer                        1.20.8      1.20.8       5.4.4  maplibre-gl
@types/react                          16.14.11    16.14.14     17.0.19  maplibre-gl
@types/react-dom                       16.9.14     16.9.14      17.0.9  maplibre-gl
@types/request                          2.48.6      2.48.7      2.48.7  maplibre-gl
@types/rollup-plugin-sourcemaps          0.4.2       0.4.2       0.5.0  maplibre-gl
@types/sinon                             7.5.2       7.5.2      10.0.2  maplibre-gl
@types/stylelint                        9.10.1      9.10.1     13.13.2  maplibre-gl
@types/tape                             4.13.1      4.13.2      4.13.2  maplibre-gl
@typescript-eslint/eslint-plugin        4.29.1      4.30.0      4.30.0  maplibre-gl
@typescript-eslint/parser               4.29.1      4.30.0      4.30.0  maplibre-gl
browserify                              16.5.2      16.5.2      17.0.0  maplibre-gl
chalk                                    3.0.0       3.0.0       4.1.2  maplibre-gl
cssnano                                 4.1.11      4.1.11       5.0.8  maplibre-gl
d3                                      4.13.0      4.13.0       7.0.1  maplibre-gl
diff                                     4.0.2       4.0.2       5.0.0  maplibre-gl
documentation                           12.1.4      12.1.4      13.2.5  maplibre-gl
ejs                                      2.7.4       2.7.4       3.1.6  maplibre-gl
eslint-plugin-import                    2.24.0      2.24.2      2.24.2  maplibre-gl
eslint-plugin-jsdoc                     36.0.6      36.0.8      36.0.8  maplibre-gl
eslint-plugin-react                     7.24.0      7.25.1      7.25.1  maplibre-gl
jsdom                                   13.2.0      13.2.0      17.0.0  maplibre-gl
json-stringify-pretty-compact            2.0.0       2.0.0       3.0.0  maplibre-gl
node-notifier                            5.4.5       5.4.5      10.0.0  maplibre-gl
npm-packlist                             2.2.2       2.2.2       3.0.0  maplibre-gl
nyc                                     13.3.0      13.3.0      15.1.0  maplibre-gl
pngjs                                    3.4.0       3.4.0       6.0.0  maplibre-gl
puppeteer                               1.20.0      1.20.0      10.2.0  maplibre-gl
react                                  16.14.0     16.14.0      17.0.2  maplibre-gl
react-dom                              16.14.0     16.14.0      17.0.2  maplibre-gl
rollup                                  2.56.1      2.56.3      2.56.3  maplibre-gl
selenium-webdriver                4.0.0-beta.4  4.0.0-rc-1  4.0.0-rc-1  maplibre-gl
semver                                   5.7.1       5.7.1       7.3.5  maplibre-gl
sinon                                    7.5.0       7.5.0      11.1.2  maplibre-gl
st                                       1.2.2       1.2.2       3.0.0  maplibre-gl
stylelint                               9.10.1      9.10.1     13.13.1  maplibre-gl
stylelint-config-standard               18.3.0      18.3.0      22.0.0  maplibre-gl
tap                                     12.4.1      12.4.1      15.0.9  maplibre-gl
tape                                    4.14.0      4.14.0       5.3.1  maplibre-gl
testem                                   3.4.2       3.5.0       3.5.0  maplibre-gl
typescript                               4.3.5       4.4.2       4.4.2  maplibre-gl
```

**after** (below not updated yet)
```
Package        Current   Wanted  Latest  Location
@types/d3      4.13.12  4.13.12   7.0.0  maplibre-gl
@types/diff      4.0.2    4.0.2   5.0.1  maplibre-gl
d3              4.13.0   4.13.0   7.0.1  maplibre-gl
diff             4.0.2    4.0.2   5.0.0  maplibre-gl
documentation   12.1.4   12.1.4  13.2.5  maplibre-gl
jsdom           13.2.0   13.2.0  17.0.0  maplibre-gl
tap             12.4.1   12.4.1  15.0.9  maplibre-gl
```

### CODE REVIEW

**Comment by HarelM** [comment]
Cool.
Can I merge this or is this still in progress?

**Review by HarelM — APPROVED** [review]

**Comment by nyurik** [comment]
I will do one more pass over this PR this weekend, sorry for the delay, this is a pretty big change

**Comment by nyurik** [comment]
my sincere apologies, commented on the wrong PR, please ignore

**Comment by chippieTV** [comment]
It's working but as you can see.. not 100% complete. The remaining libraries require more effort to fix. I think it's good for now and we can open issues for these others later depending if other changes leave some of these packages no longer necessary

summary of issues (for other PRs)

```
Package        Current   Wanted  Latest  Location
@types/d3      4.13.12  4.13.12   7.0.0  maplibre-gl
@types/diff      4.0.2    4.0.2   5.0.1  maplibre-gl
d3              4.13.0   4.13.0   7.0.1  maplibre-gl
diff             4.0.2    4.0.2   5.0.0  maplibre-gl
documentation   12.1.4   12.1.4  13.2.5  maplibre-gl
jsdom           13.2.0   13.2.0  17.0.0  maplibre-gl
tap             12.4.1   12.4.1  15.0.9  maplibre-gl
```

d3 5.0+ causes issues - deprecates queue used in test harness. It is possible to replace with regular promises and no library, or possibly p-queue may be an option: to investigate (for now will not update)

jsdom 17.0.0 causes issues so I rolled back until I have time to investigate and/or step through releases

tap 15 deprecates callbacks in beforeEach and afterEach, remove callbacks (affected tests passing again in other PR, will transfer the changes and update soon)

documentation 13+ breaks testem (npm run start-tests), not sure exactly which version or why yet

diff 5.0.0 breaks test-query

**Comment by HarelM** [comment]
Nice work! I agree the rest can be done separately.
I'm not sure it's worth investing in tap as I would like to replace it with jest.

**Comment by chippieTV** [comment]
when I tried updating Tap to 15, even after fixing the main issue of the deprecated before/after, there are only a couple of errors, 9 of the unit tests fail, so nothing significant.

If we are switching to something else (or investigating how much effort that is) I agree it's not really worth to spend too much time on these, but if there's a quick win it might ease the transition.

The later versions of Tap do support Typescript, so it might be worth looking into pros/cons of the options before committing to anything major. I'm also curious about using AVA, but I think any of these might require significant rewrites of the tests themselves, which would be quite a rabbit hole.

Running against the .ts files should mean for Tap at least we don't need to run the build first. It's not very heavy to build so not a huge time saver, but probably a little cleaner to work with..

**Comment by HarelM** [comment]
I agree. You see it the way I do. Converting the tests to typescript and referencing the ts files would be ideal, but not super urgent.
Regardless, Can I merge this PR?

**Comment by chippieTV** [comment]
yes please!

**Comment by wipfli** [comment]
I propose we enable dependabot with the following `.github/dependabot.yml` config file:

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/d3"
      - dependency-name: "@types/diff"
      - dependency-name: "d3"
      - dependency-name: "diff"
      - dependency-name: "documentation"
      - dependency-name: "jsdom"
      - dependency-name: "tap"
```

Any objections or other input?

**Comment by HarelM** [comment]
Go ahead.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/commit/4201c0ef3b928fc220fd7afe1b0b1353ff51b39d

**Pull request merged**
