### PR TITLE
Fix Jest `done.fail()` 2

### PR DESCRIPTION
**Pull request by astridx**
Please see https://github.com/maplibre/maplibre-gl-js/pull/740

### CODE REVIEW

**Comment by HarelM** [comment]
I wanted to do that :-)
I think I found done.fail too that needs fixing, can you please check?

**Comment by HarelM** [comment]
Don't forget to add it to the function call :-)

**Comment by astridx** [comment]
> I think I found done.fail too that needs fixing, can you please check?

I do not find another `done.fail`. Perhaps you mean this: https://github.com/maplibre/maplibre-gl-js/pull/903

**Comment by astridx** [comment]
> Don't forget to add it to the function call :-)

Thanks. You are right. In this case I would use `expect(false).toBeTruthy();`. What do you think?

**Comment by HarelM** [comment]
Just use like in the lower file: done('failed...')

**Comment by astridx** [comment]
> Just use like in the lower file: done('failed...')

Do you think this is better than `expect(false).toBeTruthy();`. ? Isn't it simpler without the `done`?

**Comment by HarelM** [comment]
You can't assume the callback will be called before the tests ends, so you have to use done...
And if you have to use done then there's no point in adding an expect false to be true...

**Comment by astridx** [comment]
Changed to the use of done.

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
