### PR TITLE
Minify SVG icons

### PR DESCRIPTION
**Pull request by coliff**
Reduces file size = faster loading

Uses: https://svgo.dev/ via command line

`npx svgo --folder=\"src/css/svg/\"`

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.
 
 Command line output:
 
image

### CODE REVIEW

**Comment by HarelM** [comment]
These svgs are copied into the css.
I prefer to keep them readable here, but shrink them as part of the build process instead of at the source. 
It's visible that they are not shrinked in the css here:
https://unpkg.com/maplibre-gl@4.3.2/dist/maplibre-gl.css

So I think it will be better to go that route, what do you think?

**Comment by coliff** [comment]
ah ok, I'm fine if you want to close this then but I think there are a few micro-optimisations with the changes in this PR though.

I set the script to pretty-print them so they are more human-readable... let me know what you think.

**Comment by HarelM** [comment]
The only change is the addition of the viewbox, is this a must?

**Comment by coliff** [comment]
> The only change is the addition of the viewbox, is this a must?

I made a single commit to revert a change in removing viewBox, but overall the PR does a lot more... view source diff in GitHub Web UI to see - it makes the SVGs easier to read and visually parse:

image

**Review by HarelM — APPROVED** [review]

**Pull request merged**
