### PR TITLE
Release 2.3.1-pre.2

### PR DESCRIPTION
**Pull request by birkskyum**
Changelog since 2.3.1-pre.1

- Improve expression types ([#1510](https://github.com/maplibre/maplibre-gl-js/pull/1510))
- Improve performance for primitive size selection ([#1508](https://github.com/maplibre/maplibre-gl-js/pull/1508))
- Fix query tests on windows ([#1506](https://github.com/maplibre/maplibre-gl-js/pull/1506))
- Upgrade target from ES2017 to ES2019 ([#1499](https://github.com/maplibre/maplibre-gl-js/pull/1499))

### CODE REVIEW

**Comment by HarelM** [comment]
Are we good with testing the assert stuff?

**Comment by birkskyum** [comment]
That was actually my motivation for making the pr. I don't think it's likely to break anything in the way we approached it, but if we slipped and it does happens anyway, it would be great to quickly be able to triage and potentially roll a change back - and that becomes harder for every PR we merge in on top.

**Comment by birkskyum** [comment]
@HarelM , I've converted it to another pre-release.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
I'm fine either way actually, just wanted to know where you stand.
I've been testing this pre-release and I haven't seen any new warnings or exception in my code, but let's see if anything rises from the community in the next few days/couple of weeks and if nothing new rises we can release an official one.

**Pull request merged**
