### PR TITLE
Migrate JSDocs to TSDocs

### LINKED ISSUE #2150: Bring in the docs repo
## Motivation

The docs repo is using an npm package of this repo, which basically is saying that it is coupled with the code here.
In order to streamline the docs and also maybe allow using the examples as "debug pages" it is advised to move the docs into this repo.
This was somewhat discussed here: #2148

## Design Alternatives

Keep the current setup and continue this split which doesn't really make sense.

## Acceptance criteria for the bounty

1. A design of how everything is going to work is presented and accepted, in this design the following should be considered (but they don't have to be implemented) - if needed, a separate bounty can be set for this.
  1.1. How to support in the future the ability to see docs of previous versions
  1.2. Do we want to allow seeing the docs for the main version (not the released one), if so, how?
  1.3. How do these docs interact with the style-spec docs

### Design

- The docs will be using mkdocs material as the infrastructure for the docs, ~with the ability to support versioning using `mike`~
- The examples will be in the tests folder and copied (and markdown file will be added to then) when building the docs so that that they can be used both for the docs and for debug.
- The docs of the current version can be easily seen when developing locally, no need to publish them.
- All the API comments will use TSdocs that will be converted to markdown using typedoc.
- The style spec docs will be kept separate at this point and there will be a link to them like the current solution, we can decide if we want to use the same infrastructure for the style-spec in the future.

### Implementation tasks

1. Setup mkdocs material configuration
1. Docs CI is running on every PR to make sure the docs are building without errors or warnings.
1. The release CI pipeline is updated to publish the docs on every release.
1. All the jsdocs comments are converted to tsdoc comments
1. The maplibre.org documentation links are still working as before (to some extent)
1. The maplibre-gl-js-docs repo is archived

Link to bounty:
https://github.com/maplibre/maplibre/issues/191

### LINKED ISSUE #2776: Bring in the docs repo - CI
Acceptance criteria:
1. On each CI run the docs build process is ran and checked that there are no errors or warnings
2. When running a release pipeline the docs are build and push to gh-pages branch. note that gh-pages branch is not empty and should be kept that way - we are pushing some build artifact there.

Part of #2150 
@cc: @krishnaglodha

### PR DESCRIPTION
**Pull request by HarelM**
Resolves #2150
Resolves #2776
This will be a PR that will be merged when the branch is ready and all comments are migrated.
Please open PRs against this PR/branch.

- [x] CI - will be solved by 
- [x] Enable TSdocs lint? (mainly `@param` hyphen?)
- [x] Make sure the docs don't have warning when they build
- [x] remove `@memberof` `@instanceof` `@inherits`, `@typedef`, `@name`, `@function`, `@instance`, `@property`
- [x] Event are linking to invalid location and in general are not properly structured in terms of docs, I'll need to see how to properly solve this. Not a blocker
- [x] Make sure example links are working and are backward compatible (?)
- [x] Update the main readme with the relevant links

### CODE REVIEW

**Review by krishnaglodha — APPROVED** [review]

**Comment by HarelM** [comment]
This is ready for review, basically most if not all of the content here was reviewed in the PRs that where merged to this branch.

**Comment by birkskyum** [comment]
Should #2802 be merged in first?

**Comment by HarelM** [comment]
Yes, and also the CI part, as part of the #2776 bounty.
But all the PRs are against this branch, if this is not approved I won't be able to merge.
If you want to re-review everything again that fine too 😀

**Review by birkskyum — APPROVED** [review]

**Comment by birkskyum** [comment]
Would you do the `@param` hyphen replacement as part of this?

**Comment by HarelM** [comment]
IDK, I might as part of enabling the tsdocs lint stuff..

**Comment by HarelM** [comment]
I've finished with most of the tsdoc errors.
I'm giving the events a final touch.
Hopefully a new doc site by the end of the week.

**Comment by HarelM** [comment]
I'm struggling with what appears to be a bug with the markdown plugin:
https://github.com/tgreyuk/typedoc-plugin-markdown/issues/448

I'll leave this for now as I would like to have more groups in the main intro file and currently something doesn't like me there...

**Comment by HarelM** [comment]
The following might also be a solution to the above issue if I don't get any feedback on the issue I opened:
https://github.com/hughrawlinson/typedoc-to-markdown
It's a single file converting the typedoc json output to markdown, which seems **a lot** simpler.

**Comment by birkskyum** [comment]
I only see these items in the toc - should I expect to see also the classes/interface/enums?


Screenshot 2023-07-06 at 10 51 05

**Comment by birkskyum** [comment]
If it's appear to be completely impossible to repair the markdown/mkdocs flow, there is also a potential option to explore if any of the other typedoc plugins work (docusaurus or even hugo) to figure if it's the tsdocs output that's off. Don't know how much adaption of examples that would be though.

**Comment by HarelM** [comment]
The problem is with the markdown plugin, as you can see in the linked issue.
I've checked the typedoc json output and it is valid and with the relevant group.
Docusurus also uses this ("buggy") plugin, so we'll be facing the same issue.
The problem is with the markdown generation, other platforms won't be able to help with this I believe...

**Comment by HarelM** [comment]
Since converting the json file to markdown files shouldn't be complicated, and there is already some code that does that, it might be a possible solution. But's let's wait a bit to see if there's a reasponse.

**Review by birkskyum — APPROVED** [review]

**Comment by HarelM** [comment]
Event Related was now added by adding a config flag to place everything in a different file.
There is still a need to fix the `MapEvent` docs as they are scrambled due to having `@see` and `@exmaple` one after the other.
And also improve the docs above the `on` to link to the relevant places.
I still need to think about how to improve this.
Also the main readme is not pointing relatively to the docs which I need to fix as well.
These are minor fixes, the last part of all this is the CI.
image

**Comment by HarelM** [comment]
With current version the events are now defined in two tables with the `MapLayerEventType` and `MapEventType`.
I have removed the links in the `Map#on` method as they didn't point anywhere and added above that table the relevant link.
I'm good with how it turned out.
Last thing is the main readme and the CI.
Overall this is almost complete.

**Comment by birkskyum** [comment]
All the links inside of the module, like:
https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.AttributionControl/

Was before found at:
https://maplibre.org/maplibre-gl-js-docs/api/markers/#attributioncontrol

Do we have a way to redirect make this backwards compat?

**Comment by HarelM** [comment]
The main links that I believe we will be able to keep are the examples bybredirecting maplibre-gl-js-docs to maplibre-gl-js/docs
I don't think I have a good idea how to keep the old link to classes etc, especially since it's case sensitive and the old links are lowercase...
Having said that, I'm OK with it, classes can change name etc and links to classes my break over time.

**Comment by HarelM** [comment]
I'll merge this and create a pre-release to see that everything is working asv expected.
Once everything is working I'll update the condition not to publish the docs on pre-release.

**Comment by birkskyum** [comment]
Sounds good. I did btw. try the `@next` version of the markdown plugin, but things are breaking, and it's also behind the master branch with 60+ commits, so it's probably best to proceed with the current version.

**Pull request merged**
