### PR TITLE
Fix async assertions

### PR DESCRIPTION
**Pull request by wipfli**
Assertions made in callbacks will only be checked if the test runs in async mode, i.e. ends with a `done()` call. This pull request fixes `attribution_control.test.ts` which was migrated in #543.

### CODE REVIEW

**Comment by wipfli** [comment]
This looks like an actual problem with the migration of this test. @astridx can you have a look at it?

**Comment by astridx** [comment]
Thanks @wipfli . Good that you are paying attention. There has to be a `done `there. I noticed something else we could do better in the test. I submitted a commit. What do you think about that?

**Review by astridx — APPROVED** [review]

**Comment by astridx** [comment]
@wipfli I just realised that you mean the failure of the tests in the CI. That's strange. The tests don't fail for me locally. How is it with you locally?

**Comment by wipfli** [comment]
For me they fail locally too. When I submitted the pull request they passed locally, then I saw the CI failing. After running `npm ci` locally the tests also started to fail locally.

**Comment by astridx** [comment]
> @wipfli For me they fail locally too. When I submitted the pull request they passed locally, then I saw the CI failing. After running `npm ci` locally the tests also started to fail locally.

That is strange. For me it is local fine, But I see it failing in Ci? I am on Ubunut 20.4.

**Comment by astridx** [comment]
If I am correct, then the test is now fine.

We have to [clean up after each test ](https://github.com/maplibre/maplibre-gl-js/pull/583/commits/85df004b5deb5722b459baa5329c8ed6ab57939a)so that node is happy. 

But then tests fail. I think that these tests are already not working properly since[ this change](https://github.com/maplibre/maplibre-gl-js/commit/476ce360b6f27b0abae7a8db1c9dde6bb8629264#diff-9c473852318c57bac25989bc6b1e85a2dc3e53bceff7497b0314c407c6f9d036R114). So we have to change the tests, which count via the variable `times`. I did this [here](https://github.com/maplibre/maplibre-gl-js/pull/583/commits/74aa93d5a668ff6aa057e9a0f42080955b0f37f6).

Please have a look. This is complex. I hope I'm not missing something again.

**Comment by HarelM** [comment]
The `end` and `done` should have the same effect, I'm surprised that the tests were not failing before the typescript migration, this is what is strange to me...
The changes you did basically allow the tests to pass but do not explain how come they didn't fail when using tap...

**Comment by astridx** [comment]
Does anyone know if you can undo it if you accidentally clicked approve?

**Comment by HarelM** [comment]
I think you can review again and "change your mind", can't you?

**Comment by astridx** [comment]
I can add a new comment and request changes. But the possibility of merging the branch remains. Or is this different for you?

**Comment by HarelM** [comment]
No, it's the same for me. But up to us to make sure everything is resolved...

**Comment by wipfli** [comment]
> I'm surprised that the tests were not failing before the typescript migration

Do you actually mean before the typescript migration or did you rather mean to say before the jest migration?

**Comment by wipfli** [comment]
Checking out the repo before this test was migrated to jest, i.e. at 5e9c746, it seems that the test was working. For example, if I change

```diff
---t.equal(attribution._innerContainer.innerHTML, 'Hello World');
+++t.equal(attribution._innerContainer.innerHTML, 'ello World');
```

I get this error when running the unit tests: 

```
test/unit/ui/control/attribution.test.js ............ 20/21
  AttributionControl is hidden if empty
  not ok should be equal
    --- wanted                  
    +++ found                   
    -ello World                 
    +Hello World                
    compare: '==='
    at:
      line: 153
      column: 11
```

**Comment by HarelM** [comment]
I meant before the jest migration, yes... My bad...

**Comment by astridx** [comment]
I'm wondering if it has any effect that[ in the tape tests](https://github.com/maplibre/maplibre-gl-js/blob/e14efeebb1ffc977c102012008456e2a3ad4eb99/test/util/index.js#L5) t, is given to create the map mock, but I left this out in[ our Util method](https://github.com/maplibre/maplibre-gl-js/blob/e14efeebb1ffc977c102012008456e2a3ad4eb99/src/util/test/util.ts#L5). I assumed that this is not necessary in Jest.

**Comment by astridx** [comment]
I took a closer look at the values  `times,  e.sourceDataType , attribution._innerContainer.innerHTML` in the test-methode.

This was the reason why I thought that https://github.com/maplibre/maplibre-gl-js/commit/476ce360b6f27b0abae7a8db1c9dde6bb8629264#diff-9c473852318c57bac25989bc6b1e85a2dc3e53bceff7497b0314c407c6f9d036R114 had an impact on the test. I no longer believe that. Sorry for writing this too early.

## Tape

This is one example test method including the line `        console.log(times + " | " + e.sourceDataType + " | " + attribution._innerContainer.innerHTML);` for tape.

```
test('AttributionControl dedupes attributions that are substrings of others', (t) => {
    const map = createMap(t);
    const attribution = new AttributionControl();
    map.addControl(attribution);

    map.on('load', () => {
        map.addSource('1', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'World'});
        map.addSource('2', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
        map.addSource('3', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Another Source'});
        map.addSource('4', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello'});
        map.addSource('5', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
        map.addSource('6', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
        map.addSource('7', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'GeoJSON Source'});
        map.addLayer({id: '1', type: 'fill', source: '1'});
        map.addLayer({id: '2', type: 'fill', source: '2'});
        map.addLayer({id: '3', type: 'fill', source: '3'});
        map.addLayer({id: '4', type: 'fill', source: '4'});
        map.addLayer({id: '5', type: 'fill', source: '5'});
        map.addLayer({id: '6', type: 'fill', source: '6'});
        map.addLayer({id: '7', type: 'fill', source: '7'});
    });

    let times = 0;
    map.on('data', (e) => {
        console.log(times + " | " + e.sourceDataType + " | " + attribution._innerContainer.innerHTML);

        if (e.dataType === 'source' && e.sourceDataType === 'metadata') {
            if (++times === 7) {
                t.equal(attribution._innerContainer.innerHTML, 'Hello World | Another Source | GeoJSON Source');
                t.end();
            }
        }
    });
});
```
This is the output.


```

0 | undefined | 
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | visibility | Hello World | Another Source | GeoJSON Source
0 | undefined | Hello World | Another Source | GeoJSON Source
0 | metadata | Hello World | Another Source | GeoJSON Source
1 | metadata | Hello World | Another Source | GeoJSON Source
2 | metadata | Hello World | Another Source | GeoJSON Source
3 | metadata | Hello World | Another Source | GeoJSON Source
4 | metadata | Hello World | Another Source | GeoJSON Source
5 | metadata | Hello World | Another Source | GeoJSON Source
6 | metadata | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
7 | undefined | Hello World | Another Source | GeoJSON Source
```


## Jest

### The current stand in `attribution-control.test.ts` added done. (I had forgotten that in my PR)

The output is mainly the same for jest as with tape. But the order of the tests is important. I change this order later, and the output of the test changed! Note: This test is succesful, but we have problems with `npm` and in CI.

First the test-methode:
```
    test('AttributionControl dedupes attributions that are substrings of others', done => {
        const map = createMap();
        const attribution = new AttributionControl();
        map.addControl(attribution);

        map.on('load', () => {
            map.addSource('1', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'World'});
            map.addSource('2', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
            map.addSource('3', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Another Source'});
            map.addSource('4', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello'});
            map.addSource('5', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
            map.addSource('6', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'Hello World'});
            map.addSource('7', {type: 'geojson', data: {type: 'FeatureCollection', features: []}, attribution: 'GeoJSON Source'});
            map.addLayer({id: '1', type: 'fill', source: '1'});
            map.addLayer({id: '2', type: 'fill', source: '2'});
            map.addLayer({id: '3', type: 'fill', source: '3'});
            map.addLayer({id: '4', type: 'fill', source: '4'});
            map.addLayer({id: '5', type: 'fill', source: '5'});
            map.addLayer({id: '6', type: 'fill', source: '6'});
            map.addLayer({id: '7', type: 'fill', source: '7'});
        });

        let times = 0;
        map.on('data', (e) => {
            console.log(times + " | " + e.sourceDataType + " | " + attribution._innerContainer.innerHTML);
            if (e.dataType === 'source' && e.sourceDataType === 'metadata') {
                if (++times === 7) {
                    expect(attribution._innerContainer.innerHTML).toBe('Hello World | Another Source | GeoJSON Source');
                    done();
                }
            }
        });
    });
```
This is the output:
```
    0 | undefined |
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | visibility | Hello World | Another Source | GeoJSON Source
    0 | undefined | Hello World | Another Source | GeoJSON Source
    0 | metadata | Hello World | Another Source | GeoJSON Source
    1 | metadata | Hello World | Another Source | GeoJSON Source
    2 | metadata | Hello World | Another Source | GeoJSON Source
    3 | metadata | Hello World | Another Source | GeoJSON Source
    4 | metadata | Hello World | Another Source | GeoJSON Source
    5 | metadata | Hello World | Another Source | GeoJSON Source
    6 | metadata | Hello World | Another Source | GeoJSON Source

```

### Same as the last, but I deletet all methods in front of the example test-methode.

Next I changed the test Jest-file. I delete all tests before the example test. Now in the output the `innerHTML ` is set later. It is set when `e.sourceDataType` is `visibility`. So it is not reached in our  jests `expect`-methode, because our `if statement` is `if (e.dataType === 'source' && e.sourceDataType === 'metadata')` so `e.sourceDataType === 'metadata'` and not `visibility`. 

 > If I am right, it should not be the case, that a test depends on another test. The behaviour should be the same, if it is the first one or the last one after much other test. That is why I added the `beforeEach `and the `afterEach`. This solves our problems with `npm `in CI and the dependence of the test on other tests. But the test  is failing,  Concretely, all tests that contain the variable `times `fail.

This is the output for the example test-methode:
```

    0 | undefined |
    0 | metadata |
    1 | metadata |
    2 | metadata |
    3 | metadata |
    4 | metadata |
    5 | metadata |
    6 | metadata |
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | visibility | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source
    7 | undefined | Hello World | Another Source | GeoJSON Source

 FAIL  src/ui/control/attribution_control.test.ts (17.629 s)
  AttributionControl
    ✕ AttributionControl dedupes attributions that are substrings of others (5013 ms)

```



## jest with beforeEach and afterEach

In this constellation, it does not matter where the test method is located. And here you can also see why I was initially so sure that the change regarding visability was the cause.



```
    0 | undefined |
    0 | metadata |
    1 | metadata |
    2 | metadata |
    3 | metadata |
    4 | metadata |
    5 | metadata |
    6 | metadata |
    7 | visibility | Hello World | Another Source | GeoJSON Source
    8 | visibility | Hello World | Another Source | GeoJSON Source
    9 | visibility | Hello World | Another Source | GeoJSON Source
    10 | visibility | Hello World | Another Source | GeoJSON Source
    11 | visibility | Hello World | Another Source | GeoJSON Source
    12 | visibility | Hello World | Another Source | GeoJSON Source
    13 | visibility | Hello World | Another Source | GeoJSON Source
    14 | undefined | Hello World | Another Source | GeoJSON Source
    14 | undefined | Hello World | Another Source | GeoJSON Source


```


Sadly I have not yet fully understood why the output varies so much.

**Comment by wipfli** [comment]
Interestingly, the test variable `t` gets passed into the `createMap` function but is not explicitly used. Any idea why this was necessary?

**Comment by wipfli** [comment]
Thanks for sharing this, Astrid. Does this mean that the changes you made, such as `try catch` or the adapted counter thresholds, might be unnecessary? Ideally, we should change the test code as little as possible, I think.

**Comment by astridx** [comment]
I only included` Try/Catch` so that any errors would be caught and not output as errors in the console but as formatted texts by Jest. I think that this can be helpful for debugging, (See the second codeblock in the Callback example here: https://jestjs.io/docs/asynchronous#callbacks)

And in[ another test I](https://github.com/maplibre/maplibre-gl-js/pull/578) have experienced that not reaching `done `can affect other tests if you don't use `try/catch` and if variables are used in the following test and not handled in `afterEach`.

**Comment by astridx** [comment]
> @wipfli  Ideally, we should change the test code as little as possible, I think.
 
I agree.

**Comment by HarelM** [comment]
Thanks for the investigation!
My comments:
Tests should not relay in each other, and test order should not matter.
Before/after each is important for that.
Iv world advise to do the befire each tape equivalent, make sure the tests pass and then translate them to typescript.
This way we are confident jest migration didn't cause the issue...

**Comment by wipfli** [comment]
Sounds like a good idea, Harel. Are you referring to the following block from `test/util/test.js`? 

```js
tap.beforeEach(function (done) {
    this.sandbox = sinon.createSandbox({
        injectInto: this,
        properties: ['spy', 'stub', 'mock']
    });
```

Does jest do the same a `sinon.createSandbox` automatically?

**Comment by wipfli** [comment]
Now I understand the reason behind `try catch`, thanks. Probably it is best to revert the adapted counter thresholds and figure out a good way of encapsulating the individual tests.

**Comment by wipfli** [comment]
To understand this correctly, we will not require sinon anymore once all unit tests are migrated to jest, right?

**Comment by HarelM** [comment]
Sinon will be needed to take ajax, but I don't think we'll need this sandbox stuff...

**Comment by astridx** [comment]
I would like to revert https://github.com/maplibre/maplibre-gl-js/pull/543. I think this conflicts with this PR. What do you think, @wipfli . Should we revert #543 and close this as this test is not working correctly in main at the moment? Then we can start again from scatch.

**Comment by wipfli** [comment]
Sounds good to me, @astridx. Thanks for taking care of this!

**Pull request closed without merging**
