### PR TITLE
Prerelease 2.1.8-pre.2

### PR DESCRIPTION
**Pull request by birkskyum**
Cut a new prerelease because of recent changes to the build pipeline.

### CODE REVIEW

**Comment by birkskyum** [comment]
@wipfli , can the Release action figure out by itself that it is a prerelease?

**Comment by HarelM** [comment]
Changelog changes are missing...

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Feel free to merge and create the release. What's holding us from creating a proper release?

**Comment by wipfli** [comment]
Pre-release is detected by semver based on version in package.json

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
@HarelM let's check with the pre-release that the build is fine. Then we make release. I suggest to do this whenever we touch the build process. In the past, we had broken releases because of a dropped line and other small errors...

**Comment by wipfli** [comment]
I dispatched the release workflow

**Comment by HarelM** [comment]
Sure, no problem. But we should define a timeline and success criteria for this, not just continue to ship pre-releases...

**Pull request merged**
