### PR TITLE
type fix

### LINKED ISSUE #4649: type of `_controlPositions` property of the Map class
I just noticed that the vscode intelljsense does not autocomplate for `_controlPositions` of `Map` class and found out it is due to that it is defined as `Record<string, HTMLElement>`, is that intentionally? Or typed incorrectly since `_controlPositions` cannot be positioned other than what the ControlPosition type is

https://github.com/maplibre/maplibre-gl-js/blob/160b8f9c3feb0c44c7ab233d4cedaac569236e0b/src/ui/map.ts#L448

I fix the type locally and get the nitelljsense working fine as in the following screenshot:

image

### PR DESCRIPTION
**Pull request by JabSYsEmb**
type fix #4649

### CODE REVIEW

**Comment by HarelM** [comment]
Build is failing... But otherwise looks good, thanks!!

**Comment by HarelM** [comment]
This looks like a stale PR.
If you would like to fix the CI run and update the relevant places in the code with the relevant change please let me know.
Closing...

**Comment by geekdenz** [comment]
If this PR is stale, maybe it would be a good practice run for someone like me to repeat the PR with the build fix @HarelM ?

**Comment by HarelM** [comment]
Sure, feel free to rewrite this PR.

**Pull request closed without merging**
