### PR TITLE
Add new logo as grayscale

### PR DESCRIPTION
**Pull request by wipfli**
Adds the new logo as gray scale like the old one was. I did some inkscape stuff with outlines and strokes and paths and what not but now I think it looks very much like the previous version, just with the new shape...

image

This pull request also removes a png with the old logo which we don't use anywhere I think...

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by wipfli** [comment]
This should fail a render test I assume...

**Comment by louwers** [comment]
> This should fail a render test I assume...

Does it get fed to the renderer or is it just layed on top of the canvas?

**Comment by HarelM** [comment]
It shouldn't fail a render test, this control is over the map and not part of the canvas, the render test are comparing the canvas pixels...

**Comment by HarelM** [comment]
Can you please change the base branch to the attribution branch?

**Review by HarelM — APPROVED** [review]

**Pull request merged**
