### PR TITLE
Enable anisotropic filtering only beyond 20 degrees pitch

### PR DESCRIPTION
**Pull request by e-k-m**
Enable anisotropic filtering on tiles beyond 20 degrees pitch to prevent it from compromising image crispness on flat or low-tilted maps. This is a backport of https://github.com/mapbox/mapbox-gl-js/pull/12577. The backport has been authorized see here: https://github.com/mapbox/mapbox-gl-js/issues/12999.

## Launch Checklist

- [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
   
  This is a backport, but has been authorized (https://github.com/mapbox/mapbox-gl-js/issues/12999).

- [x] Briefly describe the changes in this PR.
 
  Enable anisotropic filtering on tiles beyond 20 degrees pitch to prevent it from compromising image crispness on flat or low- tilted maps.
   
- [x] Link to related issues.

  - https://github.com/mapbox/mapbox-gl-js/issues/7331

- [x] Include before/after visuals or gifs if this PR includes visual changes.
   
  Before the fix `paint: { "raster-resampling": "nearest"}` has no effect on Windows and looks like:

  image

  with the fix it is correctly displayed:

  image

- [x] Write tests for all new functionality.
 
- [x] Document any changes to public APIs.
        No changes.

- [ ] Post benchmark scores.
- [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for taking the time to open this PR!
Please copy here the response in the linked thread, either by screenshot or copy-paste so that it will be captured here, just to be on the safe side if mapbox's repo turns private.
Are the images added here yours to upload? While the code is approved, I'm not sure the same applies to the images.
Also, it would be great if you could create something with less images used and that doesn't contain the word mapbox.

**Comment by HarelM** [comment]
I've brought it up to the MapLibre board and we believe this is still problematic, since the developers are not representing Mapbox - the company. Also, unfortunately, they are not lawyers.
I don't think we have a good idea how to resolve this.
Do you work in a company that can help us legally here by any means?

**Comment by e-k-m** [comment]
Thank you for your feedback. I understand and strongly share the concerns of the authorized backport by developers. 

Given the view, that this seems like a trivial and obvious code change that you could easily come up on your own and hence shouldn't be viewed as something original and copyright-protected, would it make sense to withdraw this "strict" backport-PR and create a PR that is an actually "original" fix? Meaning: Usage of own test images, own test configuration, own code comments and own ordering of the `if`-block arguments. 

Concerning the question of legal support, I sadly to not work in a company that could directly over such services.

**Comment by HarelM** [comment]
Yes, It is possible to create an original PR.

**Comment by e-k-m** [comment]
Ok closing this PR and a "original" PR as described above will follow.

**Pull request closed without merging**
