### PR TITLE
Readme on unpkg; tailored for MapLibre GL JS

### PR DESCRIPTION
**Pull request by roblabs**
## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
This is documentation that I wrote to include with a Docs repo commit, https://github.com/maplibre/maplibre-gl-js-docs/commit/3b420b4f419b845d772e598f5c4fdd37b2349185.  

My recommendation is to include this so that MapLibre GL TS developers don't have leave this repo to understand how to use Unpkg.com. 

 - [N/A] Include before/after visuals or gifs if this PR includes visual changes.
 - [N/A ] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [N/A] Post benchmark scores.
 - [N/A] Manually test the debug page.
 - [N/A] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [N/A] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by roblabs** [comment]
Following the lead from other funded/funding appeals (e.g., Webpack), here's it looks like when we update `Package.json` with funding info. 

___

### Before

```bash
# npm fund
maplibre-gl@1.14.0-rc.1
```

---

### After 

```bash
# npm fund
https://github.com/maplibre/maplibre-gl-js?sponsor=1
  └── maplibre-gl@1.14.0-rc.1
```

---

## Webpack funding example

```bash
├─┬ https://opencollective.com/webpack
│ │ └── css-loader@6.7.1, mini-css-extract-plugin@2.6.1, schema-utils@4.0.0, webpack@5.74.0, schema-utils@3.1.1, terser-webpack-plugin@5.3.6, webpack-cli@4.10.0, webpack-dev-server@4.11.1, webpack-dev-middleware@5.3.3
│ └── https://opencollective.com/postcss/
│     └── postcss@8.4.16
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
```

**Comment by HarelM** [comment]
Thanks for taking the time to open this PR!
A few comments:
1. I would split this PR into two separate ones as I don't see how the changes are related
2. I don't understand the need to explain how unpkg works. Who ever needs to read about it can use google search. More so, who ever is using npm enough probably knows this.
3. Don't forget to update package-lock.json with the changes.

**Comment by roblabs** [comment]
@HarelM — thanks for the comments.  My replies inline

> *1. I would split this PR into two separate ones as I don't see how the changes are related*

I forgot to the change my local branch.  But then I realized I wrote the docs part of the commit back in Spring 2021.  Unintentional. 

> *2. I don't understand the need to explain how unpkg works. Who ever needs to read about it can use google search. More so, who ever is using npm enough probably knows this.*

My goal is to have first class documentation, even for new developers & MapLibre adopters.  I would recommend to _not_ send people out to search engines.  Who knows if they do a search they may end up at this repo or our docs repo, https://github.com/maplibre/maplibre-gl-js-docs/commit/3b420b4f419b845d772e598f5c4fdd37b2349185.  Either way I think that _good docs, makes happy developers_.

> *3. Don't forget to update package-lock.json with the changes.

There were no changes to the lock.

**Comment by roblabs** [comment]
Closing for `npm fund` changes in #1689

**Pull request closed without merging**
