### PR TITLE
Use async/await for more readable code.

### PR DESCRIPTION
**Pull request by xabbu42**
I refactored most benchmarks to use async await as I consider that style more readable. I can change the remaining benchmarks too for consistency but there the difference is very minor. I'm assuming browser compatibility is less of an issue with the benchmark code.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by xabbu42** [comment]
the benchmark results are roughly the same: 
[all.pdf](https://github.com/maplibre/maplibre-gl-js/files/9557587/all.pdf)

**Comment by HarelM** [comment]
Looks A LOT BETTER! Thanks!

**Review by HarelM — APPROVED** [review]

**Comment by xabbu42** [comment]
Thanks, I'll convert the remaining benchmarks too then and add a commit to this pull request :-)

**Comment by xabbu42** [comment]
@HarelM Can you review the second commit as well?

**Review by HarelM — APPROVED** [review]

**Pull request merged**
