### PR TITLE
removing debug pages from repo

### PR DESCRIPTION
**Pull request by austyle**
remove debug pages ([#633](https://github.com/maplibre/maplibre-gl-js/issues/633))

## Launch Checklist

 - [ x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ x] Briefly describe the changes in this PR.
 - [x ] Link to related issues.
 - [x ] Include before/after visuals or gifs if this PR includes visual changes.
 - [x ] Write tests for all new functionality.
 - [x ] Document any changes to public APIs.
 - [x ] Post benchmark scores.
 - [x ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by drwestco** [comment]
Does this get rid of *all* of the debug pages? That seems a bit much. It's useful to have a debug page to load to visually verify a new enlistment, or to experiment with features locally.

**Comment by austyle** [comment]
Yes it does remove all debug pages. Per discussion here: https://github.com/maplibre/maplibre-gl-js/discussions/1823, the debug pages are not well documented or maintained which adds to technical debt and developer confusion. There isn't a single source of truth as to what the intent of a debug page is and many of them have been broken for some time. I would recommend setting up a separate repository for them if they are still helpful for one-offs, so that it doesn't contribute to making the core library stale with dead and forgotten code.

**Comment by drwestco** [comment]
Yeah, I get that many of them are stale and of limited use. Still there should be at least one in the repo to serve as a sample / sanity check to verify a working build.

**Comment by HarelM** [comment]
I world recommend keeping 1 satellite and 1/2 vector tiles using the demo tiles

**Comment by HarelM** [comment]
As per TSC discussion and request, the following pages are to be kept:
debug.html
terrain-satellite.html
@drwestco if you have a particular favorite, please indicate which one.
The following issue also comes to mind regarding this: #1938
So I would consider moving those pages to the test folder maybe? IDK.
Also please make sure to remove the `generate-debug-index-file.ts` file (I saw you removed the script that runs it, also make sure the script is not used somewhere, maybe in the postinstall...?)

**Comment by drwestco** [comment]
Keeping debug.html is good for me.

**Comment by austyle** [comment]
updated PR with requirements [here](https://github.com/maplibre/maplibre-gl-js/pull/1934#issuecomment-1352178575)

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Thanks!!!

**Pull request merged**
