### PR TITLE
Update to ts-node 10.9.1

### PR DESCRIPTION
**Pull request by birkskyum**
I added the necessary type assertions for the json imports that were breaking the build.

```ts
import spec from '../v8.json' assert {type: 'json'};
```

### CODE REVIEW

**Comment by HarelM** [comment]
Will this allow upgrading node to latest LTS version? I know this was causing a problem when we tried to upgrade...

**Comment by birkskyum** [comment]
Yes, node 18 and newer ts-node are blocked because of import type assertions and the overall shift to esm. It would be great if we could approach this in small steps, but at this point I think that in order to get much further, we might have to abandon the commonjs build as it would simplify the rollup files a lot and make a major version bump. Unfortunately we can't support firefox yet, because the worker modules [aren't implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687) and firefox is still only target missing [not supported](https://caniuse.com/?search=worker%20module). The benchmark page would also have to be fixed because the build archive is full of commonjs builds.

**Comment by birkskyum** [comment]
I think it would be good to let the whole typescript/node/esm pipeline stabilize a bit before we jump the trigger on this topic - especially the firefox support could be great to have.

**Comment by birkskyum** [comment]
Started over at #1431

**Pull request closed without merging**
