### PR TITLE
[Jest] Migrate `map_events.test.js`

### PR DESCRIPTION
**Pull request by wipfli**
This is work in progress. I just pushed it here to avoid interference :)

### CODE REVIEW

**Comment by wipfli** [comment]
I suspect typings for `map.off` to be wrong. I tried to call this function with three arguments, but I can't:

```
    src/ui/map_events.test.ts:505:60 - error TS2554: Expected 2 arguments, but got 3.

    505         map.off(event as keyof MapLayerEventType, 'layer', spy);
```

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/be9d6cb6f6935f3383d746990d3245d30d7924e8/src/ui/map.ts#L1144-L1145

should allow me to call the `off` method with three arguments, right?

**Comment by wipfli** [comment]
To check that typescript really is the problem here, I resorted to `(map as any).off([three arguemnts])` and the test passed.

**Comment by wipfli** [comment]
Assuming this is actually a problem and not just me getting something wrong, it might make sense to migrate the unit tests to jest before we release version 2.

I am a bit confused. Is this test looking at the internals of the library or does it check the public api of the library that users are going to see? I think it is the first, right?

**Comment by HarelM** [comment]
`off` is probably wrong, checkout how I changed `on` recently to correct the typings.
We can take a look at the definition in the old (version 1.x) .d.ts file to improve `off` and `once`.
If we are not in a hurry to release 2.x I would say that finishing this migration is the preferred.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
