### PR TITLE
Port CJK browser test to render test [#3006, #3162]

### PR DESCRIPTION
**Pull request by bdon**
@HarelM This replaces the code removed in https://github.com/maplibre/maplibre-gl-js/pull/3162 with a normal render test.

* It changes the font used only for the "abcde" to the test fontstack
* it enables `localIdeographFontFamily` to prepare for #3006 

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by bdon** [comment]
I generated the expected.png on Mac, so I expect the failures are because the fonts look different on those platforms.

What's the best way to account for this?

**Comment by HarelM** [comment]
The CI runs uploads an html file with the actual images to Github, it's a bit tricky to find it, but it's there.
You can download it and add the actual images to Github.
Hopes that makes sense...

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Thanks BTW.

**Comment by bdon** [comment]
The Ubuntu test runner for the render tests does not have sufficient font coverage in it's built in fonts, or however the headless chromium runs does not have access, meaning the expected image is tofu: (view with light background)

expected-ubuntu

**Comment by bdon** [comment]
This may be fine as-is, since the behavior is "correct" - if you are looking at CJK fonts on an Ubuntu machine without a full set of fonts, then you just see blank spaces. We would otherwise need to add to the ubuntu-latest image in the CI and cache the fonts since the download should be a couple hundred megabytes.

**Comment by HarelM** [comment]
How is it different from the browser test that ran on Ubuntu? I'm not sure I'm following...

**Comment by bdon** [comment]
I downloaded the image artifact HTML from the browser test that ran on Ubuntu and added it as `expected-ubuntu.png`. This image has "tofu" blank spaces for all the CJK characters, because the `ubuntu-latest` image likely does not have a full set of non-Latin fonts installed that the headless Chromium can use to render on Canvas.

**Comment by bdon** [comment]
> How is it different from the browser test that ran on Ubuntu? I'm not sure I'm following...

(rereading your comment) I don't know where the [ubuntu-runner-base64.txt](https://github.com/maplibre/maplibre-gl-js/pull/3166#diff-0fce86bab7d2f6ad25abbf06d6bb284592fc0d4f71ae583b0c32b4354b00f883) came from. Maybe it was generated outside of GitHub Actions or with a different base image?

**Comment by bdon** [comment]
@HarelM I added CJK fonts to the GitHub actions runner here https://github.com/maplibre/maplibre-gl-js/pull/3166/commits/138c75274c21562c8689cd08678d5fd84aef8c91 which makes the fonts display correctly in the runner. If that step is adding time to the CI runner we could use some caching action for the apt install.

**Comment by HarelM** [comment]
This is strange... the image that is used for the integration (browser) tests is the same image (ubuntu latest).
This runner was able to display these character well, I'm not sure I understand what changed still... weird...

**Comment by bdon** [comment]
@HarelM how do you know the old browser test wasn't generating a broken image, since the assertions weren't working? Is it possible the runner was installing extra packages that might have brought in a font as a dependency?

**Comment by HarelM** [comment]
Yes, it might be that the old tests didn't produce a valid picture since the assertion didn't run for almost a year, the original test I added had a valid picture with the relevant font and I don't remember addind this installation, but it might have been that the previous Ubuntu image had these fonts.
In any case, this PR is great. THANKS!!

**Pull request merged**
