### PR TITLE
upload benchmarks_generated.js for releases as part of the release workflow

### LINKED ISSUE #861: benchmarks_generated.js is not properly deployed on new releases
I don't know what exactly went wrong but benchmarks_generated.js is missing for all 2.0.x releases.
This means that if you follow https://github.com/maplibre/maplibre-gl-js/blob/main/bench/README.md you get an empty page instead of running benchmarks, as https://maplibre.org/maplibre-gl-js/benchmarks/v2.0.5/benchmarks_generated.js does not exist.

### PR DESCRIPTION
**Pull request by xabbu42**
This hopefully fixes #861.

I'm not sure how to test workflows locally so this is as yet untested.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by HarelM** [comment]
You can test this by adding a manual trigger to the upload benchmark yml, this way you can test that the latest is being uploaded.
Once this is working, we'll know that the only problem can be with the tags.

**Review by HarelM — APPROVED** [review]
This is good, please see my comment about adding a manual trigger.

**Comment by xabbu42** [comment]
I'm quite sure upload-benchmarks.yml is ok, as I only remove steps which where never run anyway. I'm a little bit less sure about the release workflow. I don't want to accidentally do a release :-)

**Comment by HarelM** [comment]
You can create a pre release maybe?
In any case, we can check it in our next release...

**Comment by xabbu42** [comment]
Ok, thanks for the review. I'll check if it worked after the next release.

**Comment by birkskyum** [comment]
I think we can make a patch release now, both to land the past 23 commits incl. the cache invalidation fix, and to verify that this workflow works.

**Comment by birkskyum** [comment]
@xabbu42 This is the output we got from the release workflow.

**Comment by xabbu42** [comment]
seems to have worked ok, the only small issue I see is that we now have 2 commits against gh-pages with the exact same commit message "deploy: f47e53c". we should change the commit message for the release workflow to something like "deploy: v2.1.1".

**Comment by birkskyum** [comment]
good idea.

Are these warnings about missing directory and path irrelevant?

**Comment by xabbu42** [comment]
also I forgot to set BENCHMARK_VERSION, so it says "main f47e53c" instead of "v2.1.1".

**Comment by xabbu42** [comment]
I don't know. Perhaps I can look into it tomorrow.

**Comment by xabbu42** [comment]
The warnings about missing directory are a problem with the action we use and can safely be ignored. I opened a pull request to avoid the it: https://github.com/peaceiris/actions-gh-pages/pull/698

**Pull request merged**
