### PR TITLE
Remove elevationOffset and fix below sea-level clipping

### PR DESCRIPTION
**Pull request by birkskyum**
The first two commits just remove the elevation offset.

We have a ~450 elevation offset to move lakes below sea level to places above sea level. It's a workaroud, and it should be removed.

### CODE REVIEW

**Comment by HarelM** [comment]
@birkskyum any updates on this? Is there a way for me to help push this forward?

**Comment by birkskyum** [comment]
I don't have an update on it. I did try to adjust the far plane but always ended up with some side effects when the camera is pitched that I couldn't account for. I'm not actively working on it now.

**Comment by HarelM** [comment]
How did you test it? did you use a debug page of some sort?
Would be super cool to remove this offset as part of version 3.0...
Maybe we can start by creating tests that fail so we'd know if we managed to fix every case when all tests pass?

**Comment by birkskyum** [comment]
I used the terrain-satellite debug page and zoomed to the dead sea

**Comment by HarelM** [comment]
For me the following reproduces the error when using `npm run start-debug`
http://0.0.0.0:9966/test/debug-pages/terrain-satellite.html#11.1/31.5534/35.4903/97.6
image

I have a feeling this following line is the start of the problem:
https://github.com/maplibre/maplibre-gl-js/blob/cfbc39f8316c9624256df48ffff35c3f0f629ea3/src/geo/transform.ts#L847
If I add to the elevation 450 in order to avoid negative values these artifact seems to disappear, I'm jut not 100% sure I know how this camera to sea level is used...

**Comment by HarelM** [comment]
I think I found a solution, I have no clue if it's a valid one.
@birkskyum do you want me to check it in to this branch or a different one?

**Comment by birkskyum** [comment]
Feel free to continue on this one

**Comment by birkskyum** [comment]
@HarelM , I think it's a great solution! There are a few query tests that fail, but overall it seems like it resolves the clipping issue without changing the elevation level.

**Comment by birkskyum** [comment]
The failing tests are all very small changes to the render output, but the benchmarks don't seem affected so it could be a strategy to update the tests.

Screen Shot 2022-09-11 at 00 57 26

**Comment by HarelM** [comment]
I found a prettier solution I think. I'll commit it to this branch.

**Comment by HarelM** [comment]
There's still some issue, for example the following scene:
http://0.0.0.0:9966/test/debug-pages/terrain-satellite.html#13.65/31.62985/35.50558/0/57
image

**Comment by HarelM** [comment]
OK, now it works as expected. :-)
I've changed the logic basically only for the dead sea, other places should behave as before, no hard coded values.
I also did some micro performance improvements so that this won't degrade performance by mistake.
@birkskyum any chance you could write a test or two for this use case? Maybe even a render test and not just unit test?
@prozessor13 any change you can review this? The interesting change is in `transfrom.ts` class, the rest is basically the removal of the offset...

BTW, do we want to keep the ability to have an offset for exotic use cases but default it to 0?

**Comment by birkskyum** [comment]
Because no one asked for elevationOffset in the first place, I think we should nix it.

**Comment by HarelM** [comment]
@prozessor13 any chance for a quick review?
I think this is ready basically.

**Comment by birkskyum** [comment]
The only exotic use case I have for elevationOffset is actually to test the negative render below sea level.

**Comment by prozessor13** [comment]
> @prozessor13 any chance for a quick review?
> I think this is ready basically.

Sure, but I am on vacation, will do it at the end of this week. Regards.

**Comment by HarelM** [comment]
@prozessor13 Thanks! Enjoy your vacation!
@birkskyum I would like to have @prozessor13 review this before this is merged just to be on the safe side.

**Comment by prozessor13** [comment]
Hi,

i think this calculation in transform.ts is not in all cases correct. See:
http://localhost:9966/test/debug-pages/terrain-satellite.html#13.45/31.54164/35.33225/49.6/54
There are white areas of the dead-sea.

I think your code works when center is in the dead sea, but not when the dead sea is beside center. I created a sketch for this. I think the red part is still missing. To calculate the red part you must either know the minimum elevation in the current scene, or use a constant for this, e.g. 450m.

IMG-2568

**Comment by HarelM** [comment]
Ah, interesting :-) I'll think about it some more...

**Comment by HarelM** [comment]
@birkskyum @prozessor13 while I don't think this fix fully solves the issue, I think it's better than now where we have the elevation offset.
There are cases as described above that still needs to be addressed, but I think this is ready to be merged to avoid conflicts in the future.
In general what I think is needed here in order to solve this, which I'm not sure I know how to do mathematically is to find out the places where the camera window crosses the terrain data - since the terrain data is not a mathematical function this makes it harder.
It's might be similar to the problem with the ray/triangle where you need to know where the two planes cross each-other.
IDK.
In any case, I think we can merge this, and try to solve the case above the @prozessor13 drew on paper in a different PR.
What do you think?

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Also worth taking into account that if someone would like to do a map which has elevation data for the bottom of the ocean, the hardcoded 450 won't hold. So we need to make sure the code doesn't have a hard coded value of "bottom of the dead sea" as there are DEM data that are mapping the oceans which might have a lower than -450 elevation...

**Comment by birkskyum** [comment]
A agree that this is quite important to keep working on, especially with the ocean DEM you mention, but I also see this as a step in the right direction.

**Comment by HarelM** [comment]
@birkskyum can you open a changelog change PR to add this breaking change? I forgot to add it...
Also maybe open and issue with the above diagram so that we won't forget to fix this?

**Comment by HarelM** [comment]
I've opened an issue here: https://github.com/maplibre/maplibre-gl-js/issues/1655
So there's only a need to open a PR for changelog changes.

**Pull request merged**
