### PR TITLE
[Jest] Migrate tests/source canvas_source

### PR DESCRIPTION
**Pull request by chippieTV**
- [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

- Migrate src/source/canvas_source.test.ts
- more to add, will push as I do them

### CODE REVIEW

**Comment by chippieTV** [comment]
what's the best flow for this, I want to send an update to this PR but I have already started working on the next file so have commits with that that may not pass CI yet. Should it be PR per test file or folder? Sorry if it's a silly question

**Comment by HarelM** [comment]
You can open a PR per file or per folder, whatever works for you, but once a PR is open use another breach for other PR...

**Comment by chippieTV** [comment]
if we go too fine grained I think we might end up duplicating work, I already say I solved the same problem as Astrid with adding jsdom. Maybe these are just the first few setup things and the rest is just the grind of adding types and fixing TS stuff.

**Comment by HarelM** [comment]
When you open a PR, if it's not a draft, I assume is ready for review and I world like to review a PR once if possible - just to keep in mind :-)

**Comment by HarelM** [comment]
This is ok, as we can easily merge every PR, so this is a good thing.
Use slack to communicate, and share the issue you encounter and fix.
I believe this is because it is the first steps...

**Comment by HarelM** [comment]
Don't forget lint :-)

**Comment by chippieTV** [comment]
my git got corrupted when I did `git reset --soft HEAD~1` .. for some reason it started adding files I didn't specify even when adding explicitly and committing with `git commit -m '...'` .. very weird. Maybe it didn't like when I restored the staged file change from git mv. I've never seen git act like this before :/

I switched to a different copy of maplibre and applied the changes again to commit properly.

**Comment by chippieTV** [comment]
is it possible to re-run `Test Jest/  windows-latest` .. I don't know if it's failing based on what I did or just the CI being flakey, the same thing happened the first time and none of my change in the last commit have anything to do with any settings

**Comment by HarelM** [comment]
We are all learning here :-)
In continue to the slack conversation, the `end()` should be equivalent to the `done` method, so this needs to be fixed in some of the methods.
I'm not sure what to do in case of multiple `end()` in a single test, but I would advise to put some console.log and see which is the last one that should be called and put the `done` call there.

**Comment by HarelM** [comment]
@astridx If you find weird issues in the code open an issue with the relevant description and we'll take care of it after we finish the migration, this is what we did with other big changes.

**Comment by wipfli** [comment]
Our custom codemods script does not cover asynchronous tests as you have correctly seen here. What do you think about changing the default replacements to:

```diff
replace.sync({
    files: args,
    from: /\(t\) =>/g,
-   to: '() =>',
+   to: 'done =>',
});

replace.sync({
    files: args,
    from: /t.end\(\);\n/g,
-   to: '',
+   to: 'done()',
});
```

**Comment by HarelM** [comment]
It might be saver this way, but we need to make sure whoever fixes the test should remove it in case it is not necessary...
So if you change this please also update the readme to indicate that if the done is called at the end of the method it should be remove.

**Pull request merged**
