### PR TITLE
Bump style spec to 19.1.0

### PR DESCRIPTION
**Pull request by birkskyum**
Related #2496 

# Changelog

### ✨ Features and improvements

* Use D50 white point instead of D65 in HCL/LAB color spaces [#146](https://github.com/maplibre/maplibre-style-spec/pull/146)
* Automated migration of not-CSS-Color-specification-compliant hsl color values [#135](https://github.com/maplibre/maplibre-style-spec/pull/135)

### CODE REVIEW

**Comment by HarelM** [comment]
There's a need to update the expected.png of hcl test for this to pass. but I'm sure you know that :-)

**Comment by birkskyum** [comment]
Aah, right, it should be in place now.

**Comment by HarelM** [comment]
Can you share why you changed both the test and the image and not just the image?

**Review by HarelM — APPROVED** [review]

**Comment by birkskyum** [comment]
I changed the expression tests because they independently of the render tests also were breaking due to this change.

**Pull request merged**
