### PR TITLE
Export `Event` class

### PR DESCRIPTION
**Pull request by zdila**
## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

Export `Event` class

 - [x] Link to related issues.

https://github.com/maplibre/maplibre-gl-js/issues/5015

 - [x] Document any changes to public APIs.
 (already documented)
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Can you give a user case where this is needed?

**Comment by HarelM** [comment]
I actually though about replacing evented class with eventemmiter library in some point,
But I don't mind adding it anyway.

**Review by HarelM — APPROVED** [review]

**Comment by zdila** [comment]
Thanks.

eventemitter3 on npm doesn't seem to be actively developed. Maybe browser-native [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget). Also [nanoevents](https://github.com/ai/nanoevents) looks good. In any case I think that extending from even-related class is antipattern. In my case, the `MaplibreGeocodingControl` control itself extends from `GeocodingCotrolBase` class where `GeocodingCotrolBase` is library agnostic and is used also for extending by Leaflet control implementation and so it can't extend from Maplibre `Evented`. I had to use ugly mixins.

**Comment by HarelM** [comment]
Yeah, I agree...

**Pull request merged**
