### PR TITLE
Specify `lang="en"` on all `<html>` elements

### PR DESCRIPTION
**Pull request by Malvoz**
Specifying the [`lang`](https://html.spec.whatwg.org/multipage/dom.html#attr-lang) attribute to declare the default language of documents ensures correct pronunciation by screen readers.

Edit: To clarify, the default language if `lang` is omitted or set to the empty string indicates that the primary language is _unknown_.

For more information, see:
- https://www.w3.org/International/questions/qa-html-language-declarations
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

### CODE REVIEW

**Review by lseelenbinder — APPROVED** [review]
Thanks @Malvoz!

**Comment by lseelenbinder** [comment]
LGTM

**Comment by wipfli** [comment]
@Malvoz thanks for these contributions. The CI problems should now be solved. To make sure that everything is fine, please fetch upstream and merge it into your branch. As soon as the tests pass I can merge this into main. Please to the same for the other open pull request. Thanks.

**Comment by Malvoz** [comment]
@wipfli Done for both PRs, thanks!

**Comment by wipfli** [comment]
Thanks for contributing 🐋

**Pull request merged**
