### PR TITLE
Bump stylelint from 13 to 14

### PR DESCRIPTION
**Pull request by birkskyum**
A few of the newly introduced rules are disabled, because they were to strictt.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks. Why did CI in #828 not fail if these changes are necessary?

**Comment by wipfli** [comment]
Just for completeness, why should we not have these rules and run `npm run lint -- --fix`?

**Comment by birkskyum** [comment]
Dependabot made two PR's, and the one bumping the @types/ succeeded - but the this one failed #839

**Comment by birkskyum** [comment]
These rules will make hundreds of changes to the .css file, stripping away all vendor prefixes, and while most of them can be removed, there are also a few I'm a bit tentative to remove such as https://caniuse.com/?search=user-select, which we currently have like this:
```
.mapboxgl-ctrl-group button.mapboxgl-ctrl-compass {
    cursor: -webkit-grab;
    cursor: -moz-grab;
    cursor: grab;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

Do we have PostCSS set up in such a way that the src/css/maplibre-gl.css can be simplified, and autoprefixer will add these back?

**Comment by HarelM** [comment]
LGTM, I'm not sure how to properly review this though...

**Review by HarelM — APPROVED** [review]

**Pull request merged**
