### PR TITLE
Fix missing types

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

These types were dependencies in 2.0.5 and somehow were moved to be devDependencies although they are needed in when building with typescript code such as angular.

I'll release a new version after this is merged.

### CODE REVIEW

**Comment by HarelM** [comment]
I've added the version bump to this PR to shorten the process...

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
Just out of curiosity, can you link the pull request which moved them to devdeps?

**Comment by HarelM** [comment]
I found part of it here: #810
But this only removes them and not add them back as dev dependencies...

**Comment by HarelM** [comment]
I reviewed it, so I'm to blame unfortunately. Having said that since this was mainly a removal of dependencies I thought it was safe... @birkskyum FYI

**Pull request merged**
