### PR TITLE
`test-render` for 1.x branch

### PR DESCRIPTION
**Pull request by wipfli**
Runs `test-render` on the `1.x` branch. We want to find out if this test is sometimes failing due to the typescript migration.

### CODE REVIEW

**Comment by HarelM** [comment]
Although green, the tests fail, I think...

**Comment by wipfli** [comment]
Why is this green? There are lots of tests that fail and still the exit code is zero. Very confusing.

**Comment by wipfli** [comment]
Line 34'000 or so of the test output (this is way too verbose):

```
481 passed (39.7%)
1 passed but were ignored (0.1%)
10 ignored (0.8%)
719 failed (59.3%)
1 errored (0.1%)
```

**Comment by HarelM** [comment]
This is because it's using the mapbox harness, I guess... Note to self: never write your own test framework :-)

**Comment by wipfli** [comment]
I added a build step before `test-render` and now it exits red. Note that in the release workflow we don't build before `test-render`. This makes no sense but it effectively makes `test-render` exit green.

The CI workflow says in a comment

> # TODO need a data provider for these:

@msbarry or @petr-pokorny-1  do you remember the history of this?

**Comment by HarelM** [comment]
@wipfli what do you think should be our next steps? Does it make sense to try and fix these tests? Do we want to try and find out if they ever passed and if so what broke them?

**Comment by wipfli** [comment]
There hundreds if not thousands of render tests which makes me think that they are essential for test coverage. I would like to go back to earlier versions of this library, possibly even back to the forking commit and see if the render tests ever passed. My intuition however is that we never actually had render tests working in continuous integration. Any help from the people who set up the initial CI scripts would be really helpful. @msbarry @petr-pokorny-1 @nyurik do you know more about the story of `test-render`?

**Comment by msbarry** [comment]
I believe the issue was that the render tests need a provider for vector tiles. The old ones were using mapbox data with an api key, but we need a new one to get the render tests up for maplibre. Do we have a source that we can use for this without any api key? Or an api key one of the providers can let us use for for CI/local developer testing?

**Comment by wipfli** [comment]
Thanks Michael. I think we can use the docs api key for maptiler (thanks @klokan):

`https://api.maptiler.com/maps/streets/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL`

Once this works we could start hosting tiles required for the render tests at https://github.com/maplibre/demotiles.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/352#issuecomment-922188178

**Comment by HarelM** [comment]
Note that there are test that might be failing due to missing tiles etc, but other are failing without using any tiles, for example the following test:
failed combinations/background-opaque--symbol-translucent
The test only has an icon and a background in the style that it test.
I'm not sure the problem of missing provider is the only issue here.
We probably need to see if can find a time where these test passed if there is such time...

**Pull request closed without merging**
