### PR TITLE
Combine release-related documents in a document folder

### PR DESCRIPTION
**Pull request by astridx**
Combine release-related documents in a document folder.

### CODE REVIEW

**Review by HarelM — COMMENTED** [review]
I don't think this is up-to-date anymore, I vote to simply remove this file...

**Comment by HarelM** [comment]
EDIT: `making-a-release.md` is not relevant according to the last few releases I made, I think it should be deleted.

**Comment by astridx** [comment]
Should I close the PR? Or should we leave it open as a reminder that the process is no longer up to date?

**Comment by HarelM** [comment]
No, just delete the making a release file as part of this PR, and if you want to move the correct file that's fine too.

**Review by HarelM — APPROVED** [review]

**Review by HarelM — APPROVED** [review]

**Pull request merged**
