### PR TITLE
Add adjustment to rendering glyphs

### LINKED ISSUE #1002: CJK-fonts text offset ignored
Thanks for your great contributions. CJK fonts become shown in v2.1.6 but another problem occurs.

**maplibre-gl-js version**: v2.1.6

**browser**: Chrome 97.0.4692.99

### Steps to Trigger Behavior

 1. add layer to show text in CJK fonts and set text-offset to it
 2. text-offset looks ignored

### Link to Demonstration

same style apllied to two versions maplibre-gl-js

v2.1.6: https://jsbin.com/regowuluwo/edit?html,output
v1.15.2: https://jsbin.com/duzinusoda/edit?html,output

### PR DESCRIPTION
**Pull request by Kanahiro**
close #1002 

In based on discussion in the issue and https://github.com/mapbox/tiny-sdf/issues/44#issuecomment-1041250292, adjustment codes are added, results are following, it seems good. Someone who review my codes, please judge whether these codes are not backport to `mapbox-gl-js`.

### before

スクリーンショット 2022-02-16 20 49 22

### after(topAdjustment = 27)

スクリーンショット 2022-02-16 20 48 54

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [x] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for taking the time to open this PR!
Do you think you can try and add a render test so that this won't happen in the future?
I think the style you linked in the issue can be a great input to the render tests.
See here for more info:
https://github.com/maplibre/maplibre-gl-js/tree/main/test/integration#writing-new-tests

**Comment by Kanahiro** [comment]
I've tried to make a test with same style in the issue but the issue is not reproduced in `test-render`, I'm not sure but is this only on browser problem...?

```json
// style.json
{
    "version": 8,
    "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
    "sources": {
        "sample": {
            "type": "geojson",
            "data": {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [0, 0]
                        },
                        "properties": {
                            "name_en": "abc",
                            "name_ja": "あいう",
                            "name_ch": "阿衣乌"
                        }
                    }
                ]
            }
        }
    },
    "layers": [
        {
            "id": "sample-text-left",
            "type": "symbol",
            "source": "sample",
            "layout": {
                "text-anchor": "top",
                "text-field": "{name_ja}\n{name_en}",
                "text-font": ["NotoCJK"],
                "text-offset": [-10, 0]
            }
        },
        {
            "id": "sample-text-center",
            "type": "symbol",
            "source": "sample",
            "layout": {
                "text-anchor": "top",
                "text-field": "{name_ja}{name_en}{name_ch}",
                "text-font": ["NotoCJK"],
                "text-offset": [0, 0]
            }
        },
        {
            "id": "sample-text-right",
            "type": "symbol",
            "source": "sample",
            "layout": {
                "text-anchor": "top",
                "text-field": "{name_en}\n{name_ch}",
                "text-font": ["NotoCJK"],
                "text-offset": [10, 0]
            }
        }
    ]
}
```

**Comment by HarelM** [comment]
This might explain why we didn't see this issue... :-/
Can you fix lint?
Can you share the images that were created? You see the text correctly in the generated image? Can you share the image here?

**Comment by Kanahiro** [comment]
expected

This image rendered with above style.json, this is correct.
Positions of texts are not changed even when`const top Adjustment = 27` is not written.

**Comment by HarelM** [comment]
OK, I'll open an issue to see how this can be improved in the future in terms of testing in the browser maybe and not using node execution, as it seems that there are changes between the outputs (which is not that surprising to be honest).
In any case, this issue still needs to be fixed regardless, so please fix the lint errors and I'll merge this.
Thanks again for all your work!

**Review by HarelM — APPROVED** [review]

**Pull request merged**
