### PR TITLE
Fix bad merge, bump version to 1.15.1

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Fix bad css merge, update changelog, prepare to release 1.15.1

 - [x] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by HarelM** [comment]
@curran @thaddmt @Malvoz @roblabs Any chance one of you can review this? there's not much here...

**Review by wipfli — APPROVED** [review]
Looks good to me.

**Comment by wipfli** [comment]
The additional changelog message is probably do to forgetting it earlier, right?

**Comment by HarelM** [comment]
I don't know what happen when I edited the change log. I have updated it now...

**Pull request merged**
