### PR TITLE
Update contribution guidelines for arm64 machines

### PR DESCRIPTION
**Pull request by birkskyum**
I added apple silicon guidelines for rebuilding a few node modules.

The render tests fail for node 16.14, so I updated the version to 16.13.

### CODE REVIEW

**Review by wipfli — COMMENTED** [review]
Isnt it node_modules?

**Comment by HarelM** [comment]
I would prefer nit to change the readme to say nide 16.13 but rather see of we can solve this.

**Comment by birkskyum** [comment]
That would be better of course. I tried to add all the assert json, but it unfortunately didn't seem to fix it - also when updating to node 17. That's when I figured the least I could do was to update the guide.

**Comment by HarelM** [comment]
Yea, that was my experience as well. Weird... Not sure what should be the right fix though.
If we decide to change the readme we should also open an issue to remind us what need to reverted once this issue is fixed I guess...

**Comment by wipfli** [comment]
Probably also put the same version into `.nvmrc` and all CI workflows.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
